"""classification management

Revision ID: 5533831c7522
Revises: 4fc34906c389
Create Date: 2022-09-10 02:25:01.799154

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "5533831c7522"
down_revision = "4fc34906c389"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cls_classification_detail",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("instance_id", sa.Integer(), nullable=True),
        sa.Column("status", sa.Text(), nullable=True),
        sa.Column("dataset", sa.Text(), nullable=True),
        sa.Column("collection", sa.Text(), nullable=True),
        sa.Column("field", sa.Text(), nullable=True),
        sa.Column("labels", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_cls_classification_detail_id"),
        "cls_classification_detail",
        ["id"],
        unique=False,
    )
    op.create_table(
        "cls_classification_instance",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("status", sa.Text(), nullable=True),
        sa.Column("organization_key", sa.Text(), nullable=True),
        sa.Column("target", sa.Text(), nullable=True),
        sa.Column("type", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_cls_classification_instance_id"),
        "cls_classification_instance",
        ["id"],
        unique=False,
    )
    op.drop_index(
        "ix_cls_classification_status_id", table_name="cls_classification_status"
    )
    op.drop_table("cls_classification_status")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cls_classification_status",
        sa.Column("id", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column(
            "classification_status_id", sa.INTEGER(), autoincrement=True, nullable=False
        ),
        sa.Column(
            "classification_status", sa.TEXT(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "classification_status_is_active",
            sa.BOOLEAN(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint(
            "id", "classification_status_id", name="cls_classification_status_pkey"
        ),
    )
    op.create_index(
        "ix_cls_classification_status_id",
        "cls_classification_status",
        ["id"],
        unique=False,
    )
    op.drop_index(
        op.f("ix_cls_classification_instance_id"),
        table_name="cls_classification_instance",
    )
    op.drop_table("cls_classification_instance")
    op.drop_index(
        op.f("ix_cls_classification_detail_id"), table_name="cls_classification_detail"
    )
    op.drop_table("cls_classification_detail")
    # ### end Alembic commands ###
