"""classification management

Revision ID: 69d3ce8a040e
Revises: 4fc34906c389
Create Date: 2022-09-09 03:03:36.016135

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "69d3ce8a040e"
down_revision = "4fc34906c389"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cls_classification_detail",
        sa.Column("id", sa.String(length=255), nullable=False),
        sa.Column(
            "classification_detail_id", sa.Integer(), autoincrement=True, nullable=False
        ),
        sa.Column("classification_detail_status_id", sa.Integer(), nullable=True),
        sa.Column("classification_dataset", sa.Text(), nullable=True),
        sa.Column("classification_collection", sa.Text(), nullable=True),
        sa.Column("classification_field", sa.Text(), nullable=True),
        sa.Column("classification_labels", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", "classification_detail_id"),
    )
    op.create_index(
        op.f("ix_cls_classification_detail_id"),
        "cls_classification_detail",
        ["id"],
        unique=False,
    )
    op.create_table(
        "cls_classification_instance",
        sa.Column("id", sa.String(length=255), nullable=False),
        sa.Column(
            "classification_instance_id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("classification_status_id", sa.Integer(), nullable=True),
        sa.Column("organization_key", sa.Text(), nullable=True),
        sa.Column("classification_target", sa.Text(), nullable=True),
        sa.Column("classification_type", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", "classification_instance_id"),
    )
    op.create_index(
        op.f("ix_cls_classification_instance_id"),
        "cls_classification_instance",
        ["id"],
        unique=False,
    )
    op.create_table(
        "cls_classification_status",
        sa.Column("id", sa.String(length=255), nullable=False),
        sa.Column(
            "classification_status_id", sa.Integer(), autoincrement=True, nullable=False
        ),
        sa.Column("classification_status", sa.Text(), nullable=True),
        sa.Column("classification_status_is_active", sa.BOOLEAN(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", "classification_status_id"),
    )
    op.create_index(
        op.f("ix_cls_classification_status_id"),
        "cls_classification_status",
        ["id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_cls_classification_status_id"), table_name="cls_classification_status"
    )
    op.drop_table("cls_classification_status")
    op.drop_index(
        op.f("ix_cls_classification_instance_id"),
        table_name="cls_classification_instance",
    )
    op.drop_table("cls_classification_instance")
    op.drop_index(
        op.f("ix_cls_classification_detail_id"), table_name="cls_classification_detail"
    )
    op.drop_table("cls_classification_detail")
    # ### end Alembic commands ###
