privacy_experience_configs:
# US (non-GPP) banner and modal
- id: pri-76b8-cc52-11ee-9eaa-8ef97a0-over-config
  origin: pri-76b8-cc52-11ee-9eaa-8ef97a0-over
  name: "US Modal"
  regions:
    - us_ca
    - us_co
    - us_ct
    - us_ut
    - us_va
  component: modal
  allow_language_selection: false
  dismissable: true
  disabled: true
  privacy_notice_keys:
    - data_sales_and_sharing

# US (non-GPP) privacy center
- id: pri-27d4-cc53-11ee-9eaa-8ef97a04-pri-config
  origin: pri-27d4-cc53-11ee-9eaa-8ef97a04-pri
  name: "US Privacy Center"
  regions:
    - us_ca
    - us_co
    - us_ct
    - us_ut
    - us_va
  component: privacy_center
  allow_language_selection: false
  dismissable: true
  disabled: true
  privacy_notice_keys:
    - data_sales_and_sharing

# EU banner and modal
- id: pri-c8ff-78d6-4a02-850f-2c09dda-over-config
  origin: pri-c8ff-78d6-4a02-850f-2c09dda-over
  name: "EEA Banner + Modal"
  regions:
    - be
    - bg
    - cz
    - dk
    - de
    - ee
    - ie
    - gr
    - es
    - fr
    - hr
    - it
    - cy
    - lv
    - lt
    - lu
    - hu
    - mt
    - nl
    - at
    - pl
    - pt
    - ro
    - si
    - sk
    - fi
    - se
    - gb_eng
    - gb_sct
    - gb_wls
    - gb_nir
    - is
    - "no"
    - li
  component: banner_and_modal
  allow_language_selection: false
  dismissable: true
  disabled: true
  privacy_notice_keys:
    - essential
    - functional
    - analytics
    - marketing

# EU TCF
- id: d7c3ce0a-a3b3-43ff-bf6f-3d8-tcf-over-config
  origin: d7c3ce0a-a3b3-43ff-bf6f-3d8-tcf-over
  name: "TCF"
  allow_language_selection: false
  dismissable: true
  disabled: true
  notices: []
  regions:
    - be
    - bg
    - cz
    - dk
    - de
    - ee
    - ie
    - gr
    - es
    - fr
    - hr
    - it
    - cy
    - lv
    - lt
    - lu
    - hu
    - mt
    - nl
    - at
    - pl
    - pt
    - ro
    - si
    - sk
    - fi
    - se
    - gb_eng
    - gb_sct
    - gb_wls
    - gb_nir
    - is
    - "no"
    - li
    - eea
  component: tcf_overlay
  privacy_notice_keys: []