"""empty message

Revision ID: 16977cc2e0e3
Revises: 
Create Date: 2021-09-21 05:00:09.850011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16977cc2e0e3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('policy_rules', sa.Column('policy_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'policy_rules', 'policies', ['policy_id'], ['id'])
    op.add_column('privacy_declarations', sa.Column('system_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'privacy_declarations', 'systems', ['system_id'], ['id'])
    op.add_column('privacy_rules', sa.Column('policy_rule_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'privacy_rules', 'policy_rules', ['policy_rule_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'privacy_rules', type_='foreignkey')
    op.drop_column('privacy_rules', 'policy_rule_id')
    op.drop_constraint(None, 'privacy_declarations', type_='foreignkey')
    op.drop_column('privacy_declarations', 'system_id')
    op.drop_constraint(None, 'policy_rules', type_='foreignkey')
    op.drop_column('policy_rules', 'policy_id')
    # ### end Alembic commands ###
