"""empty message

Revision ID: 318cd13ef54d
Revises: e3eeeb12a75c
Create Date: 2021-09-21 20:46:12.233847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '318cd13ef54d'
down_revision = 'e3eeeb12a75c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
