"""empty message

Revision ID: c2aa80e1df14
Revises: f0a031c9c19e
Create Date: 2021-09-21 14:46:41.104985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2aa80e1df14'
down_revision = 'f0a031c9c19e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_data_qualifiers_fides_key', table_name='data_qualifiers')
    op.create_index(op.f('ix_data_qualifiers_fides_key'), 'data_qualifiers', ['fides_key'], unique=True)
    op.drop_index('ix_data_subjects_fides_key', table_name='data_subjects')
    op.create_index(op.f('ix_data_subjects_fides_key'), 'data_subjects', ['fides_key'], unique=True)
    op.drop_index('ix_data_uses_fides_key', table_name='data_uses')
    op.create_index(op.f('ix_data_uses_fides_key'), 'data_uses', ['fides_key'], unique=True)
    op.drop_index('ix_datasets_fides_key', table_name='datasets')
    op.create_index(op.f('ix_datasets_fides_key'), 'datasets', ['fides_key'], unique=True)
    op.drop_index('ix_organizations_fides_key', table_name='organizations')
    op.create_index(op.f('ix_organizations_fides_key'), 'organizations', ['fides_key'], unique=True)
    op.drop_index('ix_policies_fides_key', table_name='policies')
    op.create_index(op.f('ix_policies_fides_key'), 'policies', ['fides_key'], unique=True)
    op.drop_index('ix_registries_fides_key', table_name='registries')
    op.create_index(op.f('ix_registries_fides_key'), 'registries', ['fides_key'], unique=True)
    op.drop_index('ix_systems_fides_key', table_name='systems')
    op.create_index(op.f('ix_systems_fides_key'), 'systems', ['fides_key'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_systems_fides_key'), table_name='systems')
    op.create_index('ix_systems_fides_key', 'systems', ['fides_key'], unique=False)
    op.drop_index(op.f('ix_registries_fides_key'), table_name='registries')
    op.create_index('ix_registries_fides_key', 'registries', ['fides_key'], unique=False)
    op.drop_index(op.f('ix_policies_fides_key'), table_name='policies')
    op.create_index('ix_policies_fides_key', 'policies', ['fides_key'], unique=False)
    op.drop_index(op.f('ix_organizations_fides_key'), table_name='organizations')
    op.create_index('ix_organizations_fides_key', 'organizations', ['fides_key'], unique=False)
    op.drop_index(op.f('ix_datasets_fides_key'), table_name='datasets')
    op.create_index('ix_datasets_fides_key', 'datasets', ['fides_key'], unique=False)
    op.drop_index(op.f('ix_data_uses_fides_key'), table_name='data_uses')
    op.create_index('ix_data_uses_fides_key', 'data_uses', ['fides_key'], unique=False)
    op.drop_index(op.f('ix_data_subjects_fides_key'), table_name='data_subjects')
    op.create_index('ix_data_subjects_fides_key', 'data_subjects', ['fides_key'], unique=False)
    op.drop_index(op.f('ix_data_qualifiers_fides_key'), table_name='data_qualifiers')
    op.create_index('ix_data_qualifiers_fides_key', 'data_qualifiers', ['fides_key'], unique=False)
    # ### end Alembic commands ###
