# Default Configuration File for Fides


[security] # Configuration settings for Security variables.

# Length of desired encryption key when using Fides to generate a random secure string used for AES encryption.
aes_encryption_key_length = 16 # integer

# Length of desired random byte str for the AES GCM encryption used throughout Fides.
aes_gcm_nonce_length = 12 # integer

# The key used to sign Fides API access tokens.
app_encryption_key = "" # string

# A list of pre-approved addresses of clients allowed to communicate with the Fides application server.
cors_origins = [] # array

# TODO
cors_origin_regex = "" # string

# JWT secret by which passed-in identity is decrypted according to the HS256 algorithm.
drp_jwt_secret = "" # string

# Text encoding to use for the application.
encoding = "UTF-8" # string

# The default, `dev`, does not apply authentication to endpoints typically used by the CLI. The other option, `prod`, requires authentication for _all_ endpoints that may contain sensitive information.
env = "dev" # string

# TODO
identity_verification_attempt_limit = 3 # integer

# The value used to identify the Fides application root API client.
oauth_root_client_id = "" # string

# The secret value used to authenticate the Fides application root API client.
oauth_root_client_secret = "" # string

# Automatically generated by Fides, and represents a hashed value of the oauth_root_client_secret.
oauth_root_client_secret_hash = [] # array

# The time in minutes for which Fides API tokens will be valid. Default value is equal to 8 days.
oauth_access_token_expire_minutes = 11520 # integer

# Sets desired length in bytes of generated client id used for oauth.
oauth_client_id_length_bytes = 16 # integer

# Sets desired length in bytes of generated client secret used for oauth.
oauth_client_secret_length_bytes = 16 # integer

# When using a parent/child Fides deployment, this password will be used by the child server to access the parent server.
parent_server_password = "" # string

# When using a parent/child Fides deployment, this username will be used by the child server to access the parent server.
parent_server_username = "" # string

# The prefix given to keys in the Redis cache used by the rate limiter.
rate_limit_prefix = "fides-" # string

# The number of requests from a single IP address allowed to hit an endpoint within a rolling 60 second period.
request_rate_limit = "1000/minute" # string

# The list of scopes that are given to the root user.
root_user_scopes = [] # array

# If set, this can be used in conjunction with root_username to log in without first creating a user in the database.
root_password = "" # string

# If set, this can be used in conjunction with root_password to log in without first creating a user in the database.
root_username = "" # string

# The number of seconds that a pre-signed download URL when using S3 storage will be valid. The default is equal to 5 days.
subject_request_download_link_ttl_seconds = 432000 # integer

[user] # Class used to store values from the 'user' section of the config.

# When set to true, prevents sending anonymous analytics data to Ethyca.
analytics_opt_out = true # boolean

# An arbitrary string used to encrypt the user data stored in the database. Encryption is implemented using PGP.
encryption_key = "test_encryption_key" # string

[database] # Configuration settings for the application database.

# Number of concurrent database connections Fides will use for API requests. Note that the pool begins with no connections, but as they are requested the connections are maintained and reused up to this limit.
api_engine_pool_size = 50 # integer

# Number of additional 'overflow' concurrent database connections Fides will use for API requests if the pool reaches the limit. These overflow connections are discarded afterwards and not maintained.
api_engine_max_overflow = 50 # integer

# The name of the application database.
db = "default_db" # string

# The password with which to login to the application database.
password = "defaultpassword" # string

# The port at which the application database will be accessible.
port = "5432" # string

# The hostname of the application database server.
server = "default-db" # string

# Number of concurrent database connections Fides will use for executing privacy request tasks, either locally or on each worker. Note that the pool begins with no connections, but as they are requested the connections are maintained and reused up to this limit.
task_engine_pool_size = 50 # integer

# Number of additional 'overflow' concurrent database connections Fides will use for executing privacy request tasks, either locally or on each worker, if the pool reaches the limit. These overflow connections are discarded afterwards and not maintained.
task_engine_max_overflow = 50 # integer

# The database user with which to login to the application database.
user = "defaultuser" # string

[execution] # Configuration settings for execution.

# If set to True, only use UPDATE requests to mask data. If False, Fides will use any defined DELETE or GDPR DELETE endpoints to remove PII, which may extend beyond the specific data categories that configured in your execution policy.
masking_strict = true # boolean

# The amount of time to wait for actions which delay privacy requests (e.g., pre- and post-processing webhooks).
privacy_request_delay_timeout = 3600 # integer

# Whether privacy requests require explicit approval to execute.
require_manual_request_approval = false # boolean

# Whether privacy requests require user identity verification.
subject_identity_verification_required = false # boolean

# The backoff factor for retries, to space out repeated retries.
task_retry_backoff = 1 # integer

# The number of times a failed request will be retried.
task_retry_count = 0 # integer

# The delays between retries in seconds.
task_retry_delay = 1 # integer

[admin_ui] # Configuration settings for Analytics variables.

# Toggle whether the Admin UI is served.
enabled = true # boolean

[notifications] # Configuration settings for data subject and/or data processor notifications

# Sets the notification service type used to send notifications. Accepts mailgun, twilio_sms, or twilio_email.
notification_service_type = "" # string

# When set to True, enables subject notifications upon privacy request completion.
send_request_completion_notification = false # boolean

# When set to True, enables subject notifications upon privacy request receipt.
send_request_receipt_notification = false # boolean

# When set to True, enables subject notifications upon privacy request review.
send_request_review_notification = false # boolean

[logging] # Class used to store values from the 'logging' section of the config.

# The output location for log files. Accepts any valid file path. If left unset, log entries are printed to stdout and log files are not produced.
destination = "" # string

# The minimum log entry level to produce. Also accepts TRACE, DEBUG, WARNING, ERROR, or CRITICAL (case insensitive).
level = "INFO" # string

# The format with which to produce log entries. If left unset, produces log entries formatted using the internal custom formatter. Also accepts 'JSON' (case insensitive).
serialization = "" # string

# If True, PII values will display unmasked in log output. This variable should always be set to 'False' in production systems.
log_pii = false # boolean

[cli] # Class used to store values from the 'cli' section of the config.

# A fully anonymized unique identifier that is automatically generated by the application and stored in the toml file.
analytics_id = "da58cc7566b7e2cf36f98f723edb9789" # string

# When set to True, disables functionality that requires making calls to a Fides webserver.
local_mode = false # boolean

# The protocol used by the Fides webserver.
server_protocol = "http" # string

# The hostname of the Fides webserver.
server_host = "localhost" # string

# The port of the Fides webserver
server_port = "8080" # string

[redis] # Configuration settings for Redis.

# Character set to use for Redis, defaults to 'utf8'. Not recommended to change.
charset = "utf8" # string

# The application will use this index in the Redis cache to cache data.
db_index = 0 # integer

# TODO
decode_responses = true # boolean

# The number of seconds for which data will live in Redis before automatically expiring.
default_ttl_seconds = 604800 # integer

# Whether the application's Redis cache should be enabled. Only set to false for certain narrow uses of the application.
enabled = false # boolean

# The network address for the application Redis cache.
host = "redis" # string

# Sets TTL for cached identity verification code as part of subject requests.
identity_verification_code_ttl_seconds = 600 # integer

# The password with which to login to the Redis cache.
password = "testpassword" # string

# The port at which the application cache will be accessible.
port = 6379 # integer

# Whether the application's connections to the cache should be encrypted using TLS.
ssl = false # boolean

# If using TLS encryption, set this to 'required' if you wish to enforce the Redis cache to provide a certificate. Note that not all cache providers support this e.g. AWS Elasticache.
ssl_cert_reqs = "required" # string

# The user with which to login to the Redis cache.
user = "" # string
