services:
  worker:
    image: ethyca/fides:local
    command: fides worker
    depends_on:
      redis:
        condition: service_started
    restart: always
    environment:
      FIDES__CONFIG_PATH: ${FIDES__CONFIG_PATH:-/fides/.fides/fides.toml}
      FIDES__TEST_MODE: "True"
      FIDES__USER__ANALYTICS_OPT_OUT: "True"
    volumes:
      - type: bind
        source: ./
        target: /fides
        read_only: False
      - /fides/src/fides.egg-info
