services:
  webserver:
    depends_on:
      - postgres_example

  postgres_example:
    command:
      [
        "postgres",
        "-c",
        "logging_collector=on",
        "-c",
        "log_statement=all",
        "-c",
        "log_destination=stderr"
      ]
    image: postgres:12
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres_example
    expose:
      - 6432
    ports:
      - "0.0.0.0:6432:5432"
