services:
  fides:
    depends_on:
      - postgres-test
      - mongodb-test

  postgres-test:
    image: postgres:12
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres_example
    expose:
      - 6432
    ports:
      - "0.0.0.0:6432:5432"
    volumes:
      - ./src/fides/data/sample_project/postgres_sample.sql:/docker-entrypoint-initdb.d/postgres_example.sql:ro

  mongodb-test:
    image: mongo:5.0.3
    environment:
      - MONGO_INITDB_DATABASE=mongo_test
      - MONGO_INITDB_ROOT_USERNAME=mongo_user
      - MONGO_INITDB_ROOT_PASSWORD=mongo_pass
    expose:
      - 27017
    ports:
      - "27017:27017"
    # Because we're using the "-f" flag from a parent directory, this relative path needs
    # to be from the parent directory as well
    volumes:
      - ./src/fides/data/sample_project/mongo_sample.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
