services:
  webserver:
    depends_on:
      - worker
    environment:
      - FIDESOPS__EXECUTION__WORKER_ENABLED=True

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    command: fidesops worker
    depends_on:
      redis:
        condition: service_started
    restart: always
    volumes:
      - type: bind
        source: ./
        target: /fidesops
        read_only: False
      - /fidesops/src/fidesops.egg-info
