services:
  fidesops:
    depends_on:
      - postgres_example
      - mongodb_example

  postgres_example:
    image: postgres:12
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres_example
    expose:
      - 6432
    ports:
      - "0.0.0.0:6432:5432"
    volumes:
      # NOTE: consider running initialization SQL in Python instead of this
      # (see "Initialization scripts" section at https://hub.docker.com/_/postgres)
      - ./data/sql/postgres_example.sql:/docker-entrypoint-initdb.d/postgres_example.sql

  mongodb_example:
    image: mongo:5.0.3
    environment:
      - MONGO_INITDB_DATABASE=mongo_test
      - MONGO_INITDB_ROOT_USERNAME=mongo_user
      - MONGO_INITDB_ROOT_PASSWORD=mongo_pass
    expose:
      - 27017
    ports:
      - "27017:27017"
    volumes:
      - ./data/nosql/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

