[saas_example]
domain = "domain"
username = "username"
api_key = "api_key"
api_version = "2.0"
page_limit = "10"

[mailchimp]
domain = ""
username = ""
api_key = ""
identity_email = ""

[hubspot]
domain = ""
hapikey = ""
identity_email = ""

[stripe]
host = ""
api_key = ""
payment_types = ""
page_limit = ""

[sentry]
host = ""
access_token = ""
identity_email = ""

[segment]
domain = ""
personas_domain = ""
workspace = ""
access_token = ""
namespace_id = ""
access_secret = ""
identity_email = ""
