[saas_example]
domain = "domain"
username = "username"
api_key = "api_key"
api_version = "2.0"
page_size = "10"

[mailchimp]
domain = ""
username = ""
api_key = ""
identity_email = ""

[hubspot]
domain = ""
hapikey = ""
identity_email = ""

[stripe]
domain = ""
api_key = ""
payment_types = ""
page_size = ""
identity_email = ""

[sentry]
domain = ""
access_token = ""
identity_email = ""
erasure_access_token = ""
erasure_identity_email = ""
user_id_erasure = ""
issue_url = ""

[segment]
domain = ""
api_domain = ""
personas_domain = ""
workspace = ""
access_token = ""
namespace_id = ""
access_secret = ""
user_token = ""
identity_email = ""

[sendgrid]
domain = ""
api_key = ""
identity_email = ""

[outreach]
domain = ""
client_id = ""
client_secret = ""
redirect_uri = ""
page_size = ""
requester_email = ""
identity_email = ""

[salesforce]
domain = ""
client_id = ""
client_secret = ""
access_token = ""
username = ""
password = ""
identity_email = ""

[zendesk]
domain = ""
username = ""
api_key = ""
identity_email = ""
