import type {
  AvailableDataset,
  AvailableSystem,
  DataPurpose,
  PurposeCoverage,
  PurposeDatasetAssignment,
  PurposeSystemAssignment,
} from "./types";

export const MOCK_PURPOSES: DataPurpose[] = [
  {
    id: "customer_analytics",
    name: "Customer Analytics",
    key: "customer_analytics",
    description:
      "Collect and analyze customer behavior data to understand engagement patterns, conversion funnels, and product usage across platforms.",
    data_use: "analytics",
    data_categories: ["user.behavior", "system.operations"],
    detected_data_categories: [
      "user.behavior",
      "system.operations",
      "user.device",
      "user.contact.email",
    ],
    data_subjects: ["customer"],
    legal_basis: "legitimate_interests",
    legal_basis_is_flexible: false,
    retention_period_days: 365,
    special_category_legal_basis: null,
    features: ["profiling"],
    sub_types: ["Behavioral analytics", "Usage metrics", "Funnel analysis"],
    updated_at: "2026-03-24T14:30:00Z",
  },
  {
    id: "revenue_analytics",
    name: "Revenue Analytics",
    key: "revenue_analytics",
    description:
      "Process transaction and subscription data to track revenue metrics, churn rates, and customer lifetime value.",
    data_use: "analytics",
    data_categories: ["user.financial", "user.behavior"],
    detected_data_categories: ["user.financial", "user.behavior"],
    data_subjects: ["customer"],
    legal_basis: "legitimate_interests",
    legal_basis_is_flexible: false,
    retention_period_days: 730,
    special_category_legal_basis: null,
    features: ["profiling"],
    sub_types: ["Revenue reporting", "Churn analysis"],
    updated_at: "2026-03-20T09:15:00Z",
  },
  {
    id: "web_traffic_analytics",
    name: "Web Traffic Analytics",
    key: "web_traffic_analytics",
    description:
      "Monitor website traffic, page views, referral sources, and session data to optimize site performance and content strategy.",
    data_use: "analytics",
    data_categories: ["user.behavior", "user.device", "system.operations"],
    detected_data_categories: [
      "user.behavior",
      "user.device",
      "system.operations",
      "user.location",
    ],
    data_subjects: ["customer"],
    legal_basis: "legitimate_interests",
    legal_basis_is_flexible: true,
    retention_period_days: 180,
    special_category_legal_basis: null,
    features: [],
    sub_types: ["Pageview tracking", "Referral analysis"],
    updated_at: "2026-03-22T11:00:00Z",
  },
  {
    id: "email_campaign_targeting",
    name: "Email Campaign Targeting",
    key: "email_campaign_targeting",
    description:
      "Use customer contact and preference data to send targeted marketing emails, newsletters, and promotional offers.",
    data_use: "marketing.advertising",
    data_categories: ["user.contact.email", "user.behavior"],
    detected_data_categories: ["user.contact.email", "user.behavior"],
    data_subjects: ["customer"],
    legal_basis: "consent",
    legal_basis_is_flexible: true,
    retention_period_days: 180,
    special_category_legal_basis: null,
    features: ["linking_devices"],
    sub_types: ["Email campaigns", "Segmentation"],
    updated_at: "2026-03-18T16:45:00Z",
  },
  {
    id: "ad_retargeting",
    name: "Ad Retargeting",
    key: "ad_retargeting",
    description:
      "Retarget website visitors and app users with personalized ads across third-party advertising platforms.",
    data_use: "marketing.advertising",
    data_categories: ["user.behavior", "user.device"],
    detected_data_categories: [
      "user.behavior",
      "user.device",
      "user.location",
    ],
    data_subjects: ["customer"],
    legal_basis: "consent",
    legal_basis_is_flexible: false,
    retention_period_days: 90,
    special_category_legal_basis: null,
    features: ["profiling", "linking_devices"],
    sub_types: ["Display ads", "Social retargeting"],
    updated_at: "2026-03-15T10:20:00Z",
  },
  {
    id: "customer_segmentation",
    name: "Customer Segmentation",
    key: "customer_segmentation",
    description:
      "Group customers into segments based on demographics, behavior, and purchase history for targeted marketing campaigns.",
    data_use: "marketing.advertising",
    data_categories: ["user.behavior", "user.contact", "user.financial"],
    detected_data_categories: [
      "user.behavior",
      "user.contact",
      "user.financial",
    ],
    data_subjects: ["customer"],
    legal_basis: "consent",
    legal_basis_is_flexible: true,
    retention_period_days: 365,
    special_category_legal_basis: null,
    features: ["profiling"],
    sub_types: ["Cohort building", "Lookalike audiences"],
    updated_at: "2026-03-21T08:30:00Z",
  },
  {
    id: "fraud_detection",
    name: "Fraud Detection & Prevention",
    key: "fraud_detection",
    description:
      "Process transaction, device, and behavioral data to detect, prevent, and investigate fraudulent activities in real time.",
    data_use: "essential.service.security",
    data_categories: ["user.financial", "user.behavior", "system.operations", "user.device"],
    detected_data_categories: [
      "user.financial",
      "user.behavior",
      "system.operations",
      "user.device",
    ],
    data_subjects: ["customer"],
    legal_basis: "legitimate_interests",
    legal_basis_is_flexible: false,
    retention_period_days: 730,
    special_category_legal_basis: null,
    features: ["automated_decisions", "profiling"],
    sub_types: ["Transaction monitoring", "Risk scoring", "Anomaly detection"],
    updated_at: "2026-03-25T13:00:00Z",
  },
  {
    id: "customer_support_ops",
    name: "Customer Support Operations",
    key: "customer_support_ops",
    description:
      "Collect and process customer data to provide support services, resolve issues, and manage support ticket workflows.",
    data_use: "essential.service.operations",
    data_categories: ["user.contact", "user.account"],
    detected_data_categories: [],
    data_subjects: ["customer"],
    legal_basis: "contract",
    legal_basis_is_flexible: false,
    retention_period_days: 365,
    special_category_legal_basis: null,
    features: [],
    sub_types: ["Ticket management", "Live chat"],
    updated_at: "2026-03-23T17:10:00Z",
  },
  {
    id: "hr_employee_management",
    name: "HR Employee Management",
    key: "hr_employee_management",
    description:
      "Process employee personal data for payroll, benefits administration, performance management, and regulatory compliance.",
    data_use: "essential.service.operations",
    data_categories: ["user.contact", "user.financial", "user.government_id"],
    detected_data_categories: [
      "user.contact",
      "user.financial",
      "user.government_id",
    ],
    data_subjects: ["employee"],
    legal_basis: "contract",
    legal_basis_is_flexible: false,
    retention_period_days: 2555,
    special_category_legal_basis: "employment",
    features: [],
    sub_types: ["Payroll", "Benefits", "Performance reviews"],
    updated_at: "2026-03-19T14:00:00Z",
  },
  {
    id: "feature_adoption",
    name: "Feature Adoption Tracking",
    key: "feature_adoption",
    description:
      "Track how users discover and adopt new product features to inform roadmap prioritization and onboarding improvements.",
    data_use: "improve",
    data_categories: ["user.behavior", "system.operations"],
    detected_data_categories: [
      "user.behavior",
      "system.operations",
      "user.device",
    ],
    data_subjects: ["customer"],
    legal_basis: "legitimate_interests",
    legal_basis_is_flexible: true,
    retention_period_days: 365,
    special_category_legal_basis: null,
    features: ["profiling"],
    sub_types: ["Feature usage", "Onboarding flows"],
    updated_at: "2026-03-24T09:45:00Z",
  },
  {
    id: "ab_testing",
    name: "A/B Testing & Experimentation",
    key: "ab_testing",
    description:
      "Run controlled experiments on UI variants, pricing models, and feature configurations to optimize user experience.",
    data_use: "improve",
    data_categories: ["user.behavior"],
    detected_data_categories: [],
    data_subjects: ["customer"],
    legal_basis: "legitimate_interests",
    legal_basis_is_flexible: true,
    retention_period_days: 180,
    special_category_legal_basis: null,
    features: [],
    sub_types: ["UI experiments", "Pricing tests"],
    updated_at: "2026-03-17T12:30:00Z",
  },
  {
    id: "error_monitoring",
    name: "Error Monitoring",
    key: "error_monitoring",
    description:
      "Capture application errors, stack traces, and performance metrics to identify and resolve bugs that impact user experience.",
    data_use: "improve",
    data_categories: ["system.operations", "user.device"],
    detected_data_categories: ["system.operations", "user.device"],
    data_subjects: ["customer"],
    legal_basis: "legitimate_interests",
    legal_basis_is_flexible: false,
    retention_period_days: 90,
    special_category_legal_basis: null,
    features: [],
    sub_types: ["Error tracking", "Performance monitoring"],
    updated_at: "2026-03-26T08:00:00Z",
  },
];

export const MOCK_SYSTEM_ASSIGNMENTS: Record<
  string,
  PurposeSystemAssignment[]
> = {
  customer_analytics: [
    { system_id: "bigquery", system_name: "BigQuery", system_type: "Data warehouse", assigned: true, consumer_category: "system" },
    { system_id: "snowflake", system_name: "Snowflake", system_type: "Data warehouse", assigned: true, consumer_category: "system" },
    { system_id: "amplitude", system_name: "Amplitude", system_type: "Analytics", assigned: true, consumer_category: "system" },
    { system_id: "segment", system_name: "Segment", system_type: "CDP", assigned: true, consumer_category: "system" },
    { system_id: "mixpanel", system_name: "Mixpanel", system_type: "Analytics", assigned: true, consumer_category: "system" },
    { system_id: "marketing_analytics_group", system_name: "Marketing analytics team", system_type: "Google group", assigned: true, consumer_category: "group" },
    { system_id: "data_science_group", system_name: "Data science team", system_type: "Google group", assigned: true, consumer_category: "group" },
    { system_id: "heap", system_name: "Heap", system_type: "Analytics", assigned: true, consumer_category: "system" },
    { system_id: "looker", system_name: "Looker", system_type: "BI", assigned: true, consumer_category: "system" },
    { system_id: "tableau", system_name: "Tableau", system_type: "BI", assigned: true, consumer_category: "system" },
    { system_id: "redshift", system_name: "Redshift", system_type: "Data warehouse", assigned: true, consumer_category: "system" },
    { system_id: "databricks", system_name: "Databricks", system_type: "Data platform", assigned: true, consumer_category: "system" },
    { system_id: "fullstory", system_name: "FullStory", system_type: "Session replay", assigned: true, consumer_category: "system" },
    { system_id: "hotjar", system_name: "Hotjar", system_type: "Heatmaps", assigned: true, consumer_category: "system" },
    { system_id: "google_analytics", system_name: "Google Analytics", system_type: "Analytics", assigned: true, consumer_category: "system" },
    { system_id: "fivetran", system_name: "Fivetran", system_type: "ETL", assigned: true, consumer_category: "system" },
    { system_id: "product_analytics_group", system_name: "Product analytics group", system_type: "Google group", assigned: true, consumer_category: "group" },
    { system_id: "growth_experimentation_group", system_name: "Growth experimentation team", system_type: "Google group", assigned: true, consumer_category: "group" },
    { system_id: "postgres_analytics", system_name: "PostgreSQL (analytics)", system_type: "Database", assigned: true, consumer_category: "system" },
    { system_id: "dbt", system_name: "dbt", system_type: "Data transformation", assigned: true, consumer_category: "system" },
    { system_id: "kafka", system_name: "Kafka", system_type: "Streaming", assigned: true, consumer_category: "system" },
    { system_id: "airflow", system_name: "Airflow", system_type: "Orchestration", assigned: true, consumer_category: "system" },
    { system_id: "executive_reporting_group", system_name: "Executive reporting", system_type: "Google group", assigned: true, consumer_category: "group" },
  ],
  email_campaign_targeting: [
    {
      system_id: "hubspot",
      system_name: "HubSpot",
      system_type: "CRM",
      assigned: true,
    },
    {
      system_id: "mailchimp",
      system_name: "Mailchimp",
      system_type: "Email marketing",
      assigned: true,
    },
    {
      system_id: "google_ads",
      system_name: "Google Ads",
      system_type: "Advertising",
      assigned: false,
    },
  ],
  fraud_detection: [
    {
      system_id: "stripe",
      system_name: "Stripe",
      system_type: "Payment processor",
      assigned: true,
    },
    {
      system_id: "sift",
      system_name: "Sift",
      system_type: "Fraud detection",
      assigned: true,
    },
    {
      system_id: "postgres_prod",
      system_name: "PostgreSQL (prod)",
      system_type: "Database",
      assigned: true,
    },
  ],
  hr_employee_management: [
    {
      system_id: "workday",
      system_name: "Workday",
      system_type: "HRIS",
      assigned: true,
    },
    {
      system_id: "adp",
      system_name: "ADP",
      system_type: "Payroll",
      assigned: true,
    },
  ],
  feature_adoption: [
    {
      system_id: "bigquery",
      system_name: "BigQuery",
      system_type: "Data warehouse",
      assigned: true,
    },
    {
      system_id: "amplitude",
      system_name: "Amplitude",
      system_type: "Analytics",
      assigned: true,
    },
    {
      system_id: "sentry",
      system_name: "Sentry",
      system_type: "Error tracking",
      assigned: true,
    },
    {
      system_id: "segment",
      system_name: "Segment",
      system_type: "CDP",
      assigned: true,
    },
  ],
  customer_support_ops: [
    {
      system_id: "zendesk",
      system_name: "Zendesk",
      system_type: "Support platform",
      assigned: true,
    },
    {
      system_id: "intercom",
      system_name: "Intercom",
      system_type: "Messaging",
      assigned: true,
    },
    {
      system_id: "salesforce",
      system_name: "Salesforce",
      system_type: "CRM",
      assigned: false,
    },
  ],
};

export const MOCK_COVERAGE: Record<string, PurposeCoverage> = {
  customer_analytics: {
    systems: { assigned: 8, total: 10 },
    datasets: { assigned: 12, total: 24 },
    tables: { assigned: 45, total: 112 },
    fields: { assigned: 210, total: 890 },
  },
  email_campaign_targeting: {
    systems: { assigned: 5, total: 6 },
    datasets: { assigned: 3, total: 5 },
    tables: { assigned: 12, total: 20 },
    fields: { assigned: 85, total: 150 },
  },
  fraud_detection: {
    systems: { assigned: 3, total: 3 },
    datasets: { assigned: 7, total: 8 },
    tables: { assigned: 30, total: 35 },
    fields: { assigned: 320, total: 400 },
  },
  hr_employee_management: {
    systems: { assigned: 2, total: 2 },
    datasets: { assigned: 1, total: 3 },
    tables: { assigned: 5, total: 15 },
    fields: { assigned: 30, total: 120 },
  },
  feature_adoption: {
    systems: { assigned: 4, total: 5 },
    datasets: { assigned: 9, total: 12 },
    tables: { assigned: 50, total: 65 },
    fields: { assigned: 410, total: 520 },
  },
  customer_support_ops: {
    systems: { assigned: 6, total: 8 },
    datasets: { assigned: 2, total: 4 },
    tables: { assigned: 10, total: 18 },
    fields: { assigned: 55, total: 140 },
  },
};

export const MOCK_DATASET_ASSIGNMENTS: Record<
  string,
  PurposeDatasetAssignment[]
> = {
  customer_analytics: [
    { dataset_fides_key: "bigquery_sessions", dataset_name: "BigQuery Sessions", system_name: "BigQuery", collection_count: 3, data_categories: ["user.behavior", "system.operations"], updated_at: "2026-03-28T09:05:00Z", steward: "Marcus Taylor" },
    { dataset_fides_key: "bigquery_events", dataset_name: "BigQuery Events", system_name: "BigQuery", collection_count: 12, data_categories: ["user.behavior", "system.operations"], updated_at: "2026-04-02T10:14:00Z", steward: "Sarah Chen" },
    { dataset_fides_key: "bigquery_users", dataset_name: "BigQuery Users", system_name: "BigQuery", collection_count: 5, data_categories: ["user.behavior", "user.contact.email"], updated_at: "2026-04-05T16:30:00Z", steward: "Sarah Chen" },
    { dataset_fides_key: "bigquery_pageviews", dataset_name: "BigQuery Pageviews", system_name: "BigQuery", collection_count: 2, data_categories: ["user.behavior", "user.device"], updated_at: "2026-04-10T12:40:00Z", steward: "Marcus Taylor" },
    { dataset_fides_key: "snowflake_analytics", dataset_name: "Snowflake Analytics", system_name: "Snowflake", collection_count: 15, data_categories: ["user.behavior", "system.operations"], updated_at: "2026-04-01T08:22:00Z", steward: "Priya Desai" },
    { dataset_fides_key: "snowflake_raw_events", dataset_name: "Snowflake Raw Events", system_name: "Snowflake", collection_count: 9, data_categories: ["user.behavior", "system.operations"], updated_at: "2026-04-07T14:11:00Z", steward: "Priya Desai" },
  ],
  email_campaign_targeting: [
    { dataset_fides_key: "hubspot_contacts", dataset_name: "HubSpot Contacts", system_name: "HubSpot", collection_count: 6, data_categories: ["user.contact.email", "user.behavior"], updated_at: "2026-03-30T09:00:00Z", steward: "Jordan Lee" },
    { dataset_fides_key: "hubspot_deals", dataset_name: "HubSpot Deals", system_name: "HubSpot", collection_count: 4, data_categories: ["user.behavior"], updated_at: "2026-03-28T11:30:00Z", steward: "Jordan Lee" },
    { dataset_fides_key: "mailchimp_lists", dataset_name: "Mailchimp Lists", system_name: "Mailchimp", collection_count: 3, data_categories: ["user.contact.email"], updated_at: "2026-03-25T14:00:00Z", steward: "Emma Rivera" },
    { dataset_fides_key: "mailchimp_campaigns", dataset_name: "Mailchimp Campaigns", system_name: "Mailchimp", collection_count: 5, data_categories: ["user.contact.email", "user.behavior"], updated_at: "2026-03-29T17:00:00Z", steward: "Emma Rivera" },
    { dataset_fides_key: "google_ads_campaigns", dataset_name: "Google Ads Campaigns", system_name: "Google Ads", collection_count: 7, data_categories: ["user.behavior"], updated_at: "2026-03-27T10:45:00Z", steward: "Alex Park" },
    { dataset_fides_key: "google_ads_audiences", dataset_name: "Google Ads Audiences", system_name: "Google Ads", collection_count: 3, data_categories: ["user.behavior"], updated_at: "2026-03-26T08:00:00Z", steward: "Alex Park" },
    { dataset_fides_key: "salesforce_leads", dataset_name: "Salesforce Leads", system_name: "Salesforce", collection_count: 8, data_categories: ["user.contact.email", "user.behavior"], updated_at: "2026-04-01T13:20:00Z", steward: "Jordan Lee" },
    { dataset_fides_key: "salesforce_accounts", dataset_name: "Salesforce Accounts", system_name: "Salesforce", collection_count: 6, data_categories: ["user.contact.email"], updated_at: "2026-04-02T09:50:00Z", steward: "Jordan Lee" },
  ],
  fraud_detection: [
    { dataset_fides_key: "stripe_transactions", dataset_name: "Stripe Transactions", system_name: "Stripe", collection_count: 9, data_categories: ["user.financial", "user.device"], updated_at: "2026-03-30T10:00:00Z", steward: "Dana Ahmed" },
    { dataset_fides_key: "stripe_customers", dataset_name: "Stripe Customers", system_name: "Stripe", collection_count: 5, data_categories: ["user.financial", "user.behavior"], updated_at: "2026-03-29T11:00:00Z", steward: "Dana Ahmed" },
    { dataset_fides_key: "stripe_disputes", dataset_name: "Stripe Disputes", system_name: "Stripe", collection_count: 3, data_categories: ["user.financial"], updated_at: "2026-03-27T15:00:00Z", steward: "Dana Ahmed" },
    { dataset_fides_key: "sift_events", dataset_name: "Sift Events", system_name: "Sift", collection_count: 4, data_categories: ["user.behavior", "user.device"], updated_at: "2026-04-01T09:00:00Z", steward: "Noah Kim" },
    { dataset_fides_key: "sift_scores", dataset_name: "Sift Risk Scores", system_name: "Sift", collection_count: 2, data_categories: ["system.operations", "user.behavior"], updated_at: "2026-04-02T14:30:00Z", steward: "Noah Kim" },
    { dataset_fides_key: "postgres_fraud_logs", dataset_name: "Fraud Logs", system_name: "PostgreSQL (prod)", collection_count: 7, data_categories: ["system.operations", "user.behavior", "user.device"], updated_at: "2026-04-03T12:00:00Z", steward: "Riya Gupta" },
    { dataset_fides_key: "postgres_users", dataset_name: "Users DB", system_name: "PostgreSQL (prod)", collection_count: 12, data_categories: ["user.financial", "user.behavior"], updated_at: "2026-04-04T10:30:00Z", steward: "Riya Gupta" },
    { dataset_fides_key: "postgres_audit", dataset_name: "Audit Trail", system_name: "PostgreSQL (prod)", collection_count: 4, data_categories: ["system.operations"], updated_at: "2026-03-28T16:00:00Z", steward: "Riya Gupta" },
  ],
  hr_employee_management: [
    { dataset_fides_key: "workday_employees", dataset_name: "Workday Employees", system_name: "Workday", collection_count: 10, data_categories: ["user.contact", "user.government_id"], updated_at: "2026-03-25T09:00:00Z", steward: "Lena Brooks" },
    { dataset_fides_key: "workday_benefits", dataset_name: "Workday Benefits", system_name: "Workday", collection_count: 6, data_categories: ["user.contact", "user.financial"], updated_at: "2026-03-26T10:00:00Z", steward: "Lena Brooks" },
    { dataset_fides_key: "workday_reviews", dataset_name: "Workday Reviews", system_name: "Workday", collection_count: 3, data_categories: ["user.contact"], updated_at: "2026-03-27T11:00:00Z", steward: "Lena Brooks" },
    { dataset_fides_key: "adp_payroll", dataset_name: "ADP Payroll", system_name: "ADP", collection_count: 8, data_categories: ["user.contact", "user.financial", "user.government_id"], updated_at: "2026-03-28T12:00:00Z", steward: "Miguel Hart" },
    { dataset_fides_key: "adp_tax", dataset_name: "ADP Tax Records", system_name: "ADP", collection_count: 4, data_categories: ["user.financial", "user.government_id"], updated_at: "2026-03-29T13:00:00Z", steward: "Miguel Hart" },
  ],
  feature_adoption: [
    { dataset_fides_key: "bigquery_product", dataset_name: "BigQuery Product Data", system_name: "BigQuery", collection_count: 14, data_categories: ["user.behavior", "system.operations"], updated_at: "2026-04-01T09:00:00Z", steward: "Sarah Chen" },
    { dataset_fides_key: "amplitude_product", dataset_name: "Amplitude Product", system_name: "Amplitude", collection_count: 6, data_categories: ["user.behavior", "user.device"], updated_at: "2026-04-02T10:00:00Z", steward: "Marcus Taylor" },
    { dataset_fides_key: "amplitude_experiments", dataset_name: "Amplitude Experiments", system_name: "Amplitude", collection_count: 3, data_categories: ["user.behavior"], updated_at: "2026-04-03T11:00:00Z", steward: "Marcus Taylor" },
    { dataset_fides_key: "sentry_errors", dataset_name: "Sentry Errors", system_name: "Sentry", collection_count: 3, data_categories: ["system.operations", "user.device"], updated_at: "2026-04-04T12:00:00Z", steward: "Ben Morales" },
    { dataset_fides_key: "sentry_performance", dataset_name: "Sentry Performance", system_name: "Sentry", collection_count: 5, data_categories: ["system.operations"], updated_at: "2026-04-05T13:00:00Z", steward: "Ben Morales" },
    { dataset_fides_key: "segment_events", dataset_name: "Segment Events", system_name: "Segment", collection_count: 11, data_categories: ["user.behavior"], updated_at: "2026-04-06T14:00:00Z", steward: "Priya Desai" },
    { dataset_fides_key: "segment_profiles", dataset_name: "Segment Profiles", system_name: "Segment", collection_count: 6, data_categories: ["user.behavior"], updated_at: "2026-04-07T15:00:00Z", steward: "Priya Desai" },
    { dataset_fides_key: "fullstory_sessions", dataset_name: "FullStory Sessions", system_name: "FullStory", collection_count: 4, data_categories: ["user.behavior", "user.device"], updated_at: "2026-04-08T16:00:00Z", steward: "Marcus Taylor" },
  ],
  customer_support_ops: [
    { dataset_fides_key: "zendesk_tickets", dataset_name: "Zendesk Tickets", system_name: "Zendesk", collection_count: 5, data_categories: [], updated_at: "2026-03-20T09:00:00Z", steward: "Ava Sullivan" },
    { dataset_fides_key: "zendesk_users", dataset_name: "Zendesk Users", system_name: "Zendesk", collection_count: 3, data_categories: [], updated_at: "2026-03-21T10:00:00Z", steward: "Ava Sullivan" },
    { dataset_fides_key: "zendesk_articles", dataset_name: "Zendesk Knowledge Base", system_name: "Zendesk", collection_count: 2, data_categories: [], updated_at: "2026-03-22T11:00:00Z", steward: "Ava Sullivan" },
    { dataset_fides_key: "intercom_conversations", dataset_name: "Intercom Conversations", system_name: "Intercom", collection_count: 4, data_categories: [], updated_at: "2026-03-23T12:00:00Z", steward: "Owen Fischer" },
    { dataset_fides_key: "intercom_contacts", dataset_name: "Intercom Contacts", system_name: "Intercom", collection_count: 6, data_categories: [], updated_at: "2026-03-24T13:00:00Z", steward: "Owen Fischer" },
    { dataset_fides_key: "salesforce_cases", dataset_name: "Salesforce Cases", system_name: "Salesforce", collection_count: 7, data_categories: [], updated_at: "2026-03-25T14:00:00Z", steward: "Jordan Lee" },
  ],
};

export const MOCK_AVAILABLE_DATASETS: AvailableDataset[] = [
  { dataset_fides_key: "bigquery_events", dataset_name: "BigQuery Events", system_name: "BigQuery" },
  { dataset_fides_key: "bigquery_users", dataset_name: "BigQuery Users", system_name: "BigQuery" },
  { dataset_fides_key: "bigquery_product", dataset_name: "BigQuery Product Data", system_name: "BigQuery" },
  { dataset_fides_key: "snowflake_analytics", dataset_name: "Snowflake Analytics", system_name: "Snowflake" },
  { dataset_fides_key: "snowflake_marketing", dataset_name: "Snowflake Marketing", system_name: "Snowflake" },
  { dataset_fides_key: "amplitude_events", dataset_name: "Amplitude Events", system_name: "Amplitude" },
  { dataset_fides_key: "amplitude_product", dataset_name: "Amplitude Product", system_name: "Amplitude" },
  { dataset_fides_key: "hubspot_contacts", dataset_name: "HubSpot Contacts", system_name: "HubSpot" },
  { dataset_fides_key: "hubspot_deals", dataset_name: "HubSpot Deals", system_name: "HubSpot" },
  { dataset_fides_key: "mailchimp_lists", dataset_name: "Mailchimp Lists", system_name: "Mailchimp" },
  { dataset_fides_key: "stripe_transactions", dataset_name: "Stripe Transactions", system_name: "Stripe" },
  { dataset_fides_key: "stripe_customers", dataset_name: "Stripe Customers", system_name: "Stripe" },
  { dataset_fides_key: "sift_events", dataset_name: "Sift Events", system_name: "Sift" },
  { dataset_fides_key: "postgres_fraud_logs", dataset_name: "Fraud Logs", system_name: "PostgreSQL (prod)" },
  { dataset_fides_key: "postgres_users", dataset_name: "Users DB", system_name: "PostgreSQL (prod)" },
  { dataset_fides_key: "workday_employees", dataset_name: "Workday Employees", system_name: "Workday" },
  { dataset_fides_key: "adp_payroll", dataset_name: "ADP Payroll", system_name: "ADP" },
  { dataset_fides_key: "sentry_errors", dataset_name: "Sentry Errors", system_name: "Sentry" },
  { dataset_fides_key: "segment_events", dataset_name: "Segment Events", system_name: "Segment" },
  { dataset_fides_key: "zendesk_tickets", dataset_name: "Zendesk Tickets", system_name: "Zendesk" },
  { dataset_fides_key: "intercom_conversations", dataset_name: "Intercom Conversations", system_name: "Intercom" },
  { dataset_fides_key: "salesforce_accounts", dataset_name: "Salesforce Accounts", system_name: "Salesforce" },
  { dataset_fides_key: "redshift_analytics", dataset_name: "Redshift Analytics", system_name: "Redshift" },
  { dataset_fides_key: "databricks_ml", dataset_name: "Databricks ML Features", system_name: "Databricks" },
];

export const MOCK_AVAILABLE_SYSTEMS: AvailableSystem[] = [
  { system_id: "bigquery", system_name: "BigQuery", system_type: "Data warehouse" },
  { system_id: "snowflake", system_name: "Snowflake", system_type: "Data warehouse" },
  { system_id: "redshift", system_name: "Redshift", system_type: "Data warehouse" },
  { system_id: "amplitude", system_name: "Amplitude", system_type: "Analytics" },
  { system_id: "mixpanel", system_name: "Mixpanel", system_type: "Analytics" },
  { system_id: "heap", system_name: "Heap", system_type: "Analytics" },
  { system_id: "google_analytics", system_name: "Google Analytics", system_type: "Analytics" },
  { system_id: "segment", system_name: "Segment", system_type: "CDP" },
  { system_id: "databricks", system_name: "Databricks", system_type: "Data platform" },
  { system_id: "looker", system_name: "Looker", system_type: "BI" },
  { system_id: "tableau", system_name: "Tableau", system_type: "BI" },
  { system_id: "fivetran", system_name: "Fivetran", system_type: "ETL" },
  { system_id: "dbt", system_name: "dbt", system_type: "Data transformation" },
  { system_id: "fullstory", system_name: "FullStory", system_type: "Session replay" },
  { system_id: "hotjar", system_name: "Hotjar", system_type: "Heatmaps" },
  { system_id: "kafka", system_name: "Kafka", system_type: "Streaming" },
  { system_id: "airflow", system_name: "Airflow", system_type: "Orchestration" },
  { system_id: "postgres_prod", system_name: "PostgreSQL (prod)", system_type: "Database" },
  { system_id: "postgres_analytics", system_name: "PostgreSQL (analytics)", system_type: "Database" },
  { system_id: "hubspot", system_name: "HubSpot", system_type: "CRM" },
  { system_id: "salesforce", system_name: "Salesforce", system_type: "CRM" },
  { system_id: "mailchimp", system_name: "Mailchimp", system_type: "Email marketing" },
  { system_id: "google_ads", system_name: "Google Ads", system_type: "Advertising" },
  { system_id: "stripe", system_name: "Stripe", system_type: "Payment processor" },
  { system_id: "sift", system_name: "Sift", system_type: "Fraud detection" },
  { system_id: "workday", system_name: "Workday", system_type: "HRIS" },
  { system_id: "adp", system_name: "ADP", system_type: "Payroll" },
  { system_id: "sentry", system_name: "Sentry", system_type: "Error tracking" },
  { system_id: "zendesk", system_name: "Zendesk", system_type: "Support platform" },
  { system_id: "intercom", system_name: "Intercom", system_type: "Messaging" },
];
