export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

const Layout = async ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
};
export default Layout;
