import type { paths } from "@ethyca/fides-api-ts"; // generated by openapi-typescript
import createClient from "openapi-fetch";
import {
  createImmutableHook,
  createInfiniteHook,
  createMutateHook,
  createQueryHook,
} from "swr-openapi";

import store from "~/app/store";
import { addCommonHeaders } from "~/common/CommonHeaders";

// Get auth headers from redux
const getHeaders = () => {
  const headers = new Headers();
  addCommonHeaders(headers);
  return headers;
};

const client = createClient<paths>({
  baseUrl: store
    .getState()
    .settings.settings?.FIDES_API_URL?.replace("/api/v1", ""), // Should think about migrating config to not include prefix
  headers: getHeaders(),
});
const prefix = "";

export const useQuery = createQueryHook(client, prefix);
export const useImmutable = createImmutableHook(client, prefix);
export const useInfinite = createInfiniteHook(client, prefix);
export const useMutate = createMutateHook(
  client,
  prefix,
  (a, b) => a === b, // Or any comparision function
);
