"""add openidprovider

Revision ID: 10a430e97f00
Revises: fc82ab64bd5e
Create Date: 2024-07-31 15:15:09.350062

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "10a430e97f00"
down_revision = "fc82ab64bd5e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "openid_provider",
        sa.Column("id", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("provider", sa.Enum("google", name="providerenum"), nullable=True),
        sa.Column(
            "client_id",
            sqlalchemy_utils.types.encrypted.encrypted_type.StringEncryptedType(),
            nullable=False,
        ),
        sa.Column(
            "client_secret",
            sqlalchemy_utils.types.encrypted.encrypted_type.StringEncryptedType(),
            nullable=False,
        ),
        sa.Column("disabled", sa.Boolean(), server_default="f", nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_openid_provider_id"), "openid_provider", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_openid_provider_provider"),
        "openid_provider",
        ["provider"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_openid_provider_provider"), table_name="openid_provider")
    op.drop_index(op.f("ix_openid_provider_id"), table_name="openid_provider")
    op.drop_table("openid_provider")
    # ### end Alembic commands ###
