"""adds auto_subdomain_cookie_deletion on experience config, migrate to write initial val of false

Revision ID: 36ad82edb38e
Revises: fa476b733915
Create Date: 2024-10-07 19:30:03.559747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36ad82edb38e'
down_revision = 'fa476b733915'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experienceconfigtemplate', sa.Column('auto_subdomain_cookie_deletion', sa.Boolean(), server_default='t', nullable=False))
    op.add_column('privacyexperienceconfig', sa.Column('auto_subdomain_cookie_deletion', sa.Boolean(), server_default='t', nullable=False))

    # Updates all existing privacy experience configs to be False. Moving forward this will be set to True by default.
    op.execute("UPDATE privacyexperienceconfig SET auto_subdomain_cookie_deletion = FALSE")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('privacyexperienceconfig', 'auto_subdomain_cookie_deletion')
    op.drop_column('experienceconfigtemplate', 'auto_subdomain_cookie_deletion')
    # ### end Alembic commands ###
