"""
Creates staged resource ancestor link table.

Does not populate the table with data, that is handled in a separate data migration.

Also does not drop the StagedResource.child_diff_statuses column,
that is handled in a separate migration, _after_ the data migration
that populates the staged resource ancestor link table, to prevent
unintended data loss.

Revision ID: 5474a47c77da
Revises: 2263583b0e44
Create Date: 2025-05-27 19:02:43.802783

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "5474a47c77da"
down_revision = "2263583b0e44"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stagedresourceancestor",
        sa.Column("id", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("ancestor_urn", sa.String(), nullable=False),
        sa.Column("descendant_urn", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["ancestor_urn"], ["stagedresource.urn"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["descendant_urn"], ["stagedresource.urn"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", "ancestor_urn", "descendant_urn"),
        sa.UniqueConstraint(
            "ancestor_urn", "descendant_urn", name="uq_staged_resource_parent_link"
        ),
    )
    op.create_index(
        "ix_staged_resource_ancestor_ancestor",
        "stagedresourceancestor",
        ["ancestor_urn"],
        unique=False,
    )
    op.create_index(
        "ix_staged_resource_ancestor_descendant",
        "stagedresourceancestor",
        ["descendant_urn"],
        unique=False,
    )

    # add an index for StagedResource.diff_status to improve queries against the diff_status field
    op.create_index(
        op.f("ix_stagedresource_diff_status"),
        "stagedresource",
        ["diff_status"],
        unique=False,
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # drop the StagedResource.diff_status index created in the migration
    op.drop_index(op.f("ix_stagedresource_diff_status"), table_name="stagedresource")

    # drop the StagedResourceAncestor table and its indexes

    op.drop_index(
        "ix_staged_resource_ancestor_descendant",
        table_name="stagedresourceancestor",
    )
    op.drop_index(
        "ix_staged_resource_ancestor_ancestor", table_name="stagedresourceancestor"
    )
    op.drop_table("stagedresourceancestor")
    # ### end Alembic commands ###
