"""remove data_qualifier

Revision ID: 548a1ac26771
Revises: 848a8f4125cf
Create Date: 2023-12-08 22:07:38.617038

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "548a1ac26771"
down_revision = "848a8f4125cf"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_ctl_data_qualifiers_fides_key", table_name="ctl_data_qualifiers")
    op.drop_index("ix_ctl_data_qualifiers_id", table_name="ctl_data_qualifiers")
    op.drop_table("ctl_data_qualifiers")
    op.drop_column("ctl_datasets", "data_qualifier")
    op.drop_index("ix_ctl_systems_name", table_name="ctl_systems")
    op.drop_column("privacydeclaration", "data_qualifier")
    op.drop_constraint("purpose_constraint", "tcf_purpose_overrides", type_="unique")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "purpose_constraint", "tcf_purpose_overrides", ["purpose"]
    )
    op.add_column(
        "privacydeclaration",
        sa.Column("data_qualifier", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.create_index("ix_ctl_systems_name", "ctl_systems", ["name"], unique=False)
    op.add_column(
        "ctl_datasets",
        sa.Column("data_qualifier", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.create_table(
        "ctl_data_qualifiers",
        sa.Column("id", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column("fides_key", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "organization_fides_key", sa.TEXT(), autoincrement=False, nullable=True
        ),
        sa.Column("name", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("description", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("parent_key", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "tags", postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True
        ),
        sa.Column("is_default", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column(
            "active",
            sa.BOOLEAN(),
            server_default=sa.text("true"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("version_added", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("version_deprecated", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("replaced_by", sa.TEXT(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name="ctl_data_qualifiers_pkey"),
    )
    op.create_index(
        "ix_ctl_data_qualifiers_id", "ctl_data_qualifiers", ["id"], unique=False
    )
    op.create_index(
        "ix_ctl_data_qualifiers_fides_key",
        "ctl_data_qualifiers",
        ["fides_key"],
        unique=False,
    )
    # ### end Alembic commands ###
