"""test_migration

Revision ID: 77c4a1e836d3
Revises: c1885270b3cc
Create Date: 2023-06-20 20:53:19.404182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77c4a1e836d3'
down_revision = 'c1885270b3cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
