"""add email_address column to fides user

Revision ID: a3abcf694cf3
Revises: 4ced99dabebb
Create Date: 2023-12-20 22:27:43.918074

"""
from alembic import op
from citext import CIText
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3abcf694cf3'
down_revision = '4ced99dabebb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fidesuser', sa.Column('email_address', CIText(), nullable=True))
    op.create_unique_constraint(None, 'fidesuser', ['email_address'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fidesuser', type_='unique')
    op.drop_column('fidesuser', 'email_address')
    # ### end Alembic commands ###
