"""add finalized fields to privacy request

Revision ID: a7065df4dcf1
Revises: 41a634d8c669
Create Date: 2025-07-01 14:07:36.779437

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a7065df4dcf1"
down_revision = "41a634d8c669"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "privacyrequest",
        sa.Column("finalized_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "privacyrequest", sa.Column("finalized_by", sa.String(), nullable=True)
    )
    op.create_foreign_key(
        None,
        "privacyrequest",
        "fidesuser",
        ["finalized_by"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "privacyrequest", type_="foreignkey")
    op.drop_column("privacyrequest", "finalized_by")
    op.drop_column("privacyrequest", "finalized_at")
    # ### end Alembic commands ###
