"""add system vendor_deleted_date field

Revision ID: d873e3e430b0
Revises: d49a767eb49d
Create Date: 2024-04-22 14:25:13.232408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd873e3e430b0'
down_revision = 'd49a767eb49d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ctl_systems', sa.Column('vendor_deleted_date', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ctl_systems', 'vendor_deleted_date')
    # ### end Alembic commands ###
