"""Add group_id to MonitorTask

Revision ID: 9f21507db078
Revises: 5f9821b4baf1
Create Date: 2026-05-04 21:18:44.962348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f21507db078'
down_revision = '5f9821b4baf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monitortask', sa.Column('group_id', sa.String(255), nullable=True))
    op.create_index(op.f('ix_monitortask_group_id'), 'monitortask', ['group_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_monitortask_group_id'), table_name='monitortask')
    op.drop_column('monitortask', 'group_id')
    # ### end Alembic commands ###
