"""empty message

Revision ID: df04cce4331f
Revises: c1d2e3f4a5b6
Create Date: 2026-02-04 13:12:39.121204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df04cce4331f'
down_revision = 'c1d2e3f4a5b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('custom_connector_template', 'replaceable')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('custom_connector_template', sa.Column('replaceable', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
