"""Add encryption_keys table

Revision ID: ecd49f8108e0
Revises: ea20059aee77
Create Date: 2026-03-16 15:19:43.610375

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ecd49f8108e0"
down_revision = "ea20059aee77"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "encryption_keys",
        sa.Column("id", sa.String(length=255), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("wrapped_dek", sa.Text(), nullable=False),
        sa.Column("kek_id_hash", sa.String(), nullable=False),
        sa.Column("provider", sa.String(), server_default="local", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_encryption_keys_id"), "encryption_keys", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_encryption_keys_id"), table_name="encryption_keys")
    op.drop_table("encryption_keys")
    # ### end Alembic commands ###
