"""add property_ids to datasetconfig and manual_task_config

Revision ID: c0dc13ad2a05
Revises: e5f6g7h8i9j0
Create Date: 2026-02-11 18:40:41.477080

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c0dc13ad2a05'
down_revision = 'e5f6g7h8i9j0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datasetconfig', sa.Column('property_ids', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False))
    op.create_index('ix_datasetconfig_property_ids_gin', 'datasetconfig', ['property_ids'], unique=False, postgresql_using='gin')
    op.add_column('manual_task_config', sa.Column('property_ids', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('manual_task_config', 'property_ids')
    op.drop_index('ix_datasetconfig_property_ids_gin', table_name='datasetconfig', postgresql_using='gin')
    op.drop_column('datasetconfig', 'property_ids')
    # ### end Alembic commands ###
