"""add received_at to currentprivacypreferencev2

Revision ID: d98cea042828
Revises: baa6792fc3f7
Create Date: 2026-03-18 18:00:11.051667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd98cea042828'
down_revision = 'baa6792fc3f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('currentprivacypreferencev2', sa.Column('received_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('currentprivacypreferencev2', 'received_at')
    # ### end Alembic commands ###
