"""add policy conditions

Revision ID: 6d5f70dd0ba5
Revises: 71f3ded6045a
Create Date: 2025-12-09 12:36:02.092314

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "6d5f70dd0ba5"
down_revision = "71f3ded6045a"
branch_labels = None
depends_on = None


def upgrade():
    op.create_table(
        "policy_condition",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "condition_type",
            sa.String(),  # Use String instead of Enum to avoid auto-creation
            nullable=False,
        ),
        sa.Column("field_address", sa.String(length=255), nullable=True),
        sa.Column("operator", sa.String(), nullable=True),
        sa.Column("value", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("logical_operator", sa.String(), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("id", sa.String(length=255), nullable=False),
        sa.Column("policy_id", sa.String(), nullable=False),
        sa.Column("parent_id", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["parent_id"], ["policy_condition.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["policy_id"], ["policy.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_policy_condition_condition_type"),
        "policy_condition",
        ["condition_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_policy_condition_parent_id"),
        "policy_condition",
        ["parent_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_policy_condition_policy_id"),
        "policy_condition",
        ["policy_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_policy_condition_sort_order"),
        "policy_condition",
        ["sort_order"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_policy_condition_sort_order"), table_name="policy_condition")
    op.drop_index(op.f("ix_policy_condition_policy_id"), table_name="policy_condition")
    op.drop_index(op.f("ix_policy_condition_parent_id"), table_name="policy_condition")
    op.drop_index(
        op.f("ix_policy_condition_condition_type"), table_name="policy_condition"
    )
    op.drop_table("policy_condition")
    # ### end Alembic commands ###
