"""add distance to stagedresourceancestor

Revision ID: 4aa72476c38b
Revises: a7241db3ee6a
Create Date: 2025-12-18 14:46:06.859018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4aa72476c38b'
down_revision = 'a7241db3ee6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stagedresourceancestor', sa.Column('distance', sa.Integer(), nullable=False, server_default='0'))
    op.create_index('ix_staged_resource_ancestor_ancestor_distance', 'stagedresourceancestor', ['ancestor_urn', 'distance'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_staged_resource_ancestor_ancestor_distance', table_name='stagedresourceancestor')
    op.drop_column('stagedresourceancestor', 'distance')
    # ### end Alembic commands ###
