"""Add system_resource_id to System

Revision ID: ae7f36ef0daf
Revises: 1739aa4a4ab7
Create Date: 2022-02-10 13:07:50.219995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ae7f36ef0daf"
down_revision = "1739aa4a4ab7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "systems", sa.Column("system_resource_id", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("systems", "system_resource_id")
    # ### end Alembic commands ###
