services:
  mssql_example:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 1433:1433
    environment:
      - MSSQL_SA_PASSWORD=Mssql_pw1
      - ACCEPT_EULA=Y
      - MSSQL_PID=Developer
