services:
  mongodb_example:
    image: mongo:5.0.3
    environment:
      - MONGO_INITDB_DATABASE=mongo_test
      - MONGO_INITDB_ROOT_USERNAME=mongo_user
      - MONGO_INITDB_ROOT_PASSWORD=mongo_pass
    expose:
      - 27017
    ports:
      - "27017:27017"
    # Because we're using the "-f" flag from a parent directory, this relative path needs
    # to be from the parent directory as well
    volumes:
      - ./docker/sample_data/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
