services:
  mssql_example:
    image: mcr.microsoft.com/azure-sql-edge:1.0.7 # Equivalent to SQL Server 2019
    ports:
      - 1433:1433
    environment:
      - SA_PASSWORD=Mssql_pw1
      - ACCEPT_EULA="Y"
