"""add column to storage config table

Revision ID: 2baa68396931
Revises: 3caf11127442
Create Date: 2023-01-11 01:45:34.988303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2baa68396931'
down_revision = '3caf11127442'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('storageconfig', sa.Column('is_default', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('storageconfig', 'is_default')
    # ### end Alembic commands ###
