"""store cookies with data use

Revision ID: 4b9fcc1e800c
Revises: 317e6197c76a
Create Date: 2023-06-06 16:15:15.067597

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "4b9fcc1e800c"
down_revision = "317e6197c76a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "privacydeclaration", sa.Column("cookies", sa.ARRAY(sa.String()), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("privacydeclaration", "cookies")
    # ### end Alembic commands ###
