"""add_role_based_foundation

Revision ID: 985d3756f908
Revises: 8e198eb13802
Create Date: 2023-02-17 21:04:20.113779

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "985d3756f908"
down_revision = "8e198eb13802"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "client",
        sa.Column("roles", sa.ARRAY(sa.String()), server_default="{}", nullable=True),
    )
    op.alter_column(
        "client", "scopes", existing_type=postgresql.ARRAY(sa.VARCHAR()), nullable=True
    )
    op.add_column(
        "fidesuserpermissions", sa.Column("roles", sa.ARRAY(sa.String()), nullable=True)
    )
    op.alter_column(
        "fidesuserpermissions",
        "scopes",
        existing_type=postgresql.ARRAY(sa.VARCHAR()),
        nullable=True,
    )


def downgrade():
    op.alter_column(
        "fidesuserpermissions",
        "scopes",
        existing_type=postgresql.ARRAY(sa.VARCHAR()),
        nullable=False,
    )
    op.drop_column("fidesuserpermissions", "roles")
    op.alter_column(
        "client", "scopes", existing_type=postgresql.ARRAY(sa.VARCHAR()), nullable=False
    )
    op.drop_column("client", "roles")
