import { DiffStatus, StagedResourceTypeValue } from "~/types/api";
import { CloudInfraStagedResource } from "~/types/api/models/CloudInfraStagedResource";

const ACCOUNT_PRIMARY = "123456789012";
const ACCOUNT_SECONDARY = "210987654321";

export const MOCK_SYSTEM_RESOURCES: CloudInfraStagedResource[] = [
  {
    urn: "arn:aws:s3:::ethyca-prod-events",
    name: "ethyca-prod-events",
    description: "Primary order events bucket",
    monitor_config_id: "aws_infra_prod",
    updated_at: "2026-05-12T14:32:11Z",
    diff_status: DiffStatus.MONITORED,
    resource_type: StagedResourceTypeValue.CLOUD_INFRASTRUCTURE,
    service: "s3",
    location: "us-east-1",
    cloud_account_id: ACCOUNT_PRIMARY,
    source_id: "arn:aws:s3:::ethyca-prod-events",
    tags: {
      Environment: "production",
      Team: "commerce-platform",
      DataClassification: "pii",
    },
    meta: {
      provider: "aws",
      source_type: "AWS::S3::Bucket",
      category: "Cloud Object Storage",
      raw_response: {},
    },
  },
  {
    urn: "arn:aws:s3:::ethyca-prod-receipts",
    name: "ethyca-prod-receipts",
    description: "Customer receipt PDFs",
    monitor_config_id: "aws_infra_prod",
    updated_at: "2026-05-12T14:32:11Z",
    diff_status: DiffStatus.MONITORED,
    resource_type: StagedResourceTypeValue.CLOUD_INFRASTRUCTURE,
    service: "s3",
    location: "us-east-1",
    cloud_account_id: ACCOUNT_PRIMARY,
    source_id: "arn:aws:s3:::ethyca-prod-receipts",
    tags: {
      Environment: "production",
      Team: "commerce-platform",
      CostCenter: "ops",
    },
    meta: {
      provider: "aws",
      source_type: "AWS::S3::Bucket",
      category: "Cloud Object Storage",
      raw_response: {},
    },
  },
  {
    urn: "arn:aws:s3:::ethyca-eu-archive",
    name: "ethyca-eu-archive",
    description: "Long-term archive (EU)",
    monitor_config_id: "aws_infra_prod",
    updated_at: "2026-05-09T08:12:00Z",
    diff_status: DiffStatus.MONITORED,
    resource_type: StagedResourceTypeValue.CLOUD_INFRASTRUCTURE,
    service: "s3",
    location: "eu-west-1",
    cloud_account_id: ACCOUNT_PRIMARY,
    source_id: "arn:aws:s3:::ethyca-eu-archive",
    tags: {
      Environment: "production",
      DataClassification: "restricted",
    },
    meta: {
      provider: "aws",
      source_type: "AWS::S3::Bucket",
      category: "Cloud Object Storage",
      raw_response: {},
    },
  },
  {
    urn: "arn:aws:s3:::ethyca-staging-events",
    name: "ethyca-staging-events",
    description: "Staging mirror of prod events",
    monitor_config_id: "aws_infra_staging",
    updated_at: "2026-05-04T22:01:43Z",
    diff_status: DiffStatus.MUTED,
    resource_type: StagedResourceTypeValue.CLOUD_INFRASTRUCTURE,
    service: "s3",
    location: "us-west-2",
    cloud_account_id: ACCOUNT_SECONDARY,
    source_id: "arn:aws:s3:::ethyca-staging-events",
    tags: { Environment: "staging", Team: "commerce-platform" },
    meta: {
      provider: "aws",
      source_type: "AWS::S3::Bucket",
      category: "Cloud Object Storage",
      raw_response: {},
    },
  },
  {
    urn: "arn:aws:rds:us-east-1:123456789012:db:customers-prod",
    name: "customers-prod",
    description: "Customer master DB (PostgreSQL)",
    monitor_config_id: "aws_infra_prod",
    updated_at: "2026-05-12T14:32:11Z",
    diff_status: DiffStatus.MONITORED,
    resource_type: StagedResourceTypeValue.CLOUD_INFRASTRUCTURE,
    service: "rds",
    location: "us-east-1",
    cloud_account_id: ACCOUNT_PRIMARY,
    source_id: "arn:aws:rds:us-east-1:123456789012:db:customers-prod",
    tags: {
      Environment: "production",
      Engine: "postgres",
      DataClassification: "pii",
    },
    meta: {
      provider: "aws",
      source_type: "AWS::RDS::DBInstance",
      category: "Cloud Relational Database",
      raw_response: {},
    },
  },
  {
    urn: "arn:aws:rds:us-east-1:123456789012:db:orders-prod",
    name: "orders-prod",
    description: "Orders DB (MySQL)",
    monitor_config_id: "aws_infra_prod",
    updated_at: "2026-05-12T14:32:11Z",
    diff_status: DiffStatus.MONITORED,
    resource_type: StagedResourceTypeValue.CLOUD_INFRASTRUCTURE,
    service: "rds",
    location: "us-east-1",
    cloud_account_id: ACCOUNT_PRIMARY,
    source_id: "arn:aws:rds:us-east-1:123456789012:db:orders-prod",
    tags: { Environment: "production", Engine: "mysql" },
    meta: {
      provider: "aws",
      source_type: "AWS::RDS::DBInstance",
      category: "Cloud Relational Database",
      raw_response: {},
    },
  },
  {
    urn: "arn:aws:rds:eu-west-1:210987654321:db:eu-customers",
    name: "eu-customers",
    description: "EU customer replica",
    monitor_config_id: "aws_infra_eu",
    updated_at: "2026-04-30T09:11:00Z",
    diff_status: DiffStatus.REMOVAL,
    resource_type: StagedResourceTypeValue.CLOUD_INFRASTRUCTURE,
    service: "rds",
    location: "eu-west-1",
    cloud_account_id: ACCOUNT_SECONDARY,
    source_id: "arn:aws:rds:eu-west-1:210987654321:db:eu-customers",
    tags: { Environment: "production", DataResidency: "eu" },
    meta: {
      provider: "aws",
      source_type: "AWS::RDS::DBInstance",
      category: "Cloud Relational Database",
      raw_response: {},
    },
  },
  {
    urn: "arn:aws:lambda:us-east-1:123456789012:function:order-events-router",
    name: "order-events-router",
    description: "Routes order events to downstream consumers",
    monitor_config_id: "aws_infra_prod",
    updated_at: "2026-05-12T14:32:11Z",
    diff_status: DiffStatus.MONITORED,
    resource_type: StagedResourceTypeValue.CLOUD_INFRASTRUCTURE,
    service: "lambda",
    location: "us-east-1",
    cloud_account_id: ACCOUNT_PRIMARY,
    source_id:
      "arn:aws:lambda:us-east-1:123456789012:function:order-events-router",
    tags: { Environment: "production", Runtime: "python3.12" },
    meta: {
      provider: "aws",
      source_type: "AWS::Lambda::Function",
      category: "Cloud Function",
      raw_response: {},
    },
  },
  {
    urn: "arn:aws:lambda:eu-west-1:123456789012:function:consent-webhook",
    name: "consent-webhook",
    description: "Receives consent updates from EU users",
    monitor_config_id: "aws_infra_eu",
    updated_at: "2026-05-08T11:45:00Z",
    diff_status: DiffStatus.MONITORED,
    resource_type: StagedResourceTypeValue.CLOUD_INFRASTRUCTURE,
    service: "lambda",
    location: "eu-west-1",
    cloud_account_id: ACCOUNT_PRIMARY,
    source_id: "arn:aws:lambda:eu-west-1:123456789012:function:consent-webhook",
    tags: { Environment: "production", DataResidency: "eu" },
    meta: {
      provider: "aws",
      source_type: "AWS::Lambda::Function",
      category: "Cloud Function",
      raw_response: {},
    },
  },
  {
    urn: "arn:aws:dynamodb:us-east-1:123456789012:table/session-state",
    name: "session-state",
    description: "Cart session state",
    monitor_config_id: "aws_infra_prod",
    updated_at: "2026-05-12T14:32:11Z",
    diff_status: DiffStatus.MONITORED,
    resource_type: StagedResourceTypeValue.CLOUD_INFRASTRUCTURE,
    service: "dynamodb",
    location: "us-east-1",
    cloud_account_id: ACCOUNT_PRIMARY,
    source_id: "arn:aws:dynamodb:us-east-1:123456789012:table/session-state",
    tags: { Environment: "production", TTL: "24h" },
    meta: {
      provider: "aws",
      source_type: "AWS::DynamoDB::Table",
      category: "Cloud NoSQL Database",
      raw_response: {},
    },
  },
  {
    urn: "arn:aws:redshift:us-west-2:123456789012:cluster:analytics-warehouse",
    name: "analytics-warehouse",
    description: "Order analytics warehouse",
    monitor_config_id: "aws_infra_prod",
    updated_at: "2026-05-12T14:32:11Z",
    diff_status: DiffStatus.MONITORED,
    resource_type: StagedResourceTypeValue.CLOUD_INFRASTRUCTURE,
    service: "redshift",
    location: "us-west-2",
    cloud_account_id: ACCOUNT_PRIMARY,
    source_id:
      "arn:aws:redshift:us-west-2:123456789012:cluster:analytics-warehouse",
    tags: { Environment: "production", CostCenter: "analytics" },
    meta: {
      provider: "aws",
      source_type: "AWS::Redshift::Cluster",
      category: "Cloud Data Warehouse",
      raw_response: {},
    },
  },
  {
    urn: "arn:aws:sagemaker:us-east-1:123456789012:endpoint/recs-prod",
    name: "recs-prod",
    description: "Product recommendation endpoint",
    monitor_config_id: "aws_infra_prod",
    updated_at: "2026-05-12T14:32:11Z",
    diff_status: DiffStatus.MUTED,
    resource_type: StagedResourceTypeValue.CLOUD_INFRASTRUCTURE,
    service: "sagemaker",
    location: "us-east-1",
    cloud_account_id: ACCOUNT_PRIMARY,
    source_id: "arn:aws:sagemaker:us-east-1:123456789012:endpoint/recs-prod",
    tags: { Environment: "production", Model: "v3" },
    meta: {
      provider: "aws",
      source_type: "AWS::SageMaker::Endpoint",
      category: "Cloud ML Platform",
      raw_response: {},
    },
  },
];
