import { HealthStatus, type MockSystem } from "./types";

const s = (
  key: string,
  name: string,
  system_type: string,
  description: string,
  overrides: Partial<MockSystem> = {},
): MockSystem => ({
  fides_key: key,
  name,
  system_type,
  description,
  department: "Engineering",
  responsibility: "Controller",
  roles: ["consumer"],
  purposes: [],
  annotation_percent: 0,
  health: HealthStatus.HEALTHY,
  issues: [],
  issue_count: 0,
  stewards: [],
  group: null,
  logoDomain: null,
  integrations: [],
  monitors: [],
  relationships: [],
  classification: { approved: 0, pending: 0, unreviewed: 0, categories: [] },
  datasets: [],
  privacyRequests: { open: 0, closed: 0, avgAccessDays: 0, avgErasureDays: 0, dsarEnabled: false },
  history: [],
  ...overrides,
});

export const MOCK_SYSTEMS: MockSystem[] = [
  // --- Data warehouses & pipelines ---
  s("snowflake", "Snowflake", "Data warehouse", "Enterprise cloud data warehouse for analytics and ML workloads.", {
    department: "Data Engineering",
    logoDomain: "snowflake.com",
    roles: ["producer", "consumer"],
    purposes: [{ name: "Analytics", color: "info" }, { name: "Fraud prevention", color: "alert" }, { name: "Finance", color: "success" }, { name: "Customer support", color: "default" }, { name: "Marketing", color: "warning" }, { name: "HR", color: "default" }],
    annotation_percent: 78,
    health: HealthStatus.ISSUES,

    issue_count: 0,
    stewards: [{ initials: "AK", name: "Anna Kim" }, { initials: "JG", name: "Jack Gale" }],
    group: "Data engineering",
    agentBriefing: "Snowflake is a critical data warehouse serving analytics and ML workloads. 78% annotation coverage is solid but 22% of fields remain unreviewed. Prioritize completing field classification and reviewing the BigQuery data flow.",
    integrations: [
      { name: "Snowflake — Read/Write", type: "Snowflake", accessLevel: "Read/Write", status: "active", lastTested: "2026-03-24T10:00:00Z", enabledActions: ["access", "erasure"] },
    ],
    monitors: [
      { name: "Production schema scan", frequency: "Daily", status: "completed", lastRun: "2026-03-26T02:00:00Z", resourceCount: 120 },
    ],
    relationships: [
      { systemName: "Amplitude", systemKey: "amplitude", role: "producer", declaredUse: "Analytics", authorizedUses: ["Analytics"], hasViolation: false },
      { systemName: "Looker", systemKey: "looker_dashboards", role: "producer", declaredUse: "Analytics", authorizedUses: ["Analytics"], hasViolation: false },
      { systemName: "BigQuery", systemKey: "bigquery", role: "consumer", declaredUse: "Analytics", authorizedUses: ["Analytics", "Finance"], hasViolation: true, violationReason: "Purpose mismatch — Analytics not authorized by BigQuery" },
    ],
    classification: { approved: 94, pending: 15, unreviewed: 11, categories: [
      { name: "PII — Name, Email, Phone", fieldCount: 32, approvedPercent: 88 },
      { name: "Usage metrics", fieldCount: 48, approvedPercent: 72 },
      { name: "Financial data", fieldCount: 40, approvedPercent: 65 },
    ]},
    datasets: [
      { name: "raw_events", key: "snowflake_raw_events", collectionCount: 12, fieldCount: 85, createdAt: "2025-11-15" },
      { name: "user_profiles", key: "snowflake_user_profiles", collectionCount: 4, fieldCount: 35, createdAt: "2025-12-01" },
    ],
    privacyRequests: { open: 3, closed: 18, avgAccessDays: 2.1, avgErasureDays: 4.5, dsarEnabled: true },
    history: [
      { timestamp: "2026-03-25T14:00:00Z", action: "Steward assigned", category: "steward", user: "Anna Kim", detail: "Added Jack Gale as data steward" },
      { timestamp: "2026-03-22T09:00:00Z", action: "Purpose updated", category: "purpose", user: "System", detail: "Added Finance purpose" },
      { timestamp: "2026-03-18T11:00:00Z", action: "Integration tested", category: "integration", user: "Anna Kim", detail: "Snowflake Read/Write — passed" },
    ],
  }),

  s("bigquery", "BigQuery", "Data warehouse", "Google Cloud data warehouse for analytics, BI, and ML.", {
    department: "Engineering",
    logoDomain: "cloud.google.com",
    roles: ["producer", "consumer"],
    purposes: [{ name: "Analytics", color: "info" }, { name: "Finance", color: "success" }, { name: "Fraud prevention", color: "alert" }, { name: "Marketing", color: "warning" }, { name: "Customer support", color: "default" }],
    annotation_percent: 62,
    health: HealthStatus.ISSUES,

    issue_count: 2,
    issues: [
      { title: "High % unreviewed fields", severity: "warning", resolveHref: "#assets" },
      { title: "DSAR not ready", severity: "warning", resolveHref: "#integrations" },
    ],
    stewards: [{ initials: "AK", name: "Anna Kim" }],
    group: "Data engineering",
    agentBriefing: "BigQuery has 2 governance issues including a failed Fivetran integration. 62% annotation coverage needs improvement — 30 fields are unreviewed. DSAR automation is not yet enabled despite active integrations.",
    integrations: [
      { name: "Google Cloud — Read/Write", type: "BigQuery", accessLevel: "Read/Write", status: "active", lastTested: "2026-03-24T08:00:00Z", enabledActions: ["access", "erasure"] },
      { name: "Fivetran — Read only", type: "Fivetran", accessLevel: "Read", status: "failed", lastTested: "2026-03-23T12:00:00Z", enabledActions: ["access"] },
    ],
    monitors: [
      { name: "Production schema scan", frequency: "Daily", status: "completed", lastRun: "2026-03-26T02:00:00Z", resourceCount: 84 },
      { name: "PII field detector", frequency: "Weekly", status: "processing", lastRun: "2026-03-24T06:00:00Z", resourceCount: 12 },
    ],
    relationships: [
      { systemName: "Amplitude", systemKey: "amplitude", role: "producer", declaredUse: "Analytics", authorizedUses: ["Analytics"], hasViolation: false },
      { systemName: "Looker Dashboards", systemKey: "looker_dashboards", role: "producer", declaredUse: "Analytics", authorizedUses: ["Analytics"], hasViolation: false },
      { systemName: "Snowflake", systemKey: "snowflake", role: "consumer", declaredUse: "Analytics", authorizedUses: ["Analytics", "Fraud prevention", "Finance"], hasViolation: false },
      { systemName: "Salesforce", systemKey: "salesforce", role: "consumer", declaredUse: "Analytics", authorizedUses: ["Customer support"], hasViolation: true, violationReason: "Purpose mismatch — Analytics not authorized by Salesforce" },
    ],
    classification: { approved: 148, pending: 62, unreviewed: 30, categories: [
      { name: "PII — Name, Email, Phone", fieldCount: 48, approvedPercent: 80 },
      { name: "Usage metrics", fieldCount: 72, approvedPercent: 55 },
      { name: "Financial data", fieldCount: 28, approvedPercent: 40 },
    ]},
    datasets: [
      { name: "analytics_events", key: "bq_analytics_events", collectionCount: 18, fieldCount: 65, createdAt: "2025-10-01" },
      { name: "user_data", key: "bq_user_data", collectionCount: 12, fieldCount: 42, createdAt: "2025-10-15" },
      { name: "financial_reports", key: "bq_financial", collectionCount: 15, fieldCount: 38, createdAt: "2025-11-01" },
      { name: "marketing_attribution", key: "bq_marketing", collectionCount: 10, fieldCount: 28, createdAt: "2025-11-20" },
      { name: "product_metrics", key: "bq_product", collectionCount: 14, fieldCount: 35, createdAt: "2025-12-01" },
      { name: "support_tickets", key: "bq_support", collectionCount: 8, fieldCount: 18, createdAt: "2026-01-10" },
      { name: "fraud_signals", key: "bq_fraud", collectionCount: 7, fieldCount: 14, createdAt: "2026-02-01" },
    ],
    privacyRequests: { open: 4, closed: 12, avgAccessDays: 3.2, avgErasureDays: 5.1, dsarEnabled: false },
    history: [
      { timestamp: "2026-03-26T08:00:00Z", action: "Monitor completed", category: "integration", user: "System", detail: "PII field detector found 12 resources" },
      { timestamp: "2026-03-24T14:00:00Z", action: "Integration failed", category: "integration", user: "System", detail: "Fivetran Read only — connection timeout" },
    ],
  }),

  s("fivetran", "Fivetran", "Data pipeline", "Automated data integration and ETL pipeline service.", {
    department: "Data Engineering", logoDomain: "fivetran.com",
    roles: ["producer", "consumer"],
    purposes: [{ name: "Analytics", color: "info" }, { name: "Finance", color: "success" }, { name: "Marketing", color: "warning" }, { name: "Customer support", color: "default" }],
    annotation_percent: 88,
    health: HealthStatus.HEALTHY,
    stewards: [{ initials: "AK", name: "Anna Kim" }],
    group: "Data engineering",
    integrations: [{ name: "Fivetran API", type: "Fivetran", accessLevel: "Read/Write", status: "active", lastTested: "2026-03-25T10:00:00Z", enabledActions: ["access"] }],
    classification: { approved: 52, pending: 5, unreviewed: 2, categories: [{ name: "Usage metrics", fieldCount: 59, approvedPercent: 88 }] },
    datasets: [{ name: "sync_logs", key: "fivetran_sync", collectionCount: 6, fieldCount: 59, createdAt: "2025-09-15" }],
    privacyRequests: { open: 0, closed: 3, avgAccessDays: 1.5, avgErasureDays: 2.0, dsarEnabled: true },
    history: [{ timestamp: "2026-03-25T10:00:00Z", action: "Integration tested", category: "integration", user: "Anna Kim", detail: "Fivetran API — passed" }],
  }),

  s("dbt", "dbt", "Data transformation", "SQL-based data transformation and modeling tool.", {
    department: "Data Engineering", logoDomain: "getdbt.com",
    roles: ["consumer"],
    purposes: [{ name: "Analytics", color: "info" }, { name: "Finance", color: "success" }, { name: "Fraud prevention", color: "alert" }],
    annotation_percent: 45,
    health: HealthStatus.ISSUES,
    issue_count: 1,
    issues: [{ title: "High % unreviewed fields", severity: "warning", resolveHref: "#assets" }],
    stewards: [{ initials: "JG", name: "Jack Gale" }],
    group: "Data engineering",
    classification: { approved: 20, pending: 10, unreviewed: 15, categories: [{ name: "Usage metrics", fieldCount: 45, approvedPercent: 44 }] },
    history: [{ timestamp: "2026-03-20T09:00:00Z", action: "Purpose assigned", category: "purpose", user: "Jack Gale", detail: "Added Analytics purpose" }],
  }),

  s("airflow", "Airflow", "Orchestration", "Workflow orchestration platform for data pipelines.", {
    department: "Data Engineering", logoDomain: "airflow.apache.org",
    roles: ["consumer"],
    purposes: [{ name: "Analytics", color: "info" }, { name: "Marketing", color: "warning" }, { name: "HR", color: "default" }],
    annotation_percent: 55,
    health: HealthStatus.ISSUES,
    issue_count: 2,
    issues: [
      { title: "No integration linked", severity: "warning", resolveHref: "#integrations" },
      { title: "DSAR not ready", severity: "warning", resolveHref: "#integrations" },
    ],
    stewards: [{ initials: "AK", name: "Anna Kim" }],
    group: "Data engineering",
    history: [],
  }),

  // --- Analytics & Growth ---
  s("amplitude", "Amplitude", "Analytics", "Product analytics platform for user behavior insights.", {
    department: "Product", logoDomain: "amplitude.com",
    roles: ["consumer"],
    purposes: [{ name: "Analytics", color: "info" }, { name: "Fraud prevention", color: "alert" }, { name: "Marketing", color: "warning" }, { name: "Customer support", color: "default" }],
    annotation_percent: 91,
    health: HealthStatus.HEALTHY,
    stewards: [{ initials: "RS", name: "Rachel Smith" }],
    group: "Growth",
    integrations: [{ name: "Amplitude API", type: "Amplitude", accessLevel: "Read", status: "active", lastTested: "2026-03-25T14:00:00Z", enabledActions: ["access"] }],
    classification: { approved: 85, pending: 5, unreviewed: 3, categories: [{ name: "Behavioral data", fieldCount: 93, approvedPercent: 91 }] },
    datasets: [{ name: "events", key: "amplitude_events", collectionCount: 4, fieldCount: 93, createdAt: "2025-08-01" }],
    privacyRequests: { open: 1, closed: 8, avgAccessDays: 1.8, avgErasureDays: 3.0, dsarEnabled: true },
    history: [{ timestamp: "2026-03-25T14:00:00Z", action: "Integration tested", category: "integration", user: "Rachel Smith", detail: "Amplitude API — passed" }],
  }),

  s("google_ads", "Google Ads", "Ad platform", "Advertising platform for search and display ad campaigns.", {
    department: "Marketing", logoDomain: "ads.google.com",
    roles: ["consumer"],
    purposes: [{ name: "Marketing", color: "warning" }, { name: "Analytics", color: "info" }, { name: "Customer support", color: "default" }, { name: "Fraud prevention", color: "alert" }],
    annotation_percent: 30,
    health: HealthStatus.ISSUES,
    issue_count: 2,
    issues: [
      { title: "High % unreviewed fields", severity: "warning", resolveHref: "#assets" },
      { title: "No data steward assigned", severity: "warning", resolveHref: "#information" },
    ],
    stewards: [],
    group: "Growth",
    history: [],
  }),

  s("braze", "Braze", "Messaging", "Customer engagement platform for push, email, and in-app messaging.", {
    department: "Marketing", logoDomain: "braze.com",
    roles: ["consumer"],
    purposes: [{ name: "Marketing", color: "warning" }, { name: "Analytics", color: "info" }, { name: "HR", color: "default" }],
    annotation_percent: 65,
    health: HealthStatus.HEALTHY,
    stewards: [{ initials: "RS", name: "Rachel Smith" }],
    group: "Growth",
    integrations: [{ name: "Braze API", type: "Braze", accessLevel: "Read/Write", status: "active", lastTested: "2026-03-22T09:00:00Z", enabledActions: ["access", "erasure"] }],
    classification: { approved: 30, pending: 8, unreviewed: 8, categories: [{ name: "Contact data", fieldCount: 46, approvedPercent: 65 }] },
    privacyRequests: { open: 2, closed: 5, avgAccessDays: 2.5, avgErasureDays: 4.0, dsarEnabled: true },
    history: [],
  }),

  s("marketing_analytics", "Marketing Analytics", "Analytics", "Internal marketing analytics and attribution platform.", {
    department: "Marketing",
    roles: ["consumer"],
    purposes: [{ name: "Marketing", color: "warning" }, { name: "Analytics", color: "info" }],
    annotation_percent: 0,
    health: HealthStatus.ISSUES,

    issue_count: 1,
    issues: [{ title: "No data steward assigned", severity: "warning", resolveHref: "#information" }],
    stewards: [],
    group: "Growth",
    agentBriefing: "Marketing Analytics has no data steward assigned and multiple governance issues. With 0% annotation coverage, this system is a significant governance risk. Assign a steward from the Marketing team and begin field classification immediately.",
    history: [],
  }),

  s("ml_platform", "ML Platform", "ML training", "Machine learning training and inference platform.", {
    department: "Engineering",
    roles: ["consumer"],
    purposes: [{ name: "Analytics", color: "info" }],
    annotation_percent: 0,
    health: HealthStatus.ISSUES,

    issue_count: 2,
    issues: [
      { title: "Needs classification", severity: "warning", resolveHref: "#assets" },
      { title: "No integration linked", severity: "warning", resolveHref: "#integrations" },
    ],
    stewards: [{ initials: "RS", name: "Rachel Smith" }],
    group: "Growth",
    history: [],
  }),

  // --- Finance ---
  s("stripe", "Stripe", "Payment processor", "Online payment processing and billing platform.", {
    department: "Finance", logoDomain: "stripe.com",
    responsibility: "Processor",
    roles: ["producer"],
    purposes: [{ name: "Finance", color: "success" }, { name: "Analytics", color: "info" }, { name: "Fraud prevention", color: "alert" }, { name: "HR", color: "default" }],
    annotation_percent: 55,
    health: HealthStatus.ISSUES,
    issue_count: 1,
    issues: [{ title: "High % unreviewed fields", severity: "warning", resolveHref: "#assets" }],
    stewards: [{ initials: "MB", name: "Mike Brown" }],
    group: "Finance & accounting",
    integrations: [{ name: "Stripe API", type: "Stripe", accessLevel: "Read/Write", status: "active", lastTested: "2026-03-24T16:00:00Z", enabledActions: ["access", "erasure"] }],
    classification: { approved: 25, pending: 12, unreviewed: 8, categories: [{ name: "Financial data", fieldCount: 45, approvedPercent: 56 }] },
    datasets: [{ name: "payments", key: "stripe_payments", collectionCount: 5, fieldCount: 45, createdAt: "2025-07-01" }],
    privacyRequests: { open: 1, closed: 6, avgAccessDays: 2.0, avgErasureDays: 3.5, dsarEnabled: true },
    history: [],
  }),

  s("netsuite", "NetSuite", "ERP", "Enterprise resource planning for finance, inventory, and operations.", {
    department: "Finance", logoDomain: "netsuite.com",
    roles: ["producer", "consumer"],
    purposes: [{ name: "Finance", color: "success" }, { name: "Analytics", color: "info" }, { name: "Customer support", color: "default" }, { name: "Marketing", color: "warning" }],
    annotation_percent: 79,
    health: HealthStatus.HEALTHY,
    stewards: [{ initials: "MB", name: "Mike Brown" }],
    group: "Finance & accounting",
    integrations: [{ name: "NetSuite API", type: "NetSuite", accessLevel: "Read/Write", status: "active", lastTested: "2026-03-23T11:00:00Z", enabledActions: ["access"] }],
    classification: { approved: 60, pending: 10, unreviewed: 6, categories: [{ name: "Financial data", fieldCount: 76, approvedPercent: 79 }] },
    privacyRequests: { open: 0, closed: 4, avgAccessDays: 3.0, avgErasureDays: 6.0, dsarEnabled: true },
    history: [],
  }),

  s("chargebee", "Chargebee", "Payment processor", "Subscription billing and revenue management platform.", {
    department: "Finance", logoDomain: "chargebee.com",
    roles: ["producer"],
    purposes: [{ name: "Finance", color: "success" }, { name: "Analytics", color: "info" }, { name: "Marketing", color: "warning" }],
    annotation_percent: 40,
    health: HealthStatus.ISSUES,
    issue_count: 1,
    issues: [{ title: "DSAR not ready", severity: "warning", resolveHref: "#integrations" }],
    stewards: [{ initials: "MB", name: "Mike Brown" }],
    group: "Finance & accounting",
    history: [],
  }),

  s("expensify", "Expensify", "Expense management", "Expense reporting and corporate card management.", {
    department: "Finance", logoDomain: "expensify.com",
    roles: ["consumer"],
    purposes: [{ name: "Finance", color: "success" }, { name: "HR", color: "default" }, { name: "Analytics", color: "info" }],
    annotation_percent: 35,
    health: HealthStatus.ISSUES,
    issue_count: 2,
    issues: [
      { title: "No integration linked", severity: "warning", resolveHref: "#integrations" },
      { title: "High % unreviewed fields", severity: "warning", resolveHref: "#assets" },
    ],
    stewards: [],
    group: "Finance & accounting",
    history: [],
  }),

  // --- Trust & Safety ---
  s("fraud_detection", "Fraud Detection Service", "Internal service", "Real-time transaction fraud detection and risk scoring.", {
    department: "Trust & Safety",
    roles: ["consumer"],
    purposes: [{ name: "Fraud prevention", color: "alert" }, { name: "Analytics", color: "info" }, { name: "Finance", color: "success" }, { name: "Customer support", color: "default" }],
    annotation_percent: 94,
    health: HealthStatus.HEALTHY,
    stewards: [{ initials: "CK", name: "Chris Kelly" }],
    group: "Trust & safety",
    integrations: [{ name: "Internal API", type: "REST", accessLevel: "Read", status: "active", lastTested: "2026-03-25T08:00:00Z", enabledActions: ["access"] }],
    classification: { approved: 42, pending: 2, unreviewed: 1, categories: [{ name: "Risk data", fieldCount: 45, approvedPercent: 93 }] },
    privacyRequests: { open: 0, closed: 2, avgAccessDays: 1.0, avgErasureDays: 2.0, dsarEnabled: true },
    history: [],
  }),

  s("risk_scoring_api", "Risk Scoring API", "Internal service", "API for real-time risk scoring of users and transactions.", {
    department: "Trust & Safety",
    roles: ["producer", "consumer"],
    purposes: [{ name: "Fraud prevention", color: "alert" }, { name: "Analytics", color: "info" }, { name: "Customer support", color: "default" }],
    annotation_percent: 97,
    health: HealthStatus.HEALTHY,
    stewards: [{ initials: "CK", name: "Chris Kelly" }],
    group: "Trust & safety",
    integrations: [{ name: "Risk API", type: "REST", accessLevel: "Read/Write", status: "active", lastTested: "2026-03-26T06:00:00Z", enabledActions: ["access"] }],
    classification: { approved: 28, pending: 1, unreviewed: 0, categories: [{ name: "Risk scores", fieldCount: 29, approvedPercent: 97 }] },
    history: [],
  }),

  s("sift", "Sift", "Fraud detection", "Third-party fraud detection and content moderation platform.", {
    department: "Trust & Safety", logoDomain: "sift.com",
    responsibility: "Processor",
    roles: ["consumer"],
    purposes: [{ name: "Fraud prevention", color: "alert" }, { name: "Finance", color: "success" }, { name: "Analytics", color: "info" }, { name: "Marketing", color: "warning" }],
    annotation_percent: 70,
    health: HealthStatus.ISSUES,
    issue_count: 1,
    issues: [{ title: "High % unreviewed fields", severity: "warning", resolveHref: "#assets" }],
    stewards: [{ initials: "CK", name: "Chris Kelly" }],
    group: "Trust & safety",
    history: [],
  }),

  // --- Customer Platform ---
  s("salesforce", "Salesforce", "CRM", "Customer relationship management for sales, service, and marketing.", {
    department: "Sales", logoDomain: "salesforce.com",
    roles: ["producer", "consumer"],
    purposes: [{ name: "Customer support", color: "default" }, { name: "Analytics", color: "info" }, { name: "Marketing", color: "warning" }, { name: "Finance", color: "success" }, { name: "HR", color: "default" }, { name: "Fraud prevention", color: "alert" }],
    annotation_percent: 72,
    health: HealthStatus.ISSUES,
    issue_count: 1,
    issues: [{ title: "DSAR not ready", severity: "warning", resolveHref: "#integrations" }],
    stewards: [{ initials: "LT", name: "Lisa Torres" }],
    group: "Customer platform",
    integrations: [{ name: "Salesforce API", type: "Salesforce", accessLevel: "Read/Write", status: "active", lastTested: "2026-03-24T14:00:00Z", enabledActions: ["access", "erasure"] }],
    classification: { approved: 80, pending: 20, unreviewed: 11, categories: [{ name: "CRM data", fieldCount: 111, approvedPercent: 72 }] },
    datasets: [{ name: "contacts", key: "sf_contacts", collectionCount: 3, fieldCount: 55, createdAt: "2025-06-01" }, { name: "accounts", key: "sf_accounts", collectionCount: 2, fieldCount: 30, createdAt: "2025-06-01" }],
    privacyRequests: { open: 2, closed: 15, avgAccessDays: 2.8, avgErasureDays: 4.2, dsarEnabled: false },
    history: [],
  }),

  s("zendesk", "Zendesk", "Support platform", "Customer support ticketing and knowledge base platform.", {
    department: "Customer Success", logoDomain: "zendesk.com",
    roles: ["consumer"],
    purposes: [{ name: "Customer support", color: "default" }, { name: "Analytics", color: "info" }, { name: "Marketing", color: "warning" }],
    annotation_percent: 82,
    health: HealthStatus.HEALTHY,
    stewards: [{ initials: "LT", name: "Lisa Torres" }],
    group: "Customer platform",
    integrations: [{ name: "Zendesk API", type: "Zendesk", accessLevel: "Read/Write", status: "active", lastTested: "2026-03-25T10:00:00Z", enabledActions: ["access", "erasure"] }],
    classification: { approved: 40, pending: 5, unreviewed: 4, categories: [{ name: "Support data", fieldCount: 49, approvedPercent: 82 }] },
    privacyRequests: { open: 1, closed: 10, avgAccessDays: 1.5, avgErasureDays: 3.0, dsarEnabled: true },
    history: [],
  }),

  s("intercom", "Intercom", "Messaging", "Customer messaging platform for support and engagement.", {
    department: "Customer Success", logoDomain: "intercom.com",
    roles: ["consumer"],
    purposes: [{ name: "Customer support", color: "default" }, { name: "Analytics", color: "info" }, { name: "HR", color: "default" }, { name: "Fraud prevention", color: "alert" }],
    annotation_percent: 60,
    health: HealthStatus.ISSUES,
    issue_count: 1,
    issues: [{ title: "High % unreviewed fields", severity: "warning", resolveHref: "#assets" }],
    stewards: [{ initials: "LT", name: "Lisa Torres" }],
    group: "Customer platform",
    history: [],
  }),

  s("auth0", "Auth0", "Identity provider", "Identity and access management platform.", {
    department: "Engineering", logoDomain: "auth0.com",
    roles: ["producer"],
    purposes: [{ name: "Analytics", color: "info" }, { name: "Fraud prevention", color: "alert" }, { name: "Customer support", color: "default" }],
    annotation_percent: 85,
    health: HealthStatus.HEALTHY,
    stewards: [{ initials: "JG", name: "Jack Gale" }],
    group: "Customer platform",
    integrations: [
      { name: "Auth0 API", type: "Auth0", accessLevel: "Read", status: "active", lastTested: "2026-03-26T07:00:00Z", enabledActions: ["access"] },
      { name: "Auth0 Management API", type: "Auth0", accessLevel: "Read/Write", status: "active", lastTested: "2026-03-25T14:00:00Z", enabledActions: ["access", "erasure"] },
    ],
    monitors: [
      { name: "Identity schema scan", frequency: "Weekly", status: "completed", lastRun: "2026-03-25T06:00:00Z", resourceCount: 26 },
      { name: "Token usage monitor", frequency: "Daily", status: "completed", lastRun: "2026-03-26T02:00:00Z", resourceCount: 8 },
    ],
    relationships: [
      { systemName: "Segment", systemKey: "segment", role: "producer", declaredUse: "Analytics", authorizedUses: ["Analytics"], hasViolation: false },
      { systemName: "Fraud Detection Service", systemKey: "fraud_detection", role: "producer", declaredUse: "Fraud prevention", authorizedUses: ["Fraud prevention"], hasViolation: false },
      { systemName: "Internal API", systemKey: "internal_api", role: "producer", declaredUse: "Customer support", authorizedUses: ["Customer support", "Analytics"], hasViolation: false },
    ],
    classification: { approved: 612, pending: 486, unreviewed: 538, categories: [
      { name: "Identity data", fieldCount: 420, approvedPercent: 82 },
      { name: "Authentication tokens", fieldCount: 286, approvedPercent: 54 },
      { name: "Session metadata", fieldCount: 196, approvedPercent: 41 },
      { name: "Authorization rules", fieldCount: 142, approvedPercent: 68 },
    ]},
    datasets: [
      { name: "auth0_users", key: "auth0_users", collectionCount: 12, fieldCount: 1842, createdAt: "2025-11-01", category: "Identity data", usage: "DSR Access, DSR Erasure", status: "approved" },
      { name: "auth0_sessions", key: "auth0_sessions", collectionCount: 8, fieldCount: 956, createdAt: "2025-12-15", category: "Session metadata", usage: "DSR Access", status: "approved" },
      { name: "auth0_logs", key: "auth0_logs", collectionCount: 5, fieldCount: 2314, createdAt: "2026-01-10", category: "Audit logs", usage: "Monitoring", status: "approved" },
      { name: "auth0_tokens", key: "auth0_tokens", collectionCount: 3, fieldCount: 428, createdAt: "2026-02-01", category: "Authentication tokens", usage: "DSR Erasure", status: "pending" },
      { name: "auth0_roles", key: "auth0_roles", collectionCount: 2, fieldCount: 186, createdAt: "2026-02-15", category: "Authorization", usage: "Access control", status: "approved" },
      { name: "auth0_connections", key: "auth0_connections", collectionCount: 4, fieldCount: 312, createdAt: "2026-03-01", category: "Identity providers", usage: "Configuration", status: "draft" },
    ],
    privacyRequests: { open: 147, closed: 3842, avgAccessDays: 1.8, avgErasureDays: 3.2, dsarEnabled: true, statusBreakdown: { pending: 23, inProgress: 84, approved: 40, complete: 3842, denied: 12, error: 3 } },
    history: [
      { timestamp: "2026-03-26T08:00:00Z", action: "Monitor completed", category: "integration", user: "System", detail: "Identity schema scan completed — 26 resources found" },
      { timestamp: "2026-03-25T16:45:00Z", action: "Label changed", category: "classification", user: "Jack Gale", detail: "Reclassified user.phone_number from contact to PII", fieldName: "user.phone_number", oldValue: "Contact info", newValue: "PII — Phone number", reason: "Field contains direct personal identifier per GDPR Art. 4" },
      { timestamp: "2026-03-25T16:30:00Z", action: "Classification approved", category: "classification", user: "Jack Gale", detail: "Approved classification for user.email", fieldName: "user.email", newValue: "PII — Email address" },
      { timestamp: "2026-03-25T16:20:00Z", action: "Classification approved", category: "classification", user: "Jack Gale", detail: "Approved classification for user.name", fieldName: "user.name", newValue: "PII — Full name" },
      { timestamp: "2026-03-25T16:10:00Z", action: "Field reviewed", category: "classification", user: "Jack Gale", detail: "Reviewed user.last_login — marked as non-PII", fieldName: "user.last_login", newValue: "System metadata", reason: "Timestamp only, no personal data" },
      { timestamp: "2026-03-25T14:30:00Z", action: "Integration tested", category: "integration", user: "Jack Gale", detail: "Auth0 Management API — connection test passed" },
      { timestamp: "2026-03-24T11:00:00Z", action: "Label changed", category: "classification", user: "Anna Kim", detail: "Changed user.ip_address from system data to PII", fieldName: "user.ip_address", oldValue: "System data", newValue: "PII — IP address", reason: "IP addresses are personal data under GDPR recital 30" },
      { timestamp: "2026-03-24T10:00:00Z", action: "Classification approved", category: "classification", user: "Jack Gale", detail: "Bulk approved 18 identity fields", fieldName: "user.* (18 fields)", newValue: "Identity data" },
      { timestamp: "2026-03-23T15:00:00Z", action: "Category assigned", category: "classification", user: "Anna Kim", detail: "Assigned 'Identity data' category to Auth0 dataset", fieldName: "auth0_identity.*", newValue: "Identity data", reason: "All fields relate to user identity and authentication" },
      { timestamp: "2026-03-22T09:00:00Z", action: "Purpose added", category: "purpose", user: "Jack Gale", detail: "Added 'Customer support' purpose to Auth0" },
      { timestamp: "2026-03-21T14:00:00Z", action: "Purpose added", category: "purpose", user: "Jack Gale", detail: "Added 'Fraud prevention' purpose to Auth0" },
      { timestamp: "2026-03-20T11:00:00Z", action: "Steward assigned", category: "steward", user: "Anna Kim", detail: "Jack Gale assigned as data steward" },
      { timestamp: "2026-03-19T10:00:00Z", action: "Integration configured", category: "integration", user: "Jack Gale", detail: "Auth0 Management API added with read/write access and erasure scope" },
      { timestamp: "2026-03-18T16:00:00Z", action: "System registered", category: "system", user: "System", detail: "Auth0 added to system inventory via API discovery" },
      { timestamp: "2026-03-15T09:00:00Z", action: "Integration added", category: "integration", user: "Jack Gale", detail: "Auth0 API integration configured with read access" },
      { timestamp: "2026-03-12T14:00:00Z", action: "Monitor created", category: "integration", user: "Anna Kim", detail: "Identity schema scan monitor set to weekly frequency" },
    ],
  }),

  s("segment", "Segment", "CDP", "Customer data platform for event collection and routing.", {
    department: "Engineering", logoDomain: "segment.com",
    roles: ["producer", "consumer"],
    purposes: [{ name: "Analytics", color: "info" }, { name: "Marketing", color: "warning" }, { name: "Customer support", color: "default" }, { name: "Fraud prevention", color: "alert" }, { name: "Finance", color: "success" }],
    annotation_percent: 75,
    health: HealthStatus.ISSUES,
    issue_count: 1,
    issues: [{ title: "DSAR not ready", severity: "warning", resolveHref: "#integrations" }],
    stewards: [{ initials: "RS", name: "Rachel Smith" }],
    group: "Customer platform",
    integrations: [{ name: "Segment API", type: "Segment", accessLevel: "Read/Write", status: "active", lastTested: "2026-03-24T12:00:00Z", enabledActions: ["access"] }],
    classification: { approved: 55, pending: 10, unreviewed: 8, categories: [{ name: "Event data", fieldCount: 73, approvedPercent: 75 }] },
    privacyRequests: { open: 1, closed: 7, avgAccessDays: 2.0, avgErasureDays: 3.5, dsarEnabled: false },
    history: [],
  }),

  // --- HR ---
  s("workday", "Workday", "HRIS", "Human capital management for HR, payroll, and talent.", {
    department: "HR", logoDomain: "workday.com",
    responsibility: "Controller",
    roles: ["producer", "consumer"],
    purposes: [{ name: "HR", color: "default" }, { name: "Finance", color: "success" }, { name: "Analytics", color: "info" }, { name: "Customer support", color: "default" }],
    annotation_percent: 90,
    health: HealthStatus.HEALTHY,
    stewards: [{ initials: "DP", name: "Diana Park" }],
    group: "HR & recruiting",
    integrations: [{ name: "Workday API", type: "Workday", accessLevel: "Read/Write", status: "active", lastTested: "2026-03-23T09:00:00Z", enabledActions: ["access", "erasure"] }],
    classification: { approved: 65, pending: 5, unreviewed: 2, categories: [{ name: "Employee data", fieldCount: 72, approvedPercent: 90 }] },
    privacyRequests: { open: 0, closed: 3, avgAccessDays: 2.0, avgErasureDays: 5.0, dsarEnabled: true },
    history: [],
  }),

  s("greenhouse", "Greenhouse", "HRIS", "Applicant tracking and recruiting platform.", {
    department: "HR", logoDomain: "greenhouse.io",
    roles: ["consumer"],
    purposes: [{ name: "HR", color: "default" }, { name: "Analytics", color: "info" }, { name: "Finance", color: "success" }],
    annotation_percent: 50,
    health: HealthStatus.ISSUES,
    issue_count: 1,
    issues: [{ title: "DSAR not ready", severity: "warning", resolveHref: "#integrations" }],
    stewards: [{ initials: "DP", name: "Diana Park" }],
    group: "HR & recruiting",
    history: [],
  }),

  s("bamboohr", "BambooHR", "HRIS", "HR management software for small and mid-size businesses.", {
    department: "HR", logoDomain: "bamboohr.com",
    roles: ["consumer"],
    purposes: [{ name: "HR", color: "default" }, { name: "Finance", color: "success" }, { name: "Customer support", color: "default" }, { name: "Analytics", color: "info" }, { name: "Marketing", color: "warning" }],
    annotation_percent: 40,
    health: HealthStatus.ISSUES,
    issue_count: 2,
    issues: [
      { title: "No integration linked", severity: "warning", resolveHref: "#integrations" },
      { title: "High % unreviewed fields", severity: "warning", resolveHref: "#assets" },
    ],
    stewards: [],
    group: "HR & recruiting",
    history: [],
  }),

  s("slack", "Slack", "Messaging", "Team communication and collaboration platform.", {
    department: "IT", logoDomain: "slack.com",
    roles: ["consumer"],
    purposes: [{ name: "HR", color: "default" }, { name: "Analytics", color: "info" }, { name: "Marketing", color: "warning" }],
    annotation_percent: 20,
    health: HealthStatus.ISSUES,
    issue_count: 3,
    issues: [
      { title: "No data steward assigned", severity: "warning", resolveHref: "#information" },
      { title: "No integration linked", severity: "warning", resolveHref: "#integrations" },
      { title: "Needs classification", severity: "warning", resolveHref: "#assets" },
    ],
    stewards: [],
    agentBriefing: "Slack has 3 governance issues: no steward, no integration, and no classification. With only 20% annotation coverage, this system needs foundational governance setup. Assign an IT team steward and configure the Slack API integration.",
    history: [],
  }),

  // --- Ungrouped ---
  s("internal_api", "Internal API", "Internal service", "Core internal API serving frontend applications.", {
    department: "Engineering",
    roles: ["producer"],
    purposes: [{ name: "Analytics", color: "info" }, { name: "Customer support", color: "default" }, { name: "Finance", color: "success" }],
    annotation_percent: 68,
    health: HealthStatus.ISSUES,
    issue_count: 1,
    issues: [{ title: "No data steward assigned", severity: "warning", resolveHref: "#information" }],
    stewards: [],
    history: [],
  }),

  s("legacy_crm", "Legacy CRM", "CRM", "Legacy customer relationship management system being decommissioned.", {
    department: "Sales",
    roles: ["producer"],
    purposes: [],
    annotation_percent: 15,
    health: HealthStatus.ISSUES,

    issue_count: 3,
    issues: [
      { title: "No data steward assigned", severity: "warning", resolveHref: "#information" },
      { title: "No integration linked", severity: "warning", resolveHref: "#integrations" },
      { title: "Needs classification", severity: "warning", resolveHref: "#assets" },
    ],
    stewards: [],
    agentBriefing: "Legacy CRM is being decommissioned but still has 3 unresolved governance issues. No steward is assigned and annotation coverage is only 15%. Ensure data flows are properly shut down before decommission.",
    history: [],
  }),

  s("test_environment", "Test Environment", "Internal service", "Staging and testing environment for QA.", {
    department: "Engineering",
    roles: ["consumer"],
    purposes: [],
    annotation_percent: 0,
    health: HealthStatus.ISSUES,
    issue_count: 3,
    issues: [
      { title: "No data steward assigned", severity: "warning", resolveHref: "#information" },
      { title: "Needs classification", severity: "warning", resolveHref: "#assets" },
      { title: "No integration linked", severity: "warning", resolveHref: "#integrations" },
    ],
    stewards: [],
    history: [],
  }),
];
