import { HealthStatus, type MockSystem } from "./types";

const s = (
  key: string,
  name: string,
  system_type: string,
  description: string,
  overrides: Partial<MockSystem> = {},
): MockSystem => ({
  fides_key: key,
  name,
  system_type,
  description,
  department: "Engineering",
  responsibility: "Controller",
  roles: ["consumer"],
  purposes: [],
  annotation_percent: 0,
  health: HealthStatus.HEALTHY,
  issues: [],
  issue_count: 0,
  stewards: [],
  group: null,
  logoDomain: null,
  integrations: [],
  monitors: [],
  relationships: [],
  classification: { approved: 0, pending: 0, unreviewed: 0, categories: [] },
  datasets: [],
  privacyRequests: {
    open: 0,
    closed: 0,
    avgAccessDays: 0,
    avgErasureDays: 0,
    dsarEnabled: false,
  },
  history: [],
  assets: [],
  ...overrides,
});

export const MOCK_SYSTEMS: MockSystem[] = [
  // --- Data warehouses & pipelines ---
  s(
    "snowflake",
    "Snowflake",
    "Data warehouse",
    "Enterprise cloud data warehouse for analytics and ML workloads.",
    {
      department: "Data Engineering",
      logoDomain: "snowflake.com",
      roles: ["producer", "consumer"],
      purposes: [
        { name: "Analytics", color: "info" },
        { name: "Fraud prevention", color: "alert" },
        { name: "Finance", color: "success" },
        { name: "Customer support", color: "default" },
        { name: "Marketing", color: "warning" },
        { name: "HR", color: "default" },
      ],
      annotation_percent: 78,
      health: HealthStatus.ISSUES,

      issue_count: 0,
      stewards: [
        { initials: "AK", name: "Anna Kim" },
        { initials: "JG", name: "Jack Gale" },
      ],
      group: "Data engineering",
    },
  ),

  s(
    "bigquery",
    "Auth0",
    "Identity provider",
    "Identity and access management platform.",
    {
      department: "Engineering",
      logoDomain: "auth0.com",
      roles: ["producer", "consumer"],
      purposes: [
        { name: "Analytics", color: "info" },
        { name: "Finance", color: "success" },
        { name: "Fraud prevention", color: "alert" },
        { name: "Marketing", color: "warning" },
        { name: "Customer support", color: "default" },
      ],
      annotation_percent: 62,
      health: HealthStatus.ISSUES,

      issue_count: 2,
      issues: [
        {
          title: "High % unreviewed fields",
          severity: "warning",
          resolveHref: "#assets",
        },
        {
          title: "DSAR not ready",
          severity: "warning",
          resolveHref: "#integrations",
        },
      ],
      stewards: [{ initials: "AK", name: "Anna Kim" }],
      group: "Data engineering",
    },
  ),

  s(
    "fivetran",
    "Fivetran",
    "Data pipeline",
    "Automated data integration and ETL pipeline service.",
    {
      department: "Data Engineering",
      logoDomain: "fivetran.com",
      roles: ["producer", "consumer"],
      purposes: [
        { name: "Analytics", color: "info" },
        { name: "Finance", color: "success" },
        { name: "Marketing", color: "warning" },
        { name: "Customer support", color: "default" },
      ],
      annotation_percent: 88,
      health: HealthStatus.HEALTHY,
      stewards: [{ initials: "AK", name: "Anna Kim" }],
      group: "Data engineering",
    },
  ),

  s(
    "dbt",
    "dbt",
    "Data transformation",
    "SQL-based data transformation and modeling tool.",
    {
      department: "Data Engineering",
      logoDomain: "getdbt.com",
      roles: ["consumer"],
      purposes: [
        { name: "Analytics", color: "info" },
        { name: "Finance", color: "success" },
        { name: "Fraud prevention", color: "alert" },
      ],
      annotation_percent: 45,
      health: HealthStatus.ISSUES,
      issue_count: 1,
      issues: [
        {
          title: "High % unreviewed fields",
          severity: "warning",
          resolveHref: "#assets",
        },
      ],
      stewards: [{ initials: "JG", name: "Jack Gale" }],
      group: "Data engineering",
    },
  ),

  s(
    "airflow",
    "Airflow",
    "Orchestration",
    "Workflow orchestration platform for data pipelines.",
    {
      department: "Data Engineering",
      logoDomain: "airflow.apache.org",
      roles: ["consumer"],
      purposes: [
        { name: "Analytics", color: "info" },
        { name: "Marketing", color: "warning" },
        { name: "HR", color: "default" },
      ],
      annotation_percent: 55,
      health: HealthStatus.ISSUES,
      issue_count: 2,
      issues: [
        {
          title: "No integration linked",
          severity: "warning",
          resolveHref: "#integrations",
        },
        {
          title: "DSAR not ready",
          severity: "warning",
          resolveHref: "#integrations",
        },
      ],
      stewards: [{ initials: "AK", name: "Anna Kim" }],
      group: "Data engineering",
    },
  ),

  // --- Analytics & Growth ---
  s(
    "amplitude",
    "Amplitude",
    "Analytics",
    "Product analytics platform for user behavior insights.",
    {
      department: "Product",
      logoDomain: "amplitude.com",
      roles: ["consumer"],
      purposes: [
        { name: "Analytics", color: "info" },
        { name: "Fraud prevention", color: "alert" },
        { name: "Marketing", color: "warning" },
        { name: "Customer support", color: "default" },
      ],
      annotation_percent: 91,
      health: HealthStatus.HEALTHY,
      stewards: [{ initials: "RS", name: "Rachel Smith" }],
      group: "Growth",
    },
  ),

  s(
    "google_ads",
    "Google Ads",
    "Ad platform",
    "Advertising platform for search and display ad campaigns.",
    {
      department: "Marketing",
      logoDomain: "ads.google.com",
      roles: ["consumer"],
      purposes: [
        { name: "Marketing", color: "warning" },
        { name: "Analytics", color: "info" },
        { name: "Customer support", color: "default" },
        { name: "Fraud prevention", color: "alert" },
      ],
      annotation_percent: 30,
      health: HealthStatus.ISSUES,
      issue_count: 2,
      issues: [
        {
          title: "High % unreviewed fields",
          severity: "warning",
          resolveHref: "#assets",
        },
        {
          title: "No data steward assigned",
          severity: "warning",
          resolveHref: "#information",
        },
      ],
      stewards: [],
      group: "Growth",
    },
  ),

  s(
    "braze",
    "Braze",
    "Messaging",
    "Customer engagement platform for push, email, and in-app messaging.",
    {
      department: "Marketing",
      logoDomain: "braze.com",
      roles: ["consumer"],
      purposes: [
        { name: "Marketing", color: "warning" },
        { name: "Analytics", color: "info" },
        { name: "HR", color: "default" },
      ],
      annotation_percent: 65,
      health: HealthStatus.HEALTHY,
      stewards: [{ initials: "RS", name: "Rachel Smith" }],
      group: "Growth",
    },
  ),

  s(
    "marketing_analytics",
    "Marketing Analytics",
    "Analytics",
    "Internal marketing analytics and attribution platform.",
    {
      department: "Marketing",
      roles: ["consumer"],
      purposes: [
        { name: "Marketing", color: "warning" },
        { name: "Analytics", color: "info" },
      ],
      annotation_percent: 0,
      health: HealthStatus.ISSUES,

      issue_count: 1,
      issues: [
        {
          title: "No data steward assigned",
          severity: "warning",
          resolveHref: "#information",
        },
      ],
      stewards: [],
      group: "Growth",
    },
  ),

  s(
    "ml_platform",
    "ML Platform",
    "ML training",
    "Machine learning training and inference platform.",
    {
      department: "Engineering",
      roles: ["consumer"],
      purposes: [{ name: "Analytics", color: "info" }],
      annotation_percent: 0,
      health: HealthStatus.ISSUES,

      issue_count: 2,
      issues: [
        {
          title: "Needs classification",
          severity: "warning",
          resolveHref: "#assets",
        },
        {
          title: "No integration linked",
          severity: "warning",
          resolveHref: "#integrations",
        },
      ],
      stewards: [{ initials: "RS", name: "Rachel Smith" }],
      group: "Growth",
    },
  ),

  // --- Finance ---
  s(
    "stripe",
    "Stripe",
    "Payment processor",
    "Online payment processing and billing platform.",
    {
      department: "Finance",
      logoDomain: "stripe.com",
      responsibility: "Processor",
      roles: ["producer"],
      purposes: [
        { name: "Finance", color: "success" },
        { name: "Analytics", color: "info" },
        { name: "Fraud prevention", color: "alert" },
        { name: "HR", color: "default" },
      ],
      annotation_percent: 55,
      health: HealthStatus.ISSUES,
      issue_count: 1,
      issues: [
        {
          title: "High % unreviewed fields",
          severity: "warning",
          resolveHref: "#assets",
        },
      ],
      stewards: [{ initials: "MB", name: "Mike Brown" }],
      group: "Finance & accounting",
    },
  ),

  s(
    "netsuite",
    "NetSuite",
    "ERP",
    "Enterprise resource planning for finance, inventory, and operations.",
    {
      department: "Finance",
      logoDomain: "netsuite.com",
      roles: ["producer", "consumer"],
      purposes: [
        { name: "Finance", color: "success" },
        { name: "Analytics", color: "info" },
        { name: "Customer support", color: "default" },
        { name: "Marketing", color: "warning" },
      ],
      annotation_percent: 79,
      health: HealthStatus.HEALTHY,
      stewards: [{ initials: "MB", name: "Mike Brown" }],
      group: "Finance & accounting",
    },
  ),

  s(
    "chargebee",
    "Chargebee",
    "Payment processor",
    "Subscription billing and revenue management platform.",
    {
      department: "Finance",
      logoDomain: "chargebee.com",
      roles: ["producer"],
      purposes: [
        { name: "Finance", color: "success" },
        { name: "Analytics", color: "info" },
        { name: "Marketing", color: "warning" },
      ],
      annotation_percent: 40,
      health: HealthStatus.ISSUES,
      issue_count: 1,
      issues: [
        {
          title: "DSAR not ready",
          severity: "warning",
          resolveHref: "#integrations",
        },
      ],
      stewards: [{ initials: "MB", name: "Mike Brown" }],
      group: "Finance & accounting",
    },
  ),

  s(
    "expensify",
    "Expensify",
    "Expense management",
    "Expense reporting and corporate card management.",
    {
      department: "Finance",
      logoDomain: "expensify.com",
      roles: ["consumer"],
      purposes: [
        { name: "Finance", color: "success" },
        { name: "HR", color: "default" },
        { name: "Analytics", color: "info" },
      ],
      annotation_percent: 35,
      health: HealthStatus.ISSUES,
      issue_count: 2,
      issues: [
        {
          title: "No integration linked",
          severity: "warning",
          resolveHref: "#integrations",
        },
        {
          title: "High % unreviewed fields",
          severity: "warning",
          resolveHref: "#assets",
        },
      ],
      stewards: [],
      group: "Finance & accounting",
    },
  ),

  // --- Trust & Safety ---
  s(
    "fraud_detection",
    "Fraud Detection Service",
    "Internal service",
    "Real-time transaction fraud detection and risk scoring.",
    {
      department: "Trust & Safety",
      roles: ["consumer"],
      purposes: [
        { name: "Fraud prevention", color: "alert" },
        { name: "Analytics", color: "info" },
        { name: "Finance", color: "success" },
        { name: "Customer support", color: "default" },
      ],
      annotation_percent: 94,
      health: HealthStatus.HEALTHY,
      stewards: [{ initials: "CK", name: "Chris Kelly" }],
      group: "Trust & safety",
    },
  ),

  s(
    "risk_scoring_api",
    "Risk Scoring API",
    "Internal service",
    "API for real-time risk scoring of users and transactions.",
    {
      department: "Trust & Safety",
      roles: ["producer", "consumer"],
      purposes: [
        { name: "Fraud prevention", color: "alert" },
        { name: "Analytics", color: "info" },
        { name: "Customer support", color: "default" },
      ],
      annotation_percent: 97,
      health: HealthStatus.HEALTHY,
      stewards: [{ initials: "CK", name: "Chris Kelly" }],
      group: "Trust & safety",
    },
  ),

  s(
    "sift",
    "Sift",
    "Fraud detection",
    "Third-party fraud detection and content moderation platform.",
    {
      department: "Trust & Safety",
      logoDomain: "sift.com",
      responsibility: "Processor",
      roles: ["consumer"],
      purposes: [
        { name: "Fraud prevention", color: "alert" },
        { name: "Finance", color: "success" },
        { name: "Analytics", color: "info" },
        { name: "Marketing", color: "warning" },
      ],
      annotation_percent: 70,
      health: HealthStatus.ISSUES,
      issue_count: 1,
      issues: [
        {
          title: "High % unreviewed fields",
          severity: "warning",
          resolveHref: "#assets",
        },
      ],
      stewards: [{ initials: "CK", name: "Chris Kelly" }],
      group: "Trust & safety",
    },
  ),

  // --- Customer Platform ---
  s(
    "salesforce",
    "Salesforce",
    "CRM",
    "Customer relationship management for sales, service, and marketing.",
    {
      department: "Sales",
      logoDomain: "salesforce.com",
      roles: ["producer", "consumer"],
      purposes: [
        { name: "Customer support", color: "default" },
        { name: "Analytics", color: "info" },
        { name: "Marketing", color: "warning" },
        { name: "Finance", color: "success" },
        { name: "HR", color: "default" },
        { name: "Fraud prevention", color: "alert" },
      ],
      annotation_percent: 72,
      health: HealthStatus.ISSUES,
      issue_count: 1,
      issues: [
        {
          title: "DSAR not ready",
          severity: "warning",
          resolveHref: "#integrations",
        },
      ],
      stewards: [{ initials: "LT", name: "Lisa Torres" }],
      group: "Customer platform",
    },
  ),

  s(
    "zendesk",
    "Zendesk",
    "Support platform",
    "Customer support ticketing and knowledge base platform.",
    {
      department: "Customer Success",
      logoDomain: "zendesk.com",
      roles: ["consumer"],
      purposes: [
        { name: "Customer support", color: "default" },
        { name: "Analytics", color: "info" },
        { name: "Marketing", color: "warning" },
      ],
      annotation_percent: 82,
      health: HealthStatus.HEALTHY,
      stewards: [{ initials: "LT", name: "Lisa Torres" }],
      group: "Customer platform",
    },
  ),

  s(
    "intercom",
    "Intercom",
    "Messaging",
    "Customer messaging platform for support and engagement.",
    {
      department: "Customer Success",
      logoDomain: "intercom.com",
      roles: ["consumer"],
      purposes: [
        { name: "Customer support", color: "default" },
        { name: "Analytics", color: "info" },
        { name: "HR", color: "default" },
        { name: "Fraud prevention", color: "alert" },
      ],
      annotation_percent: 60,
      health: HealthStatus.ISSUES,
      issue_count: 1,
      issues: [
        {
          title: "High % unreviewed fields",
          severity: "warning",
          resolveHref: "#assets",
        },
      ],
      stewards: [{ initials: "LT", name: "Lisa Torres" }],
      group: "Customer platform",
    },
  ),

  s(
    "auth0",
    "BigQuery",
    "Data warehouse",
    "Google Cloud data warehouse for analytics, BI, and ML.",
    {
      department: "Engineering",
      logoDomain: "cloud.google.com",
      roles: ["producer"],
      purposes: [
        { name: "Analytics", color: "info" },
        { name: "Fraud prevention", color: "alert" },
        { name: "Customer support", color: "default" },
      ],
      annotation_percent: 85,
      health: HealthStatus.HEALTHY,
      stewards: [{ initials: "JG", name: "Jack Gale" }],
      group: "Customer platform",
      integrations: [
        {
          name: "BigQuery — DSR Automation",
          type: "BigQuery",
          accessLevel: "Read/Write",
          status: "active",
          lastTested: "2026-03-26T07:00:00Z",
          enabledActions: ["DSR access", "DSR erasure"],
        },
        {
          name: "BigQuery — Monitoring",
          type: "BigQuery",
          accessLevel: "Read",
          status: "active",
          lastTested: "2026-03-25T14:00:00Z",
          enabledActions: ["monitoring", "classification"],
        },
        {
          name: "BigQuery — Consent",
          type: "BigQuery",
          accessLevel: "Read/Write",
          status: "active",
          lastTested: "2026-03-24T10:00:00Z",
          enabledActions: ["consent"],
        },
        {
          name: "Fivetran — BigQuery Sync",
          type: "Fivetran",
          accessLevel: "Read",
          status: "active",
          lastTested: "2026-03-23T08:00:00Z",
          enabledActions: ["monitoring"],
        },
      ],
      monitors: [
        {
          name: "Identity schema scan",
          frequency: "Weekly",
          status: "completed",
          lastRun: "2026-03-25T06:00:00Z",
          resourceCount: 26,
        },
        {
          name: "Token usage monitor",
          frequency: "Daily",
          status: "completed",
          lastRun: "2026-03-26T02:00:00Z",
          resourceCount: 8,
        },
      ],
      relationships: [
        {
          systemName: "Segment",
          systemKey: "segment",
          role: "producer",
          declaredUse: "Analytics",
          authorizedUses: ["Analytics"],
          hasViolation: false,
        },
        {
          systemName: "Fraud Detection Service",
          systemKey: "fraud_detection",
          role: "producer",
          declaredUse: "Fraud prevention",
          authorizedUses: ["Fraud prevention"],
          hasViolation: false,
        },
        {
          systemName: "Internal API",
          systemKey: "internal_api",
          role: "producer",
          declaredUse: "Customer support",
          authorizedUses: ["Customer support", "Analytics"],
          hasViolation: false,
        },
      ],
      classification: {
        approved: 612,
        pending: 486,
        unreviewed: 538,
        categories: [
          { name: "Identity data", fieldCount: 420, approvedPercent: 82 },
          {
            name: "Authentication tokens",
            fieldCount: 286,
            approvedPercent: 54,
          },
          { name: "Session metadata", fieldCount: 196, approvedPercent: 41 },
          { name: "Authorization rules", fieldCount: 142, approvedPercent: 68 },
        ],
      },
      datasets: [
        {
          name: "bq_user_profiles",
          key: "bq_user_profiles",
          collectionCount: 8,
          fieldCount: 1842,
          createdAt: "2025-11-01",
          category: "Identity data",
          dsrScope: ["access", "erasure"],
          dataCategories: [
            "user.name",
            "user.contact.email",
            "user.contact.phone_number",
            "user.unique_id",
          ],
          status: "approved",
        },
        {
          name: "bq_analytics_events",
          key: "bq_analytics_events",
          collectionCount: 14,
          fieldCount: 956,
          createdAt: "2025-12-15",
          category: "Behavioral data",
          dsrScope: ["access"],
          dataCategories: [
            "user.behavior",
            "user.device.ip_address",
            "system.operations",
          ],
          status: "approved",
        },
        {
          name: "bq_audit_logs",
          key: "bq_audit_logs",
          collectionCount: 5,
          fieldCount: 2314,
          createdAt: "2026-01-10",
          category: "Audit logs",
          dsrScope: [],
          dataCategories: ["system.operations"],
          status: "approved",
        },
        {
          name: "bq_payment_transactions",
          key: "bq_payment_transactions",
          collectionCount: 6,
          fieldCount: 428,
          createdAt: "2026-02-01",
          category: "Financial data",
          dsrScope: ["access", "erasure"],
          dataCategories: [
            "user.financial",
            "user.payment",
            "user.contact.email",
          ],
          status: "pending",
        },
        {
          name: "bq_marketing_attribution",
          key: "bq_marketing_attribution",
          collectionCount: 4,
          fieldCount: 186,
          createdAt: "2026-02-15",
          category: "Marketing data",
          dsrScope: ["access", "erasure"],
          dataCategories: [
            "user.behavior",
            "user.device.cookie_id",
            "user.contact.email",
          ],
          status: "approved",
        },
        {
          name: "bq_support_tickets",
          key: "bq_support_tickets",
          collectionCount: 3,
          fieldCount: 312,
          createdAt: "2026-03-01",
          category: "Support data",
          dsrScope: ["access"],
          dataCategories: ["user.contact.email", "user.name", "user.content"],
          status: "draft",
        },
      ],
      privacyRequests: {
        open: 147,
        closed: 3842,
        avgAccessDays: 1.8,
        avgErasureDays: 3.2,
        dsarEnabled: true,
        statusBreakdown: {
          pending: 23,
          inProgress: 84,
          approved: 40,
          complete: 3842,
          denied: 12,
          error: 3,
        },
      },
      history: [
        {
          timestamp: "2026-03-26T08:00:00Z",
          action: "Monitor completed",
          category: "integration",
          user: "System",
          detail: "Identity schema scan completed — 26 resources found",
        },
        {
          timestamp: "2026-03-25T16:45:00Z",
          action: "Label changed",
          category: "classification",
          user: "Jack Gale",
          detail: "Reclassified user.phone_number from contact to PII",
          fieldName: "user.phone_number",
          oldValue: "Contact info",
          newValue: "PII — Phone number",
          reason: "Field contains direct personal identifier per GDPR Art. 4",
        },
        {
          timestamp: "2026-03-25T16:30:00Z",
          action: "Classification approved",
          category: "classification",
          user: "Jack Gale",
          detail: "Approved classification for user.email",
          fieldName: "user.email",
          newValue: "PII — Email address",
        },
        {
          timestamp: "2026-03-25T16:20:00Z",
          action: "Classification approved",
          category: "classification",
          user: "Jack Gale",
          detail: "Approved classification for user.name",
          fieldName: "user.name",
          newValue: "PII — Full name",
        },
        {
          timestamp: "2026-03-25T16:10:00Z",
          action: "Field reviewed",
          category: "classification",
          user: "Jack Gale",
          detail: "Reviewed user.last_login — marked as non-PII",
          fieldName: "user.last_login",
          newValue: "System metadata",
          reason: "Timestamp only, no personal data",
        },
        {
          timestamp: "2026-03-25T14:30:00Z",
          action: "Integration tested",
          category: "integration",
          user: "Jack Gale",
          detail: "BigQuery Storage API — connection test passed",
        },
        {
          timestamp: "2026-03-24T11:00:00Z",
          action: "Label changed",
          category: "classification",
          user: "Anna Kim",
          detail: "Changed user.ip_address from system data to PII",
          fieldName: "user.ip_address",
          oldValue: "System data",
          newValue: "PII — IP address",
          reason: "IP addresses are personal data under GDPR recital 30",
        },
        {
          timestamp: "2026-03-24T10:00:00Z",
          action: "Classification approved",
          category: "classification",
          user: "Jack Gale",
          detail: "Bulk approved 18 identity fields",
          fieldName: "user.* (18 fields)",
          newValue: "Identity data",
        },
        {
          timestamp: "2026-03-23T15:00:00Z",
          action: "Category assigned",
          category: "classification",
          user: "Anna Kim",
          detail: "Assigned 'Identity data' category to Auth0 dataset",
          fieldName: "auth0_identity.*",
          newValue: "Identity data",
          reason: "All fields relate to user identity and authentication",
        },
        {
          timestamp: "2026-03-22T09:00:00Z",
          action: "Purpose added",
          category: "purpose",
          user: "Jack Gale",
          detail: "Added 'Customer support' purpose to Auth0",
        },
        {
          timestamp: "2026-03-21T14:00:00Z",
          action: "Purpose added",
          category: "purpose",
          user: "Jack Gale",
          detail: "Added 'Fraud prevention' purpose to Auth0",
        },
        {
          timestamp: "2026-03-20T11:00:00Z",
          action: "Steward assigned",
          category: "steward",
          user: "Anna Kim",
          detail: "Jack Gale assigned as data steward",
        },
        {
          timestamp: "2026-03-19T10:00:00Z",
          action: "Integration configured",
          category: "integration",
          user: "Jack Gale",
          detail:
            "BigQuery Read/Write configured with access and erasure scopes",
        },
        {
          timestamp: "2026-03-18T16:00:00Z",
          action: "System registered",
          category: "system",
          user: "System",
          detail: "Auth0 added to system inventory via API discovery",
        },
        {
          timestamp: "2026-03-15T09:00:00Z",
          action: "Integration added",
          category: "integration",
          user: "Jack Gale",
          detail: "BigQuery Storage API configured with read access",
        },
        {
          timestamp: "2026-03-12T14:00:00Z",
          action: "Monitor created",
          category: "integration",
          user: "Anna Kim",
          detail: "Identity schema scan monitor set to weekly frequency",
        },
      ],
      assets: [
        {
          id: "a1",
          name: "auth0_session",
          assetType: "Cookie",
          domain: "auth0.com",
          dataUses: ["functional"],
          duration: "24 hours",
          description: "Session cookie for authenticated users",
          consentStatus: "opt_in",
        },
        {
          id: "a2",
          name: "auth0_csrf",
          assetType: "Cookie",
          domain: "auth0.com",
          dataUses: ["functional", "essential"],
          duration: "1 hour",
          description: "CSRF protection token",
          consentStatus: "opt_out",
        },
        {
          id: "a3",
          name: "_auth0_consent",
          assetType: "Cookie",
          domain: "auth0.com",
          dataUses: ["functional"],
          duration: "1 year",
          description: "Stores user consent preferences",
          consentStatus: "opt_in",
        },
        {
          id: "a4",
          name: "auth0-analytics.js",
          assetType: "Javascript tag",
          domain: "cdn.auth0.com",
          dataUses: ["analytics"],
          baseUrl: "https://cdn.auth0.com/js/analytics.js",
          description: "Auth0 usage analytics tracker",
          detectedOn: ["/login", "/signup", "/dashboard"],
          consentStatus: "opt_in",
        },
        {
          id: "a5",
          name: "consent-manager.js",
          assetType: "Javascript tag",
          domain: "cdn.auth0.com",
          dataUses: ["functional", "essential"],
          baseUrl: "https://cdn.auth0.com/js/consent.js",
          description: "Consent management script",
          detectedOn: ["/login", "/signup"],
        },
        {
          id: "a6",
          name: "auth0-retarget",
          assetType: "Image",
          domain: "pixel.auth0.com",
          dataUses: ["marketing"],
          baseUrl: "https://pixel.auth0.com/t.gif",
          description: "Retargeting pixel for marketing campaigns",
          detectedOn: ["/pricing"],
          consentStatus: "opt_in",
        },
        {
          id: "a7",
          name: "social-login-frame",
          assetType: "iFrame",
          domain: "login.auth0.com",
          dataUses: ["functional", "third_party_sharing"],
          baseUrl: "https://login.auth0.com/social",
          description: "Social login provider iframe (Google, GitHub)",
          detectedOn: ["/login"],
        },
        {
          id: "a8",
          name: "telemetry-beacon",
          assetType: "Browser Request",
          domain: "telemetry.auth0.com",
          dataUses: ["analytics", "functional"],
          baseUrl: "https://telemetry.auth0.com/v1/track",
          description: "Performance and error telemetry",
          detectedOn: ["/login", "/signup", "/dashboard", "/settings"],
        },
      ],
    },
  ),

  s(
    "segment",
    "Segment",
    "CDP",
    "Customer data platform for event collection and routing.",
    {
      department: "Engineering",
      logoDomain: "segment.com",
      roles: ["producer", "consumer"],
      purposes: [
        { name: "Analytics", color: "info" },
        { name: "Marketing", color: "warning" },
        { name: "Customer support", color: "default" },
        { name: "Fraud prevention", color: "alert" },
        { name: "Finance", color: "success" },
      ],
      annotation_percent: 75,
      health: HealthStatus.ISSUES,
      issue_count: 1,
      issues: [
        {
          title: "DSAR not ready",
          severity: "warning",
          resolveHref: "#integrations",
        },
      ],
      stewards: [{ initials: "RS", name: "Rachel Smith" }],
      group: "Customer platform",
    },
  ),

  // --- HR ---
  s(
    "workday",
    "Workday",
    "HRIS",
    "Human capital management for HR, payroll, and talent.",
    {
      department: "HR",
      logoDomain: "workday.com",
      responsibility: "Controller",
      roles: ["producer", "consumer"],
      purposes: [
        { name: "HR", color: "default" },
        { name: "Finance", color: "success" },
        { name: "Analytics", color: "info" },
        { name: "Customer support", color: "default" },
      ],
      annotation_percent: 90,
      health: HealthStatus.HEALTHY,
      stewards: [{ initials: "DP", name: "Diana Park" }],
      group: "HR & recruiting",
    },
  ),

  s(
    "greenhouse",
    "Greenhouse",
    "HRIS",
    "Applicant tracking and recruiting platform.",
    {
      department: "HR",
      logoDomain: "greenhouse.io",
      roles: ["consumer"],
      purposes: [
        { name: "HR", color: "default" },
        { name: "Analytics", color: "info" },
        { name: "Finance", color: "success" },
      ],
      annotation_percent: 50,
      health: HealthStatus.ISSUES,
      issue_count: 1,
      issues: [
        {
          title: "DSAR not ready",
          severity: "warning",
          resolveHref: "#integrations",
        },
      ],
      stewards: [{ initials: "DP", name: "Diana Park" }],
      group: "HR & recruiting",
    },
  ),

  s(
    "bamboohr",
    "BambooHR",
    "HRIS",
    "HR management software for small and mid-size businesses.",
    {
      department: "HR",
      logoDomain: "bamboohr.com",
      roles: ["consumer"],
      purposes: [
        { name: "HR", color: "default" },
        { name: "Finance", color: "success" },
        { name: "Customer support", color: "default" },
        { name: "Analytics", color: "info" },
        { name: "Marketing", color: "warning" },
      ],
      annotation_percent: 40,
      health: HealthStatus.ISSUES,
      issue_count: 2,
      issues: [
        {
          title: "No integration linked",
          severity: "warning",
          resolveHref: "#integrations",
        },
        {
          title: "High % unreviewed fields",
          severity: "warning",
          resolveHref: "#assets",
        },
      ],
      stewards: [],
      group: "HR & recruiting",
    },
  ),

  s(
    "slack",
    "Slack",
    "Messaging",
    "Team communication and collaboration platform.",
    {
      department: "IT",
      logoDomain: "slack.com",
      roles: ["consumer"],
      purposes: [
        { name: "HR", color: "default" },
        { name: "Analytics", color: "info" },
        { name: "Marketing", color: "warning" },
      ],
      annotation_percent: 20,
      health: HealthStatus.ISSUES,
      issue_count: 3,
      issues: [
        {
          title: "No data steward assigned",
          severity: "warning",
          resolveHref: "#information",
        },
        {
          title: "No integration linked",
          severity: "warning",
          resolveHref: "#integrations",
        },
        {
          title: "Needs classification",
          severity: "warning",
          resolveHref: "#assets",
        },
      ],
      stewards: [],
    },
  ),

  // --- Ungrouped ---
  s(
    "internal_api",
    "Internal API",
    "Internal service",
    "Core internal API serving frontend applications.",
    {
      department: "Engineering",
      roles: ["producer"],
      purposes: [
        { name: "Analytics", color: "info" },
        { name: "Customer support", color: "default" },
        { name: "Finance", color: "success" },
      ],
      annotation_percent: 68,
      health: HealthStatus.ISSUES,
      issue_count: 1,
      issues: [
        {
          title: "No data steward assigned",
          severity: "warning",
          resolveHref: "#information",
        },
      ],
      stewards: [],
    },
  ),

  s(
    "legacy_crm",
    "Legacy CRM",
    "CRM",
    "Legacy customer relationship management system being decommissioned.",
    {
      department: "Sales",
      roles: ["producer"],
      purposes: [],
      annotation_percent: 15,
      health: HealthStatus.ISSUES,

      issue_count: 3,
      issues: [
        {
          title: "No data steward assigned",
          severity: "warning",
          resolveHref: "#information",
        },
        {
          title: "No integration linked",
          severity: "warning",
          resolveHref: "#integrations",
        },
        {
          title: "Needs classification",
          severity: "warning",
          resolveHref: "#assets",
        },
      ],
      stewards: [],
    },
  ),

  s(
    "test_environment",
    "Test Environment",
    "Internal service",
    "Staging and testing environment for QA.",
    {
      department: "Engineering",
      roles: ["consumer"],
      purposes: [],
      annotation_percent: 0,
      health: HealthStatus.ISSUES,
      issue_count: 3,
      issues: [
        {
          title: "No data steward assigned",
          severity: "warning",
          resolveHref: "#information",
        },
        {
          title: "Needs classification",
          severity: "warning",
          resolveHref: "#assets",
        },
        {
          title: "No integration linked",
          severity: "warning",
          resolveHref: "#integrations",
        },
      ],
      stewards: [],
    },
  ),
];
