import type {
  ActionTab,
  AlertData,
  DsrStatusData,
  GovernanceData,
  SparklineCardData,
  SummaryData,
  SystemCoverageData,
} from "./types";

export const MOCK_SUMMARY: SummaryData = {
  score: 83,
  trend: 7.2,
  dsrsPending: 13,
  dsrsOverdue: 1,
  systemsCount: 16,
  violations: 0,
};

export const MOCK_ALERT: AlertData = {
  message: "4 privacy requests are overdue and require immediate attention.",
  count: 4,
  actions: [
    { label: "Review overdue requests", href: "/privacy-requests?status=overdue" },
    { label: "Review classifications", href: "/data-discovery/action-center" },
    { label: "Assign stewards (16 systems)", href: "/systems" },
  ],
};

export const MOCK_GOVERNANCE: GovernanceData = {
  score: 83,
  trend: 7.2,
  dimensions: [
    { subject: "Coverage", value: 90, previous: 72, status: "success" },
    { subject: "Classification\nHealth", value: 76, previous: 58, status: "warning" },
    { subject: "DSR\nCompliance", value: 85, previous: 80, status: "success" },
    { subject: "Consent\nAlignment", value: 78, previous: 65, status: "warning" },
  ],
};

export const MOCK_PRIORITY_ACTIONS: ActionTab[] = [
  {
    key: "act-now",
    label: "Act now",
    count: 8,
    items: [
      {
        id: "1",
        title: "Erasure request overdue — SLA breach",
        severity: "error",
        category: "DSR",
        subject: "jane.doe@example.com",
        requestType: "Erasure",
        daysRemaining: -2,
        submitted: "Mar 11",
        status: "Requires Input",
      },
      {
        id: "2",
        title: "Access request pending manual review",
        severity: "error",
        category: "DSR",
        subject: "user-8291@acme.co",
        requestType: "Access",
        daysRemaining: 1,
        submitted: "Mar 18",
        status: "Pending Review",
      },
      {
        id: "3",
        title: "Access request awaiting approval",
        severity: "warning",
        category: "DSR",
        subject: "m.chen@partner.io",
        requestType: "Access",
        daysRemaining: 4,
        submitted: "Mar 20",
        status: "Awaiting Approval",
      },
      {
        id: "16",
        title: "Erasure request — identity unverified",
        severity: "error",
        category: "DSR",
        subject: "anon-4417",
        requestType: "Erasure",
        daysRemaining: 0,
        submitted: "Mar 14",
        status: "Identity Pending",
      },
      {
        id: "17",
        title: "Unclassified system detected in production",
        severity: "error",
        category: "Systems",
        subject: "prod-db-07.internal",
        submitted: "Mar 22",
        status: "Unclassified",
      },
      {
        id: "18",
        title: "Consent banner misconfigured on checkout",
        severity: "warning",
        category: "Consent",
        subject: "checkout.example.com",
        submitted: "Mar 19",
        status: "Misconfigured",
      },
      {
        id: "19",
        title: "Data map drift — 3 new connections found",
        severity: "warning",
        category: "Data Map",
        subject: "Snowflake → BigQuery",
        submitted: "Mar 21",
        status: "Needs Review",
      },
      {
        id: "20",
        title: "Access request pending approval",
        severity: "warning",
        category: "DSR",
        subject: "t.nguyen@example.com",
        requestType: "Access",
        daysRemaining: 2,
        submitted: "Mar 22",
        status: "Awaiting Approval",
      },
    ],
  },
  {
    key: "scheduled",
    label: "Scheduled",
    count: 10,
    items: [
      {
        id: "4",
        title: "Quarterly consent audit",
        severity: "info",
        category: "Consent",
        submitted: "Due Apr 1",
        status: "Scheduled",
      },
      {
        id: "5",
        title: "System classification review",
        severity: "info",
        category: "Systems",
        subject: "16 systems",
        submitted: "Due Apr 5",
        status: "Scheduled",
      },
      {
        id: "6",
        title: "Vendor data map refresh",
        severity: "info",
        category: "Data Map",
        subject: "3 vendors",
        submitted: "Due Apr 10",
        status: "Scheduled",
      },
      {
        id: "10",
        title: "Re-certify data processing agreements",
        severity: "info",
        category: "Consent",
        subject: "5 DPAs",
        submitted: "Due Apr 15",
        status: "Scheduled",
      },
      {
        id: "11",
        title: "Update privacy policy for new jurisdictions",
        severity: "warning",
        category: "Consent",
        subject: "BR, KR, TH",
        submitted: "Due Mar 31",
        status: "Approaching",
      },
      {
        id: "12",
        title: "Run monthly DSR compliance report",
        severity: "info",
        category: "DSR",
        submitted: "Due Apr 1",
        status: "Scheduled",
      },
    ],
  },
  {
    key: "when-ready",
    label: "When ready",
    count: 12,
    items: [
      {
        id: "7",
        title: "Update cookie consent banners",
        severity: "info",
        category: "Consent",
        subject: "3 properties",
        status: "Backlog",
      },
      {
        id: "8",
        title: "Review stale system connections",
        severity: "info",
        category: "Systems",
        subject: "4 connections inactive 90d+",
        status: "Backlog",
      },
      {
        id: "9",
        title: "Archive completed DSR records",
        severity: "info",
        category: "DSR",
        subject: "142 records",
        status: "Backlog",
      },
      {
        id: "13",
        title: "Audit vendor sub-processor list",
        severity: "info",
        category: "Systems",
        subject: "8 vendors",
        status: "Backlog",
      },
      {
        id: "14",
        title: "Review data retention schedules",
        severity: "info",
        category: "Data Map",
        subject: "6 policies",
        status: "Backlog",
      },
      {
        id: "15",
        title: "Consolidate duplicate system entries",
        severity: "warning",
        category: "Systems",
        subject: "3 duplicates",
        status: "Needs Review",
      },
    ],
  },
];

export const MOCK_SPARKLINE_CARDS: SparklineCardData[] = [
  {
    title: "Governance posture",
    value: 83,
    unit: "",
    trend: "+15",
    trendDirection: "up",
    data: [52, 55, 58, 63, 60, 68, 65, 72, 70, 75, 78, 83],
  },
  {
    title: "DSR volume",
    value: 50,
    unit: "",
    trend: "+31",
    trendDirection: "up",
    data: [12, 15, 18, 16, 22, 25, 28, 31, 35, 38, 42, 50],
  },
  {
    title: "System coverage",
    value: 63,
    unit: "%",
    trend: "+3%",
    trendDirection: "up",
    data: [45, 47, 48, 50, 52, 53, 55, 57, 58, 60, 61, 63],
  },
  {
    title: "Classification health",
    value: 76,
    unit: "%",
    trend: "+19%",
    trendDirection: "up",
    data: [40, 42, 45, 48, 52, 55, 58, 62, 65, 67, 72, 76],
  },
];

export const MOCK_SYSTEM_COVERAGE: SystemCoverageData = {
  percent: 62.5,
  total: 16,
  breakdown: [
    { label: "Fully classified", value: 10, color: "#5a9a68" },
    { label: "Partially classified", value: 4, color: "#e59d47" },
    { label: "Unclassified", value: 0, color: "#d9534f" },
    { label: "Without steward", value: 16, color: "#cecac2" },
  ],
  monitors: [
    { name: "Okta SSO", systems: 6, classified: 5 },
    { name: "AWS IAM", systems: 4, classified: 3 },
    { name: "Snowflake", systems: 3, classified: 3 },
    { name: "BigQuery", systems: 3, classified: 1 },
  ],
  dataStores: { total: 24, approved: 18, pending: 6 },
};

export const MOCK_DSR_STATUS: DsrStatusData = {
  active: 26,
  breakdown: [
    { label: "In Progress", value: 8, color: "#5a9a68" },
    { label: "Pending Action", value: 9, color: "#cecac2" },
    { label: "Awaiting Approval", value: 4, color: "#e59d47" },
  ],
  slaBars: [
    {
      label: "Access →",
      segments: [
        { label: "On track", value: 10, color: "#5a9a68" },
        { label: "Approaching", value: 3, color: "#e59d47" },
        { label: "Overdue", value: 2, color: "#d9534f" },
      ],
    },
    {
      label: "Erasure →",
      segments: [
        { label: "On track", value: 8, color: "#5a9a68" },
        { label: "Approaching", value: 1, color: "#e59d47" },
        { label: "Overdue", value: 2, color: "#d9534f" },
      ],
    },
  ],
  slaLegend: [
    { label: "On track", value: 0, color: "#5a9a68" },
    { label: "Approaching", value: 0, color: "#e59d47" },
    { label: "Overdue", value: 0, color: "#d9534f" },
  ],
};
