import { createSelector } from "@reduxjs/toolkit";
import { createApi, fetchBaseQuery } from "@reduxjs/toolkit/query/react";

<<<<<<< HEAD:clients/admin-ui/src/features/common/plus.slice.ts
import { Dataset } from "~/types/api";
=======
import {
  selectActiveCollection,
  selectActiveDatasetFidesKey,
  selectActiveField,
} from "~/features/dataset/dataset.slice";
import { Generate } from "~/types/api";
>>>>>>> unified-fides-2:clients/ctl/admin-ui/src/features/common/plus.slice.ts

interface HealthResponse {
  core_fidesctl_version: string;
  status: "healthy";
}

/**
 * These interfaces will be replaced with the OpenAPI generated models when the backend is ready.
 */
<<<<<<< HEAD:clients/admin-ui/src/features/common/plus.slice.ts
interface ClassificationRequest {
  // Key of the dataset. Should this have "dataset_" prefix?
  fides_key: string;
}
interface ClassificationResponse {
  // Classifications probably have a UID not a key
  id: string;
  // Dataset key
  fides_key: string;
  // Probably will become an enum.
  status: "processing" | "review" | "classified";
  // Assuming it's just the fields generated by classify. What's a good name?
  // (This is blank while in the "processing" status.
  classification?: Pick<Dataset, "data_categories" | "collections">;
=======
export interface ClassifyInstanceRequest {
  organization_key: string;
  // Array of objects because we might need to match by more DB info than just the fides_key.
  datasets: Array<{
    fides_key: string;
  }>;
  generate: Generate;
}

// TODO(ssangervasi): Resolves the assumptions commented below when the API is done.
// https://github.com/ethyca/fidesctl-plus/pull/106#pullrequestreview-1112775197
export interface Classification {
  label: string;
  score: number;
  aggregated_score: number;
  classification_paradigm: string;
}
export interface ClassifyField {
  name: string;
  classifications: Classification[];
}
export interface ClassifyCollection {
  name: string;
  fields: ClassifyField[];
}
export interface ClassifyDataset {
  fides_key: string;
  // Assuming these are empty while the instance is in the "processing" status.
  collections: ClassifyCollection[];
}
export enum ClassifyStatusEnum {
  CREATED = "Created",
  IN_WORK = "In Work",
  COMPLETE = "Complete",
  FAILED = "Failed",
  // Name TBD by the backend.
  REVIEWED = "Reviewed",
}
export interface ClassifyInstance {
  // ClassifyInstances probably have a UID not a key
  id: string;
  status: ClassifyStatusEnum;
  datasets: ClassifyDataset[];
>>>>>>> unified-fides-2:clients/ctl/admin-ui/src/features/common/plus.slice.ts
}

export const plusApi = createApi({
  reducerPath: "plusApi",
  baseQuery: fetchBaseQuery({
    baseUrl: `${process.env.NEXT_PUBLIC_FIDESCTL_API}/plus`,
  }),
  tagTypes: ["Plus"],
  endpoints: (build) => ({
    getHealth: build.query<HealthResponse, void>({
      query: () => "health",
    }),
    /**
     * Fidescls endpoints:
     */
<<<<<<< HEAD:clients/admin-ui/src/features/common/plus.slice.ts
    createClassification: build.mutation<
      ClassificationResponse,
      ClassificationRequest
    >({
      query: (body) => ({
        // Or is this "classify/"?
        url: `classification/`,
=======
    createClassifyInstance: build.mutation<
      ClassifyInstance,
      ClassifyInstanceRequest
    >({
      query: (body) => ({
        url: `classify/`,
>>>>>>> unified-fides-2:clients/ctl/admin-ui/src/features/common/plus.slice.ts
        method: "POST",
        body,
      }),
    }),
<<<<<<< HEAD:clients/admin-ui/src/features/common/plus.slice.ts
    getAllClassifications: build.query<ClassificationResponse[], void>({
      query: () => `classification/`,
=======
    getAllClassifyInstances: build.query<ClassifyInstance[], void>({
      query: () => `classify/`,
>>>>>>> unified-fides-2:clients/ctl/admin-ui/src/features/common/plus.slice.ts
    }),
  }),
});

export const {
  useGetHealthQuery,
<<<<<<< HEAD:clients/admin-ui/src/features/common/plus.slice.ts
  useCreateClassificationMutation,
  useGetAllClassificationsQuery,
=======
  useCreateClassifyInstanceMutation,
  useGetAllClassifyInstancesQuery,
>>>>>>> unified-fides-2:clients/ctl/admin-ui/src/features/common/plus.slice.ts
} = plusApi;

export const useHasPlus = () => {
  const { isSuccess: hasPlus } = useGetHealthQuery();
  return hasPlus;
};

<<<<<<< HEAD:clients/admin-ui/src/features/common/plus.slice.ts
const emptyClassifications: ClassificationResponse[] = [];
const selectClassificationsMap = createSelector(
  ({ data }: { data?: ClassificationResponse[] }) =>
    data ?? emptyClassifications,
  (dataCategories) => ({
    map: new Map(dataCategories.map((c) => [c.fides_key, c])),
  })
);

/**
 * Convenience hook for looking up a Classification by Dataset key.
 */
export const useClassificationsMap = (): Map<
  string,
  ClassificationResponse
> => {
  const hasPlus = useHasPlus();
  const { map } = useGetAllClassificationsQuery(undefined, {
    skip: !hasPlus,
    selectFromResult: selectClassificationsMap,
  });
  return map;
};
=======
const emptyClassifyInstances: ClassifyInstance[] = [];
const selectClassifyInstancesMap = createSelector(
  ({ data }: { data?: ClassifyInstance[] }) => data ?? emptyClassifyInstances,
  (classifyInstances) => {
    const map = new Map();
    classifyInstances.forEach((ci) => {
      ci.datasets?.forEach((ds) => {
        map.set(ds.fides_key, ci);
      });
    });
    return {
      map,
    };
  }
);

/**
 * Convenience hook for looking up a ClassifyInstance by Dataset key.
 */
export const useClassifyInstancesMap = (): Map<string, ClassifyInstance> => {
  const hasPlus = useHasPlus();
  const { map } = useGetAllClassifyInstancesQuery(undefined, {
    skip: !hasPlus,
    selectFromResult: selectClassifyInstancesMap,
  });
  return map;
};

/**
 * ClassifyInstance selectors that parallel the dataset's structure. These used the
 * cached getAllClassifyInstances response state, as well as the "active" dataset according
 * to the dataset feature's state.
 */
export const selectActiveClassifyDataset = createSelector(
  [
    plusApi.endpoints.getAllClassifyInstances.select(),
    selectActiveDatasetFidesKey,
  ],
  ({ data: instances }, fidesKey) => {
    let classifyDataset: ClassifyDataset | undefined;
    instances?.find((ci) =>
      ci.datasets?.find((ds) => {
        if (ds.fides_key === fidesKey) {
          classifyDataset = ds;
          return true;
        }
        return false;
      })
    );
    return classifyDataset;
  }
);

const emptyCollectionMap: Map<string, ClassifyCollection> = new Map();
export const selectClassifyInstanceCollectionMap = createSelector(
  selectActiveClassifyDataset,
  (classifyInstance) =>
    classifyInstance?.collections
      ? new Map(classifyInstance.collections.map((c) => [c.name, c]))
      : emptyCollectionMap
);
export const selectClassifyInstanceCollection = createSelector(
  [selectClassifyInstanceCollectionMap, selectActiveCollection],
  (collectionMap, active) =>
    active ? collectionMap.get(active.name) : undefined
);

const emptyFieldMap: Map<string, ClassifyField> = new Map();
export const selectClassifyInstanceFieldMap = createSelector(
  selectClassifyInstanceCollection,
  (collection) =>
    collection?.fields
      ? new Map(collection.fields.map((f) => [f.name, f]))
      : emptyFieldMap
);
/**
 * Note that this selects the field that is currently active in the editor. Fields that are shown in
 * the table are looked up by their name using selectClassifyInstanceFieldMap.
 */
export const selectClassifyInstanceField = createSelector(
  [selectClassifyInstanceFieldMap, selectActiveField],
  (fieldMap, active) => (active ? fieldMap.get(active.name) : undefined)
);
>>>>>>> unified-fides-2:clients/ctl/admin-ui/src/features/common/plus.slice.ts
