queues {
  fides-fides { defaultVisibilityTimeout = 30 seconds }
  fides-fides.dsr { defaultVisibilityTimeout = 30 seconds }
  fides-fidesops.messaging { defaultVisibilityTimeout = 30 seconds }
  fides-fides.privacy_preferences { defaultVisibilityTimeout = 30 seconds }
  fides-fides.privacy_request_exports { defaultVisibilityTimeout = 30 seconds }
  fides-fides.privacy_request_ingestion { defaultVisibilityTimeout = 30 seconds }
  fides-fidesplus.consent_webhooks { defaultVisibilityTimeout = 30 seconds }
  fides-fidesplus.discovery_monitors_detection { defaultVisibilityTimeout = 30 seconds }
  fides-fidesplus.discovery_monitors_classification { defaultVisibilityTimeout = 30 seconds }
  fides-fidesplus.discovery_monitors_promotion { defaultVisibilityTimeout = 30 seconds }
}
