include classpath("application.conf")

node-address {
    protocol = http
    host = localhost
    port = 9324
    context-path = ""
}

rest-sqs {
    enabled = true
    bind-port = 9324
    bind-hostname = "0.0.0.0"
    sqs-limits = strict
}

queues {
  ethyca-fides { defaultVisibilityTimeout = 30 seconds }
  ethyca-fides-dsr { defaultVisibilityTimeout = 30 seconds }
  ethyca-fidesops-messaging { defaultVisibilityTimeout = 30 seconds }
  ethyca-fides-privacy_preferences { defaultVisibilityTimeout = 30 seconds }
  ethyca-fides-privacy_request_exports { defaultVisibilityTimeout = 30 seconds }
  ethyca-fides-privacy_request_ingestion { defaultVisibilityTimeout = 30 seconds }
  ethyca-fidesplus-consent_webhooks { defaultVisibilityTimeout = 30 seconds }
  ethyca-fidesplus-discovery_monitors_detection { defaultVisibilityTimeout = 30 seconds }
  ethyca-fidesplus-discovery_monitors_classification { defaultVisibilityTimeout = 30 seconds }
  ethyca-fidesplus-discovery_monitors_promotion { defaultVisibilityTimeout = 30 seconds }
}
