/**
 * Privacy Assessments Constants
 *
 * Centralized constants and label mappings for privacy assessments.
 */

import { AssessmentStatus, RiskLevel } from "./types";

// =============================================================================
// Status Labels
// =============================================================================

// Using Record<string, string> to handle the wider string type from autogenerated API
// but AssessmentStatus union is still available for type narrowing where needed
export const ASSESSMENT_STATUS_LABELS: Record<string, string> = {
  in_progress: "In progress",
  completed: "Completed",
  outdated: "Out of date",
} satisfies Record<AssessmentStatus, string>;

// =============================================================================
// Risk Level Labels
// =============================================================================

// Using Record<string, string> to handle the wider string type from autogenerated API
// but RiskLevel union is still available for type narrowing where needed
export const RISK_LEVEL_LABELS: Record<string, string> = {
  high: "High",
  medium: "Med",
  low: "Low",
} satisfies Record<RiskLevel, string>;
