"""
Public endpoint decorator and default auth policy enforcement.

All API endpoints are required to either:
  1. Have an explicit ``Security(...)`` dependency (route-level or function parameter), OR
  2. Be decorated with ``@public_endpoint`` to mark them as intentionally public.

If a developer adds a new endpoint without either, the application will fail to start.

Public endpoints that are added must also be documented at:
https://www.ethyca.com/docs/platform/configuration/security-practices#public-internet----fides-webserver
"""

import inspect
from typing import Callable, TypeVar

from fastapi.params import Depends, Security
from fastapi.routing import APIRoute
from loguru import logger

F = TypeVar("F", bound=Callable)


def public_endpoint(func: F) -> F:
    """Mark an API endpoint as intentionally public (no authentication required).

    Usage::

        @router.get("/my-public-route")
        @public_endpoint
        def my_public_handler():
            ...

    Any endpoint without a ``Security`` dependency that is NOT decorated with
    ``@public_endpoint`` will cause the application to fail at startup.
    """
    func._public_endpoint = True  # type: ignore[attr-defined]
    return func


def _is_marked_public(route: APIRoute) -> bool:
    """Return True if the route's endpoint function is decorated with @public_endpoint."""
    func = route.endpoint
    # Walk through any decorator wrappers that used functools.wraps
    while func is not None:
        if getattr(func, "_public_endpoint", False):
            return True
        func = getattr(func, "__wrapped__", None)
    return False


def _has_auth_dependency(route: APIRoute) -> bool:
    """Return True if the route enforces authentication.

    Checks two places where auth can be declared:
      1. Route-level ``dependencies=[Security(...)]``
      2. Endpoint function parameters with ``Security(...)`` defaults
         (including one level of ``Depends`` nesting)
    """
    # 1. Route-level dependencies
    for dep in route.dependencies:
        if isinstance(dep, Security):
            return True

    # 2. Endpoint function signature
    sig = inspect.signature(route.endpoint)
    for param in sig.parameters.values():
        if param.default is inspect.Parameter.empty:
            continue
        if isinstance(param.default, Security):
            return True
        # Some endpoints use Depends(func) where func itself takes a
        # Security(oauth2_scheme) parameter - check one level deep.
        if isinstance(param.default, Depends):
            inner = getattr(param.default, "dependency", None)
            if callable(inner):
                try:
                    inner_sig = inspect.signature(inner)
                except (ValueError, TypeError):
                    continue
                for ip in inner_sig.parameters.values():
                    if ip.default is not inspect.Parameter.empty and isinstance(
                        ip.default, Security
                    ):
                        return True
    return False


def validate_endpoint_auth_policy(app) -> None:
    """Validate that every API endpoint has auth or is explicitly marked public.

    Call this after all routes (including plugin routes) have been registered.
    Raises ``RuntimeError`` at startup if any endpoint is unprotected and unmarked,
    preventing the application from serving traffic with unintended public endpoints.
    """
    unprotected: list[tuple[str, str]] = []

    for route in app.routes:
        if not isinstance(route, APIRoute):
            continue
        # Skip catch-all frontend asset routes
        if route.path in ("/{catchall:path}", "/"):
            continue
        # Skip trailing-slash duplicates generated by FastAPI
        if route.path.endswith("/"):
            continue

        if _has_auth_dependency(route):
            continue
        if _is_marked_public(route):
            continue

        for method in sorted(route.methods or []):
            unprotected.append((method, route.path))

    if unprotected:
        formatted = "\n".join(f"  {m} {p}" for m, p in sorted(unprotected))
        raise RuntimeError(
            f"Found {len(unprotected)} API endpoint(s) without authentication "
            f"that are not marked @public_endpoint:\n{formatted}\n\n"
            "Either:\n"
            "  1. Add a Security(...) dependency to the endpoint, OR\n"
            "  2. Decorate the endpoint function with @public_endpoint and document it at:\n"
            "     https://www.ethyca.com/docs/platform/configuration/security-practices"
            "#public-internet----fides-webserver"
        )

    logger.info(
        "Endpoint auth policy validated: all endpoints are protected or explicitly public"
    )
