// This file is auto-generated by @hey-api/openapi-ts

import type { ManualWebhookField } from "./ManualWebhookField";

/**
 * AccessManualWebhooks
 *
 * Expected request body for creating Access Manual Webhooks
 */
export type AccessManualWebhooks = {
  /**
   * Fields
   */
  fields: Array<ManualWebhookField>;
};
