// This file is auto-generated by @hey-api/openapi-ts

import type { AccessPackageCategory } from "./AccessPackageCategory";

/**
 * AccessPackageDataUse
 *
 * A top-level data use section in the access package.
 */
export type AccessPackageDataUse = {
  /**
   * Fides Key
   */
  fides_key: string;
  /**
   * Name
   */
  name: string;
  /**
   * Description
   */
  description?: string;
  /**
   * Categories
   */
  categories?: Array<AccessPackageCategory>;
};
