// This file is auto-generated by @hey-api/openapi-ts

/**
 * AccessPolicyUpdate
 *
 * Request body for updating an access policy.
 */
export type AccessPolicyUpdate = {
  /**
   * Name
   */
  name?: string | null;
  /**
   * Description
   */
  description?: string | null;
  /**
   * Yaml
   *
   * Full policy YAML as a string
   */
  yaml?: string | null;
};
