// This file is auto-generated by @hey-api/openapi-ts

import { ActorType } from "./ActorType";

/**
 * ActivityFeedItem
 */
export type ActivityFeedItem = {
  actor_type: ActorType;
  /**
   * Message
   */
  message: string;
  /**
   * Timestamp
   */
  timestamp: string;
};
