// This file is auto-generated by @hey-api/openapi-ts

import { ErrorNotificationMode } from "./ErrorNotificationMode";

/**
 * AdminUIConfig
 */
export type AdminUIConfig = {
  /**
   * Enabled
   */
  enabled?: boolean | null;
  /**
   * Url
   */
  url?: string | null;
  error_notification_mode?: ErrorNotificationMode | null;
  /**
   * Consent Module Enabled
   */
  consent_module_enabled?: boolean | null;
};
