// This file is auto-generated by @hey-api/openapi-ts

import type { ExtendedIdentityTypes } from "./ExtendedIdentityTypes";

/**
 * AdvancedSettingsWithExtendedIdentityTypes
 *
 * Overrides base AdvancedSettings to have extended IdentityTypes
 */
export type AdvancedSettingsWithExtendedIdentityTypes = {
  identity_types: ExtendedIdentityTypes;
};
