// This file is auto-generated by @hey-api/openapi-ts

/**
 * AesEncryptionResponse
 *
 * Specifies fields returned from the AES Encryption endpoint
 */
export type AesEncryptionResponse = {
  /**
   * Encrypted Value
   */
  encrypted_value: string;
  /**
   * Nonce
   */
  nonce: string;
};
