// This file is auto-generated by @hey-api/openapi-ts

/**
 * AesEncryptionRequest
 *
 * Specifies fields provided to the AES Encryption endpoint
 */
export type AesEncryptionRequest = {
  /**
   * Value
   */
  value: string;
  /**
   * Key
   */
  key: string;
};
