// This file is auto-generated by @hey-api/openapi-ts

/**
 * AllowList
 */
export type AllowList = {
  /**
   * Name
   */
  name?: string | null;
  /**
   * Description
   */
  description?: string | null;
  /**
   * Allowed Values
   */
  allowed_values?: Array<string> | null;
  /**
   * Id
   */
  id?: string | null;
};
