// This file is auto-generated by @hey-api/openapi-ts

/**
 * AnswerSourceBreakdown
 *
 * Count of complete answers per source. Mirrors the ``AnswerSource``
 * enum on the backend.
 */
export type AnswerSourceBreakdown = {
  /**
   * System
   */
  system?: number;
  /**
   * Ai Analysis
   */
  ai_analysis?: number;
  /**
   * User Input
   */
  user_input?: number;
  /**
   * Team Input
   */
  team_input?: number;
};
