// This file is auto-generated by @hey-api/openapi-ts

/**
 * ApprovalProgress
 *
 * Approval progress tracking for monitors.
 */
export type ApprovalProgress = {
  /**
   * Approved
   */
  approved?: number;
  /**
   * Total
   */
  total?: number;
  /**
   * Percentage
   */
  percentage?: number;
};
