// This file is auto-generated by @hey-api/openapi-ts

/**
 * AssetUpdate
 *
 * Schema for updating an asset's mutable fields.
 * Changing any other fields would effectively create a new asset
 */
export type AssetUpdate = {
  /**
   * Data Uses
   */
  data_uses?: Array<string> | null;
  /**
   * Description
   */
  description?: string | null;
  /**
   * Duration
   */
  duration?: string | null;
  /**
   * Id
   */
  id: string;
  /**
   * System Key
   */
  system_key?: string | null;
  /**
   * System Id
   */
  system_id?: string | null;
};
