// This file is auto-generated by @hey-api/openapi-ts

import type { AssessmentTaskSystemInfo } from "./AssessmentTaskSystemInfo";

/**
 * AssessmentTaskResponse
 *
 * Response schema for privacy assessment task status.
 */
export type AssessmentTaskResponse = {
  /**
   * Id
   */
  id: string;
  /**
   * Action Type
   */
  action_type: string;
  /**
   * Status
   */
  status: string;
  /**
   * Total Count
   */
  total_count?: number;
  /**
   * Completed Count
   */
  completed_count?: number;
  /**
   * Progress
   */
  progress?: number;
  /**
   * Message
   */
  message?: string | null;
  /**
   * Assessment Types
   */
  assessment_types?: Array<string>;
  /**
   * System Fides Keys
   */
  system_fides_keys?: Array<string> | null;
  /**
   * Systems
   */
  systems?: Array<AssessmentTaskSystemInfo> | null;
  /**
   * Created By
   */
  created_by?: string | null;
  /**
   * Use Llm
   */
  use_llm?: boolean;
  /**
   * Llm Model
   */
  llm_model?: string | null;
  /**
   * Assessment Ids
   */
  assessment_ids?: Array<string>;
  /**
   * Created At
   */
  created_at?: string | null;
  /**
   * Updated At
   */
  updated_at?: string | null;
};
