// This file is auto-generated by @hey-api/openapi-ts

/**
 * AttachmentResponse
 *
 * Schema for attachment responses returned by the API.
 */
export type AttachmentResponse = {
  /**
   * Id
   *
   * The attachment ID
   */
  id: string;
  /**
   * User Id
   *
   * The user ID
   */
  user_id: string | null;
  /**
   * Username
   *
   * The user name
   */
  username: string;
  /**
   * User First Name
   *
   * The user first name
   */
  user_first_name: string | null;
  /**
   * User Last Name
   *
   * The user last name
   */
  user_last_name: string | null;
  /**
   * File Name
   *
   * The attachment name
   */
  file_name: string;
  /**
   * Attachment Type
   *
   * The attachment type
   */
  attachment_type: string;
  /**
   * Retrieved Attachment Size
   *
   * The size of the attachment
   */
  retrieved_attachment_size: number | null;
  /**
   * Retrieved Attachment Url
   *
   * The URL to retrieve the attachment
   */
  retrieved_attachment_url: string | string | null;
  /**
   * Created At
   *
   * The creation date
   */
  created_at: string;
};
