// This file is auto-generated by @hey-api/openapi-ts

/**
 * AuthenticationMethods
 *
 * Schema for reporting which authentication methods are enabled.
 */
export type AuthenticationMethods = {
  /**
   * Username Password
   */
  username_password: boolean;
  /**
   * Sso
   */
  sso: boolean;
};
