// This file is auto-generated by @hey-api/openapi-ts

/**
 * BackfillStatusResponse
 *
 * Response body for backfill status endpoint.
 */
export type BackfillStatusResponse = {
  /**
   * Is Running
   *
   * Whether a backfill is currently running
   */
  is_running: boolean;
  /**
   * Pending Count
   *
   * Count of rows pending backfill, keyed by backfill task name
   */
  pending_count: {
    [key: string]: number;
  };
};
