// This file is auto-generated by @hey-api/openapi-ts

/**
 * BackfillRequest
 *
 * Request body for triggering a database backfill operation.
 */
export type BackfillRequest = {
  /**
   * Batch Size
   *
   * Number of rows to update per batch (default: 5000)
   */
  batch_size?: number;
  /**
   * Batch Delay Seconds
   *
   * Delay between batches in seconds (default: 1.0)
   */
  batch_delay_seconds?: number;
};
