// This file is auto-generated by @hey-api/openapi-ts

/**
 * BedrockConnectionTestRequest
 *
 * Request schema for AWS Bedrock connection test.
 */
export type BedrockConnectionTestRequest = {
  /**
   * Aws Region
   */
  aws_region: string;
  /**
   * Model
   *
   * Bedrock model string
   */
  model: string;
  /**
   * Aws Bearer Token Bedrock
   */
  aws_bearer_token_bedrock?: string | null;
  /**
   * Aws Role Arn
   */
  aws_role_arn?: string | null;
  /**
   * Aws Web Identity Token
   */
  aws_web_identity_token?: string | null;
  /**
   * Aws Role Session Name
   */
  aws_role_session_name?: string | null;
};
