// This file is auto-generated by @hey-api/openapi-ts

import type { fidesplus__cls__schemas__connection_configuration__connection_secrets_bigquery__KeyfileCreds } from "./fidesplus__cls__schemas__connection_configuration__connection_secrets_bigquery__KeyfileCreds";

/**
 * BigQueryMonitorConfig
 *
 * BigQuery monitor configuration.
 *
 * Simplified seed input for creating a BigQuery discovery monitor.
 * See also: EditableMonitorConfig, MonitorClassifyParams, BigQuerySchema.
 */
export type BigQueryMonitorConfig = {
  /**
   * BigQuery keyfile credentials (JSON string or object)
   */
  keyfile_creds: fidesplus__cls__schemas__connection_configuration__connection_secrets_bigquery__KeyfileCreds;
  /**
   * System Key
   *
   * System key to link the connection to
   */
  system_key?: string;
  /**
   * Execute After Creation
   *
   * Execute the monitor after creation
   */
  execute_after_creation?: boolean;
};
