// This file is auto-generated by @hey-api/openapi-ts

import type { CustomReportCreate } from "./CustomReportCreate";

/**
 * Body_export_minimal_datamap_with_format_api_v1_plus_datamap_minimal__export_format__post
 */
export type Body_export_minimal_datamap_with_format_api_v1_plus_datamap_minimal__export_format__post =
  {
    report?: CustomReportCreate | null;
  };
