// This file is auto-generated by @hey-api/openapi-ts

import { AttachmentType } from "./AttachmentType";

/**
 * Body_create_attachment_api_v1_plus_privacy_request__privacy_request_id__access_manual_webhook__connection_key__attachment_post
 */
export type Body_create_attachment_api_v1_plus_privacy_request__privacy_request_id__access_manual_webhook__connection_key__attachment_post =
  {
    attachment_type: AttachmentType;
    /**
     * Attachment File
     */
    attachment_file: Blob | File;
  };
