// This file is auto-generated by @hey-api/openapi-ts

import type { ConditionGroup } from "./ConditionGroup";
import type { ConditionLeaf } from "./ConditionLeaf";

/**
 * BulkConditionAssignment
 *
 * Schema for bulk condition assignment to task and/or fields.
 *
 * This allows setting conditions for both the task level and specific config fields
 * in a single request.
 */
export type BulkConditionAssignment = {
  /**
   * Task Conditions
   *
   * Conditions to set at task level
   */
  task_conditions?: Array<ConditionLeaf | ConditionGroup> | null;
  /**
   * Field Conditions
   *
   * Conditions to set for specific fields, keyed by config_field_key
   */
  field_conditions?: {
    [key: string]: Array<ConditionLeaf | ConditionGroup>;
  } | null;
};
