// This file is auto-generated by @hey-api/openapi-ts

import type { BasicMessagingTemplateResponse } from "./BasicMessagingTemplateResponse";
import type { BulkUpdateFailed } from "./BulkUpdateFailed";

/**
 * BulkPutBasicMessagingTemplateResponse
 */
export type BulkPutBasicMessagingTemplateResponse = {
  /**
   * Succeeded
   */
  succeeded: Array<BasicMessagingTemplateResponse>;
  /**
   * Failed
   */
  failed: Array<BulkUpdateFailed>;
};
