// This file is auto-generated by @hey-api/openapi-ts

import type { BulkUpdateFailed } from "./BulkUpdateFailed";

/**
 * BulkSoftDeletePrivacyRequests
 */
export type BulkSoftDeletePrivacyRequests = {
  /**
   * Succeeded
   */
  succeeded: Array<string>;
  /**
   * Failed
   */
  failed: Array<BulkUpdateFailed>;
};
