// This file is auto-generated by @hey-api/openapi-ts

import type { CustomFieldWithId } from "./CustomFieldWithId";

/**
 * BulkCustomFieldRequest
 */
export type BulkCustomFieldRequest = {
  /**
   * Resource Type
   */
  resource_type: string;
  /**
   * Resource Id
   */
  resource_id: string;
  /**
   * Upsert
   */
  upsert?: Array<CustomFieldWithId> | null;
  /**
   * Delete
   */
  delete?: Array<string> | null;
};
