// This file is auto-generated by @hey-api/openapi-ts

/**
 * ChatConfigSecrets
 *
 * Schema for updating secrets only.
 */
export type ChatConfigSecrets = {
  /**
   * Client Secret
   */
  client_secret?: string | null;
  /**
   * Signing Secret
   */
  signing_secret?: string | null;
};
