// This file is auto-generated by @hey-api/openapi-ts

/**
 * ChatConfigResponse
 *
 * Response schema for a chat configuration (excludes secrets).
 */
export type ChatConfigResponse = {
  /**
   * Id
   */
  id: string;
  /**
   * Enabled
   */
  enabled: boolean;
  /**
   * Provider Type
   */
  provider_type: string;
  /**
   * Workspace Url
   */
  workspace_url?: string | null;
  /**
   * Client Id
   */
  client_id?: string | null;
  /**
   * Authorized
   */
  authorized: boolean;
  /**
   * Has Signing Secret
   */
  has_signing_secret?: boolean;
  /**
   * Created At
   */
  created_at: string;
  /**
   * Updated At
   */
  updated_at: string;
  /**
   * Workspace Name
   */
  workspace_name?: string | null;
  /**
   * Connected By Email
   */
  connected_by_email?: string | null;
};
