// This file is auto-generated by @hey-api/openapi-ts

/**
 * ChatConfigTestResponse
 *
 * Response schema for chat provider connection test.
 */
export type ChatConfigTestResponse = {
  /**
   * Success
   */
  success: boolean;
  /**
   * Message
   */
  message: string;
};
