// This file is auto-generated by @hey-api/openapi-ts

import type { ChatConfigResponse } from "./ChatConfigResponse";

/**
 * ChatConfigListResponse
 *
 * Response schema for list of chat configurations.
 */
export type ChatConfigListResponse = {
  /**
   * Items
   */
  items: Array<ChatConfigResponse>;
  /**
   * Total
   */
  total: number;
};
