// This file is auto-generated by @hey-api/openapi-ts

import type { SlackChannel } from "./SlackChannel";

/**
 * ChatChannelsResponse
 *
 * Response schema for list of available channels.
 */
export type ChatChannelsResponse = {
  /**
   * Channels
   */
  channels: Array<SlackChannel>;
};
