// This file is auto-generated by @hey-api/openapi-ts

import { CurrentStep } from "./CurrentStep";
import type { ManualAction } from "./ManualAction";

/**
 * CheckpointActionRequiredDetails
 */
export type CheckpointActionRequiredDetails = {
  step: CurrentStep;
  /**
   * Collection
   */
  collection?: string | null;
  /**
   * Action Needed
   */
  action_needed?: Array<ManualAction> | null;
};
