// This file is auto-generated by @hey-api/openapi-ts

import { ClassifyLlmPromptTemplateOptions } from "./ClassifyLlmPromptTemplateOptions";

/**
 * ClassifyLlmParams
 *
 * Parameters for the llm/classifier/llm_context_classifier function
 */
export type ClassifyLlmParams = {
  /**
   * Llm Model Override
   */
  llm_model_override?: string | null;
  /**
   * Custom Llm Instructions
   */
  custom_llm_instructions?: string | null;
  prompt_template?: ClassifyLlmPromptTemplateOptions | null;
  /**
   * Include Rationale
   */
  include_rationale?: boolean;
  /**
   * Num Workers
   */
  num_workers?: number;
  /**
   * Max Tokens
   */
  max_tokens?: number;
  /**
   * Taxonomy Instructions
   */
  taxonomy_instructions?: string | null;
  /**
   * Tagging Instructions
   */
  tagging_instructions?: {
    [key: string]: {
      [key: string]: unknown;
    };
  } | null;
  /**
   * Tagging Instructions Override All
   */
  tagging_instructions_override_all?: {
    [key: string]: {
      [key: string]: unknown;
    };
  } | null;
  /**
   * Tagging Instructions Remove
   */
  tagging_instructions_remove?: Array<string> | null;
  /**
   * Classification Retry Count
   *
   * Number of times to retry classification if the LLM returns an invalid response (e.g., null tags, malformed XML). Set to 0 to disable retries.
   */
  classification_retry_count?: number;
};
