// This file is auto-generated by @hey-api/openapi-ts

/**
 * Classification
 *
 * The model for the suggested data labels.
 *
 * Note: For LLM-based classifications, the `score` field is always 1.0 and is not used
 * for confidence bucket determination. Instead, the `confidence_rating` field (1-5 integer)
 * is used to calculate confidence buckets (low, medium, high). The `score` field is primarily
 * maintained for backwards compatibility with legacy classification systems.
 */
export type Classification = {
  /**
   * Label
   */
  label: string;
  /**
   * Score
   */
  score: number;
  /**
   * Rationale
   */
  rationale?: string | null;
  /**
   * Confidence Rating
   */
  confidence_rating?: number | null;
  /**
   * Default
   */
  default?: boolean;
};
