// This file is auto-generated by @hey-api/openapi-ts

import { ClassificationStatus } from "./ClassificationStatus";
import { GenerateTypes } from "./GenerateTypes";

/**
 * ClassifyInstanceResponseValues
 */
export type ClassifyInstanceResponseValues = {
  status: ClassificationStatus;
  /**
   * Organization Key
   */
  organization_key: string;
  /**
   * Dataset Key
   */
  dataset_key: string;
  /**
   * Dataset Name
   */
  dataset_name: string;
  /**
   * Target
   */
  target: string;
  type: GenerateTypes;
  /**
   * Id
   */
  id: string;
  /**
   * Created At
   */
  created_at: string;
  /**
   * Updated At
   */
  updated_at: string;
  /**
   * Has Labels
   */
  has_labels?: boolean;
};
