// This file is auto-generated by @hey-api/openapi-ts

import { ConfidenceBucket } from "./ConfidenceBucket";

/**
 * ClassificationWithConfidence
 *
 * Pydantic Schema used to represent a classification with a confidence bucket.
 *
 * The confidence_bucket is automatically calculated based on the confidence_rating
 * (1-5 integer) compared against configurable high/low thresholds, not the score field.
 * NULL confidence_rating is treated as 0, which maps to the LOW bucket.
 *
 * Thresholds are read from config. For testing, set config values via fixtures.
 *
 * Can be constructed from:
 * - A dict (e.g., from DB JSON column)
 * - A Classification instance (via from_classification() or direct instantiation)
 */
export type ClassificationWithConfidence = {
  /**
   * Label
   */
  label: string;
  /**
   * Score
   */
  score: number;
  /**
   * Rationale
   */
  rationale?: string | null;
  /**
   * Confidence Rating
   */
  confidence_rating?: number | null;
  /**
   * Default
   */
  default?: boolean;
  /**
   * Confidence bucket (high/medium/low/manual) based on confidence_rating (1-5). NULL is treated as 0 (LOW).
   */
  confidence_bucket: ConfidenceBucket;
};
