// This file is auto-generated by @hey-api/openapi-ts

import type { Classification } from "./Classification";

/**
 * ClassifyDataFlow
 */
export type ClassifyDataFlow = {
  /**
   * Fides Key
   */
  fides_key: string;
  /**
   * Classifications
   */
  classifications: Array<Classification>;
};
