// This file is auto-generated by @hey-api/openapi-ts

import { ClassificationStatus } from "./ClassificationStatus";
import type { ClassifyDataFlow } from "./ClassifyDataFlow";

/**
 * ClassifySystem
 */
export type ClassifySystem = {
  /**
   * Fides Key
   */
  fides_key: string;
  /**
   * Name
   */
  name: string;
  status: ClassificationStatus;
  /**
   * Egress
   */
  egress: Array<ClassifyDataFlow>;
  /**
   * Ingress
   */
  ingress: Array<ClassifyDataFlow>;
};
