// This file is auto-generated by @hey-api/openapi-ts

/**
 * ClassifyParams
 *
 * Model for the classifier params
 * These are all not required as part of the request
 * and can rely on the defaults
 */
export type ClassifyParams = {
  /**
   * Possible Targets
   */
  possible_targets?: Array<string> | null;
  /**
   * Top N
   */
  top_n?: number;
  /**
   * Remove Stop Words
   */
  remove_stop_words?: boolean;
  /**
   * Pii Threshold
   */
  pii_threshold?: number;
  /**
   * Num Samples
   */
  num_samples?: number;
  /**
   * Num Threads
   */
  num_threads?: number;
};
