// This file is auto-generated by @hey-api/openapi-ts

/**
 * ClassificationCoverage
 *
 * Coverage statistics for the classification run.
 */
export type ClassificationCoverage = {
  /**
   * Total Resources
   *
   * Total resources in the monitor
   */
  total_resources: number;
  /**
   * Classified By Compass
   *
   * Resources classified by Compass (have vendor_id from scan)
   */
  classified_by_compass: number;
  /**
   * Classified By Llm
   *
   * Resources classified by LLM
   */
  classified_by_llm: number;
  /**
   * Unclassified
   *
   * Resources still without classification
   */
  unclassified: number;
  /**
   * Coverage Rate
   *
   * Percentage of resources with any classification
   */
  coverage_rate: number;
};
