// This file is auto-generated by @hey-api/openapi-ts

import type { ClassifyParams } from "./ClassifyParams";
import type { DatasetSchema } from "./DatasetSchema";
import type { GenerateRequestPayload } from "./GenerateRequestPayload";

/**
 * ClassifyRequestPayload
 */
export type ClassifyRequestPayload = {
  schema_config: GenerateRequestPayload;
  /**
   * Dataset Schemas
   */
  dataset_schemas: Array<DatasetSchema>;
  classify_params?: ClassifyParams;
};
