// This file is auto-generated by @hey-api/openapi-ts

import type { MaskingStrategyOverride } from "./MaskingStrategyOverride";

/**
 * CollectionMeta
 *
 * Collection-level specific annotations used for query traversal
 */
export type CollectionMeta = {
  /**
   * After
   */
  after?: Array<string> | null;
  /**
   * Erase After
   */
  erase_after?: Array<string> | null;
  /**
   * Skip Processing
   */
  skip_processing?: boolean | null;
  masking_strategy_override?: MaskingStrategyOverride | null;
  /**
   * Partitioning
   */
  partitioning?:
    | {
        [key: string]: unknown;
      }
    | Array<{
        [key: string]: unknown;
      }>
    | null;
  /**
   * Redact
   *
   * Specify 'name' to indicate the collection name should be redacted.
   */
  redact?: "name" | null;
};
