// This file is auto-generated by @hey-api/openapi-ts

import type { AttachmentResponse } from "./AttachmentResponse";
import { CommentType } from "./CommentType";

/**
 * CommentResponse
 *
 * Model for comment responses.
 */
export type CommentResponse = {
  /**
   * Id
   *
   * The comment ID
   */
  id: string;
  /**
   * Privacy Request Id
   *
   * The privacy request ID
   */
  privacy_request_id: string;
  /**
   * User Id
   *
   * The user ID
   */
  user_id: string | null;
  /**
   * Username
   *
   * The username
   */
  username: string | null;
  /**
   * User First Name
   *
   * The user first name
   */
  user_first_name: string | null;
  /**
   * User Last Name
   *
   * The user last name
   */
  user_last_name: string | null;
  /**
   * Created At
   *
   * The creation date
   */
  created_at: string;
  /**
   * Attachments
   *
   * The attachments
   */
  attachments: Array<AttachmentResponse>;
  /**
   * Comment Text
   *
   * The comment text
   */
  comment_text: string;
  /**
   * The comment type
   */
  comment_type: CommentType;
};
