// This file is auto-generated by @hey-api/openapi-ts

import { Operator } from "./Operator";

/**
 * ConditionLeaf
 */
export type ConditionLeaf = {
  /**
   * Field Address
   *
   * Field path to check (e.g., 'user.name', 'billing.subscription.status')
   */
  field_address: string;
  /**
   * Operator to apply
   */
  operator: Operator;
  /**
   * Value
   *
   * Expected value for comparison
   */
  value?:
    | string
    | number
    | number
    | boolean
    | Array<string | number | number | boolean>
    | null;
};
