// This file is auto-generated by @hey-api/openapi-ts

/**
 * ConnectionDatahubSyncDetailStatus
 *
 * Status of a Datahub sync detail.
 */
export enum ConnectionDatahubSyncDetailStatus {
  SUCCEEDED = "succeeded",
  FAILED = "failed",
}
