// This file is auto-generated by @hey-api/openapi-ts

/**
 * ConnectionTestStatus
 *
 * Enum for supplying statuses of validating credentials for a Connection Config to the user
 */
export enum ConnectionTestStatus {
  SUCCEEDED = "succeeded",
  FAILED = "failed",
  SKIPPED = "skipped",
}
