// This file is auto-generated by @hey-api/openapi-ts

/**
 * ConnectorParam
 *
 * Used to define the required parameters for the connector (user and constants)
 */
export type ConnectorParam = {
  /**
   * Name
   */
  name: string;
  /**
   * Label
   */
  label?: string | null;
  /**
   * Options
   */
  options?: Array<string> | null;
  /**
   * Default Value
   */
  default_value?: string | Array<string> | number | Array<number> | null;
  /**
   * Multiselect
   */
  multiselect?: boolean | null;
  /**
   * Description
   */
  description?: string | null;
  /**
   * Sensitive
   */
  sensitive?: boolean | null;
  /**
   * Type
   */
  type?: string | null;
  /**
   * Allowed Values
   */
  allowed_values?: Array<string> | null;
};
