// This file is auto-generated by @hey-api/openapi-ts

/**
 * ConnectionDatahubSyncPayload
 *
 * Payload for syncing Datahub connections.
 */
export type ConnectionDatahubSyncPayload = {
  /**
   * Dataset Ids
   */
  dataset_ids: Array<string>;
};
