// This file is auto-generated by @hey-api/openapi-ts

/**
 * ConsentMechanism
 *
 * Enum is not formalized in the DB because it may be subject to frequent change
 */
export enum ConsentMechanism {
  OPT_IN = "opt_in",
  OPT_OUT = "opt_out",
  NOTICE_ONLY = "notice_only",
}
