// This file is auto-generated by @hey-api/openapi-ts

/**
 * ConsentableItem
 *
 * Schema to represent 3rd-party consentable items and privacy notice relationships.
 */
export type ConsentableItem = {
  /**
   * External Id
   */
  external_id: string;
  /**
   * Type
   */
  type: string;
  /**
   * Name
   */
  name: string;
  /**
   * Notice Id
   */
  notice_id?: string | null;
  /**
   * Children
   */
  children?: Array<ConsentableItem>;
  /**
   * Unmapped
   */
  unmapped?: boolean | null;
};
