// This file is auto-generated by @hey-api/openapi-ts

import type { ConsumerRequestSummaryResponse } from "./ConsumerRequestSummaryResponse";

/**
 * ConsumerRequestsByConsumerResponse
 */
export type ConsumerRequestsByConsumerResponse = {
  /**
   * Items
   */
  items: Array<ConsumerRequestSummaryResponse>;
};
