// This file is auto-generated by @hey-api/openapi-ts

import { fidesplus__api__schemas__discovery_monitor__ConstraintType } from "./fidesplus__api__schemas__discovery_monitor__ConstraintType";

/**
 * Constraint
 *
 * Base class for table constraints
 */
export type Constraint = {
  /**
   * Name
   */
  name: string;
  /**
   * Fields
   */
  fields: Array<string>;
  type: fidesplus__api__schemas__discovery_monitor__ConstraintType;
};
