// This file is auto-generated by @hey-api/openapi-ts

import type { FidesConsentMetaCreate } from "./FidesConsentMetaCreate";

/**
 * ConsentMetaCreate
 *
 * A set of Fides-defined metadata properties for a privacy preference.
 */
export type ConsentMetaCreate = {
  /**
   * A set of Fides-defined metadata properties for a privacy preference.
   */
  fides?: FidesConsentMetaCreate | null;
  [key: string]: unknown | FidesConsentMetaCreate | null | undefined;
};
