// This file is auto-generated by @hey-api/openapi-ts

import type { ConsentMetaResponse } from "./ConsentMetaResponse";
import type { ConsentPreferenceResponse } from "./ConsentPreferenceResponse";
import type { ConsentScopeResponse } from "./ConsentScopeResponse";
import type { fidesplus__v3__schemas__identity__Identity } from "./fidesplus__v3__schemas__identity__Identity";

/**
 * ConsentResponse
 *
 * Unified consent v3 schema with server-generated fields (ID, created_at, etc.).
 */
export type ConsentResponse = {
  identity: fidesplus__v3__schemas__identity__Identity;
  scope?: ConsentScopeResponse | null;
  meta: ConsentMetaResponse;
  /**
   * Preferences
   */
  preferences: Array<ConsentPreferenceResponse>;
  /**
   * Is Latest
   *
   * Indicates if this is the latest preference record for the given identity
   */
  is_latest?: boolean | null;
};
