// This file is auto-generated by @hey-api/openapi-ts

/**
 * ConsentRequestResponse
 *
 * Schema for consent request response.
 */
export type ConsentRequestResponse = {
  /**
   * Consent Request Id
   */
  consent_request_id: string;
};
