// This file is auto-generated by @hey-api/openapi-ts

import type { FidesConsentScopes } from "./FidesConsentScopes";

/**
 * ConsentScopeResponse
 *
 * Scope information with reserved 'fides' namespace and arbitrary additional fields
 */
export type ConsentScopeResponse = {
  /**
   * A reserved 'fides' namespace for Fides-defined scope properties.
   */
  fides?: FidesConsentScopes | null;
  [key: string]: unknown | FidesConsentScopes | null | undefined;
};
