// This file is auto-generated by @hey-api/openapi-ts

/**
 * Consent
 *
 * Deprecated: This used to be populated and sent to the server by a `config.json` in the UI
 */
export type Consent = {
  /**
   * Data Use
   */
  data_use: string;
  /**
   * Data Use Description
   */
  data_use_description?: string | null;
  /**
   * Opt In
   */
  opt_in: boolean;
  /**
   * Has Gpc Flag
   */
  has_gpc_flag?: boolean;
  /**
   * Conflicts With Gpc
   */
  conflicts_with_gpc?: boolean;
};
