// This file is auto-generated by @hey-api/openapi-ts

import { ConsentMechanism } from "./ConsentMechanism";
import { LoadingContext } from "./LoadingContext";

/**
 * ConsentStatusReason
 *
 * TypedDict for storing details relevant to the consent status for a given asset
 */
export type ConsentStatusReason = {
  /**
   * Notice Key
   */
  notice_key: string;
  mechanism: ConsentMechanism;
  loading_context: LoadingContext;
};
