// This file is auto-generated by @hey-api/openapi-ts

/**
 * ConsumerTypeResponse
 *
 * A consumer type supported by an identity group provider.
 */
export type ConsumerTypeResponse = {
  /**
   * Key
   */
  key: string;
  /**
   * Name
   */
  name: string;
  /**
   * Description
   */
  description: string;
  /**
   * Platform
   */
  platform: string;
  /**
   * Platform Label
   */
  platform_label: string;
  /**
   * Supports Members
   */
  supports_members: boolean;
  /**
   * Scope Keys
   */
  scope_keys: {
    [key: string]: string;
  };
  /**
   * Display Key
   */
  display_key?: string;
};
