// This file is auto-generated by @hey-api/openapi-ts

/**
 * ConsentWithExecutableStatus
 *
 * Schema for executable consents
 */
export type ConsentWithExecutableStatus = {
  /**
   * Data Use
   */
  data_use: string;
  /**
   * Executable
   */
  executable: boolean;
};
