// This file is auto-generated by @hey-api/openapi-ts

import type { PreferenceMetaResponse } from "./PreferenceMetaResponse";
import { UserConsentPreference } from "./UserConsentPreference";

/**
 * ConsentPreferenceResponse
 *
 * An individual preference response (includes backend-generated fields).
 */
export type ConsentPreferenceResponse = {
  /**
   * Notice History Id
   *
   * Identifier for the notice history
   */
  notice_history_id: string;
  /**
   * Notice Key
   *
   * Key identifying the privacy notice
   */
  notice_key: string;
  /**
   * User preference value
   */
  value: UserConsentPreference;
  /**
   * Collected At
   *
   * ISO timestamp when the preference was collected (auto-populated if not provided)
   */
  collected_at: string;
  /**
   * Metadata for a single preference value (includes backend fields like 'derived', 'override', 'source')
   */
  meta?: PreferenceMetaResponse | null;
};
