// This file is auto-generated by @hey-api/openapi-ts

import { AllowedTypes } from "./AllowedTypes";
import { ResourceTypes } from "./ResourceTypes";

/**
 * CustomFieldDefinitionResponse
 */
export type CustomFieldDefinitionResponse = {
  /**
   * Name
   */
  name: string;
  /**
   * Description
   */
  description?: string | null;
  /**
   * Field Type
   */
  field_type: AllowedTypes | string;
  /**
   * Allow List Id
   */
  allow_list_id?: string | null;
  /**
   * Resource Type
   */
  resource_type: ResourceTypes | string;
  /**
   * Field Definition
   */
  field_definition?: string | null;
  /**
   * Active
   */
  active?: boolean;
  /**
   * Id
   */
  id: string;
  /**
   * Created At
   */
  created_at: string;
};
