// This file is auto-generated by @hey-api/openapi-ts

import type { CustomReportConfig } from "./CustomReportConfig";
import { ReportType } from "./ReportType";

/**
 * CustomReportResponse
 *
 * Response containing the basic custom report information along with the actual custom report configuration.
 */
export type CustomReportResponse = {
  /**
   * Id
   */
  id: string;
  type: ReportType;
  /**
   * Name
   */
  name: string;
  /**
   * Stable key of the OOTB regulatory reporting template that owns this report (e.g. 'ico', 'dpc', 'cnil'). When set, the report is system-managed: clients should render it with a 'Standard' badge and disable the delete affordance.
   */
  system_template_key?: string | null;
  config: CustomReportConfig;
};
