// This file is auto-generated by @hey-api/openapi-ts

/**
 * DataPurposeRef
 *
 * Minimal purpose reference in consumer responses.
 */
export type DataPurposeRef = {
  /**
   * Fides Key
   */
  fides_key: string;
  /**
   * Name
   */
  name: string;
};
