// This file is auto-generated by @hey-api/openapi-ts

/**
 * DatasetReachability
 *
 * Response containing reachability details for a single dataset
 */
export type DatasetReachability = {
  /**
   * Reachable
   */
  reachable: boolean;
  /**
   * Details
   */
  details:
    | string
    | Array<{
        [key: string]: unknown;
      }>
    | null;
};
