// This file is auto-generated by @hey-api/openapi-ts

import { ConfidenceBucket } from "./ConfidenceBucket";

/**
 * DatastoreMonitorResourcesDynamicFilters
 */
export type DatastoreMonitorResourcesDynamicFilters = {
  /**
   * Diff Status
   */
  diff_status?: Array<string> | null;
  /**
   * Data Category
   */
  data_category?: Array<string> | null;
  /**
   * Confidence Bucket
   */
  confidence_bucket?: Array<ConfidenceBucket> | null;
};
