// This file is auto-generated by @hey-api/openapi-ts

import type { ClassificationWithConfidence } from "./ClassificationWithConfidence";
import { DiffStatus } from "./DiffStatus";

/**
 * DatastoreStagedResourceAPIResponse
 *
 * Pydantic Schema used to represent any StageResource in datastore monitor, used only for API responses.
 */
export type DatastoreStagedResourceAPIResponse = {
  /**
   * Urn
   */
  urn: string;
  /**
   * Name
   */
  name?: string | null;
  diff_status?: DiffStatus | null;
  /**
   * Description
   */
  description?: string | null;
  /**
   * Updated At
   */
  updated_at?: string | null;
  /**
   * Classifications
   */
  classifications?: Array<ClassificationWithConfidence>;
  /**
   * User Assigned Data Categories
   *
   * User assigned data categories overriding auto assigned classifications
   */
  user_assigned_data_categories?: Array<string> | null;
  /**
   * Data Type
   */
  data_type?: string | null;
  /**
   * Monitor Config Id
   *
   * The monitor config that detected this resource
   */
  monitor_config_id: string;
};
