// This file is auto-generated by @hey-api/openapi-ts

import type { DatabaseHealthCheck } from "./DatabaseHealthCheck";

export type databaseHealthHealthDatabaseGetResponses = {
  /**
   * Successful Response
   */
  200: DatabaseHealthCheck;
};
