// This file is auto-generated by @hey-api/openapi-ts

/**
 * DatasetTraversalDetails
 *
 * Describes whether or not the parent dataset is traversable; if not, includes
 * an error message describing the traversal issues.
 */
export type DatasetTraversalDetails = {
  /**
   * Is Traversable
   */
  is_traversable: boolean;
  /**
   * Msg
   */
  msg: string | null;
};
