// This file is auto-generated by @hey-api/openapi-ts

/**
 * DatasetPropertyIdsResponse
 *
 * Property IDs assigned to a dataset.
 */
export type DatasetPropertyIdsResponse = {
  /**
   * Property Ids
   */
  property_ids: Array<string>;
};
