// This file is auto-generated by @hey-api/openapi-ts

import { DataSubjectRightsEnum } from "./DataSubjectRightsEnum";
import { IncludeExcludeEnum } from "./IncludeExcludeEnum";

/**
 * DataSubjectRights
 *
 * The DataSubjectRights resource model.
 *
 * Includes a strategy and optionally a
 * list of data subject rights to apply
 * via the set strategy.
 */
export type DataSubjectRights = {
  /**
   * Defines the strategy used when mapping data rights to a data subject.
   */
  strategy: IncludeExcludeEnum;
  /**
   * Values
   *
   * A list of valid data subject rights to be used when applying data rights to a data subject via a strategy.
   */
  values?: Array<DataSubjectRightsEnum> | null;
};
