// This file is auto-generated by @hey-api/openapi-ts

/**
 * DataSectionConfig
 *
 * Configuration for which data sections to include.
 */
export type DataSectionConfig = {
  /**
   * Organization
   */
  organization?: boolean;
  /**
   * Data Categories
   */
  data_categories?: boolean;
  /**
   * Data Uses
   */
  data_uses?: boolean;
  /**
   * Data Subjects
   */
  data_subjects?: boolean;
  /**
   * Systems
   */
  systems?: boolean;
  /**
   * Datasets
   */
  datasets?: boolean;
  /**
   * Policies
   */
  policies?: boolean;
  /**
   * Privacy Notices
   */
  privacy_notices?: boolean;
  /**
   * Connections
   */
  connections?: boolean;
};
