// This file is auto-generated by @hey-api/openapi-ts

import type { DataSubjectRights } from "./DataSubjectRights";

/**
 * DataSubjectCreateOrUpdate
 */
export type DataSubjectCreateOrUpdate = {
  /**
   * Version Added
   *
   * The version of Fideslang in which this label was added.
   */
  version_added?: string | null;
  /**
   * Version Deprecated
   *
   * The version of Fideslang in which this label was deprecated.
   */
  version_deprecated?: string | null;
  /**
   * Replaced By
   *
   * The new name, if applicable, for this label after deprecation.
   */
  replaced_by?: string | null;
  /**
   * Is Default
   *
   * Denotes whether the resource is part of the default taxonomy or not.
   */
  is_default?: boolean;
  /**
   * Name
   */
  name?: string | null;
  /**
   * Description
   */
  description?: string | null;
  /**
   * Active
   */
  active?: boolean | null;
  /**
   * Fides Key
   */
  fides_key?: string | null;
  /**
   * Tags
   */
  tags?: Array<string> | null;
  /**
   * Organization Fides Key
   */
  organization_fides_key?: string | null;
  rights?: DataSubjectRights | null;
  /**
   * Automated Decisions Or Profiling
   */
  automated_decisions_or_profiling?: boolean | null;
};
