// This file is auto-generated by @hey-api/openapi-ts

/**
 * DatasetMetadata
 *
 * The DatasetMetadata resource model.
 *
 * Object used to hold application specific metadata for a dataset
 */
export type DatasetMetadata = {
  /**
   * Resource Id
   */
  resource_id?: string | null;
  /**
   * After
   */
  after?: Array<string> | null;
  /**
   * Namespace
   */
  namespace?: {
    [key: string]: unknown;
  } | null;
  /**
   * Redact
   *
   * Specify 'name' to indicate the dataset name should be redacted.
   */
  redact?: "name" | null;
};
