// This file is auto-generated by @hey-api/openapi-ts

/**
 * DataProducerUpdate
 */
export type DataProducerUpdate = {
  /**
   * Name
   */
  name?: string | null;
  /**
   * Description
   */
  description?: string | null;
  /**
   * External Id
   */
  external_id?: string | null;
  /**
   * Monitor Id
   */
  monitor_id?: string | null;
  /**
   * Contact Email
   */
  contact_email?: string | null;
  /**
   * Contact Slack Channel
   */
  contact_slack_channel?: string | null;
  /**
   * Contact Details
   */
  contact_details?: {
    [key: string]: unknown;
  } | null;
};
