// This file is auto-generated by @hey-api/openapi-ts

/**
 * DBActions
 *
 * The available path parameters for the `/admin/db/{action}` endpoint.
 */
export enum DBActions {
  UPGRADE = "upgrade",
  RESET = "reset",
  DOWNGRADE = "downgrade",
}
