// This file is auto-generated by @hey-api/openapi-ts

import { ActionType } from "./ActionType";

/**
 * DefaultPolicyConfigRequest
 *
 * Request schema for setting default policy configuration.
 */
export type DefaultPolicyConfigRequest = {
  /**
   * Policy Key
   *
   * Policy key to set as default. Null to reset to system default.
   */
  policy_key?: string | null;
  /**
   * Action type (access, erasure, or consent) for which to set the default policy.
   */
  action_type: ActionType;
};
