// This file is auto-generated by @hey-api/openapi-ts

/**
 * DiffStatusDistribution
 *
 * Distribution of diff statuses across generated tables
 */
export type DiffStatusDistribution = {
  /**
   * Addition
   *
   * Proportion of tables with ADDITION status (0.0 to 1.0)
   */
  addition?: number;
  /**
   * Classifying
   *
   * Proportion of tables with CLASSIFYING status (0.0 to 1.0)
   */
  classifying?: number;
  /**
   * Classification Addition
   *
   * Proportion of tables with CLASSIFICATION_ADDITION status (0.0 to 1.0)
   */
  classification_addition?: number;
};
