// This file is auto-generated by @hey-api/openapi-ts

/**
 * DigestType
 *
 * Types of digests that can be configured.
 */
export enum DigestType {
  MANUAL_TASKS = "manual_tasks",
  PRIVACY_REQUESTS = "privacy_requests",
}
