// This file is auto-generated by @hey-api/openapi-ts

/**
 * DrpAction
 *
 * Enum to hold valid DRP actions. For more details, see:
 * https://github.com/consumer-reports-digital-lab/data-rights-protocol#301-supported-rights-actions
 */
export enum DrpAction {
  ACCESS = "access",
  DELETION = "deletion",
  "SALE:OPT_OUT" = "sale:opt_out",
  "SALE:OPT_IN" = "sale:opt_in",
  "ACCESS:CATEGORIES" = "access:categories",
  "ACCESS:SPECIFIC" = "access:specific",
}
