// This file is auto-generated by @hey-api/openapi-ts

import { DrpAction } from "./DrpAction";
import type { DrpMeta } from "./DrpMeta";
import { DrpRegime } from "./DrpRegime";

/**
 * DrpPrivacyRequestCreate
 *
 * Data required to create a DRP PrivacyRequest
 */
export type DrpPrivacyRequestCreate = {
  meta: DrpMeta;
  regime?: DrpRegime | null;
  /**
   * Exercise
   */
  exercise: Array<DrpAction>;
  /**
   * Relationships
   */
  relationships?: Array<string> | null;
  /**
   * Identity
   */
  identity: string;
  /**
   * Status Callback
   */
  status_callback?: string | null;
};
