// This file is auto-generated by @hey-api/openapi-ts

import type { AdvancedSettings } from "./AdvancedSettings";
import type { FidesDatasetReference } from "./FidesDatasetReference";

/**
 * DynamicErasureEmailDocsSchema
 *
 * DynamicErasureEmailDocsSchema Secrets Schema for API Docs
 */
export type DynamicErasureEmailDocsSchema = {
  /**
   * Test Email Address
   */
  test_email_address?: string | null;
  advanced_settings?: AdvancedSettings;
  /**
   * Third party vendor name field
   *
   * Dataset reference to the field containing the third party vendor name. Both third_party_vendor_name and recipient_email_address must reference the same dataset and collection.
   */
  third_party_vendor_name: FidesDatasetReference;
  /**
   * Recipient email address field
   *
   * Dataset reference to the field containing the recipient email address. Both third_party_vendor_name and recipient_email_address must reference the same dataset and collection.
   */
  recipient_email_address: FidesDatasetReference;
};
