// This file is auto-generated by @hey-api/openapi-ts

/**
 * EmbeddedPurpose
 *
 * Sparse details for an embedded purpose beneath a system or vendor section.  Read-only.
 */
export type EmbeddedPurpose = {
  /**
   * Id
   */
  id: number;
  /**
   * Name
   */
  name: string;
  /**
   * Retention Period
   */
  retention_period?: string | null;
};
