// This file is auto-generated by @hey-api/openapi-ts

/**
 * EmbeddedVendor
 *
 * Sparse details for an embedded vendor beneath a purpose or feature section. Read-only.
 */
export type EmbeddedVendor = {
  /**
   * Id
   */
  id: string;
  /**
   * Name
   */
  name: string;
};
