// This file is auto-generated by @hey-api/openapi-ts

import type { SaaSRequestMap } from "./SaaSRequestMap";

/**
 * Endpoint
 *
 * A collection of read/update/delete requests which corresponds to a FidesDataset collection (by name)
 */
export type Endpoint = {
  /**
   * Name
   */
  name: string;
  requests: SaaSRequestMap;
  /**
   * Skip Processing
   */
  skip_processing?: boolean;
  /**
   * After
   */
  after?: Array<string>;
  /**
   * Erase After
   */
  erase_after?: Array<string>;
};
