// This file is auto-generated by @hey-api/openapi-ts

/**
 * EnforcementLevel
 *
 * Enum is not formalized in the DB because it may be subject to frequent change
 */
export enum EnforcementLevel {
  FRONTEND = "frontend",
  SYSTEM_WIDE = "system_wide",
  NOT_APPLICABLE = "not_applicable",
}
