// This file is auto-generated by @hey-api/openapi-ts

/**
 * EntraMonitorConfig
 *
 * Entra (Identity Provider) monitor configuration.
 *
 * Simplified seed input for creating a Microsoft Entra ID discovery monitor.
 * See also: IdentityProviderMonitorConfig, EditableMonitorConfig.
 */
export type EntraMonitorConfig = {
  /**
   * Tenant Id
   *
   * Entra tenant ID
   */
  tenant_id: string;
  /**
   * Client Id
   *
   * Entra OAuth2 client ID
   */
  client_id: string;
  /**
   * Client Secret
   *
   * Entra OAuth2 client secret
   */
  client_secret: string;
  /**
   * Name
   *
   * Monitor name
   */
  name?: string;
  /**
   * Execute After Creation
   *
   * Execute the monitor after creation
   */
  execute_after_creation?: boolean;
};
