// This file is auto-generated by @hey-api/openapi-ts

import { PromptType } from "./PromptType";

/**
 * ExecutePromptRequest
 *
 * Request to execute a prompt against the LLM.
 */
export type ExecutePromptRequest = {
  /**
   * Prompt
   */
  prompt: string;
  /**
   * Model
   */
  model?: string | null;
  prompt_type?: PromptType | null;
};
