// This file is auto-generated by @hey-api/openapi-ts

/**
 * ExecutePromptResponse
 *
 * Response from executing a prompt.
 */
export type ExecutePromptResponse = {
  /**
   * Model
   */
  model: string;
  /**
   * Response Text
   */
  response_text: string;
  /**
   * Raw Response
   */
  raw_response?: {
    [key: string]: unknown;
  };
};
