// This file is auto-generated by @hey-api/openapi-ts

import { ComponentType } from "./ComponentType";
import type { ExperienceTranslationCreate } from "./ExperienceTranslationCreate";
import { Layer1ButtonOption } from "./Layer1ButtonOption";
import type { MinimalProperty } from "./MinimalProperty";
import { PrivacyNoticeRegion } from "./PrivacyNoticeRegion";
import { RejectAllMechanism } from "./RejectAllMechanism";

/**
 * ExperienceConfigCreate
 *
 * Schema for creating Experience Configs via the API
 *
 * Privacy notices are specified as a list of ids instead of keys like the template
 */
export type ExperienceConfigCreate = {
  /**
   * Name
   */
  name: string;
  /**
   * Disabled
   */
  disabled?: boolean | null;
  /**
   * Dismissable
   */
  dismissable?: boolean | null;
  /**
   * Show Layer1 Notices
   */
  show_layer1_notices?: boolean | null;
  layer1_button_options?: Layer1ButtonOption | null;
  /**
   * Allow Language Selection
   */
  allow_language_selection?: boolean | null;
  /**
   * Auto Detect Language
   */
  auto_detect_language?: boolean | null;
  /**
   * Auto Subdomain Cookie Deletion
   */
  auto_subdomain_cookie_deletion?: boolean | null;
  /**
   * Cookie Deletion Based On Host Domain
   */
  cookie_deletion_based_on_host_domain?: boolean | null;
  /**
   * Resurface behavior options (fidesplus)
   */
  resurface_behavior?: Array<"reject" | "dismiss">;
  /**
   * Allow Vendor Asset Disclosure
   */
  allow_vendor_asset_disclosure?: boolean | null;
  /**
   * Asset Disclosure Include Types
   */
  asset_disclosure_include_types?: Array<string> | null;
  /**
   * Regions
   */
  regions?: Array<PrivacyNoticeRegion>;
  /**
   * Tcf Configuration Id
   */
  tcf_configuration_id?: string | null;
  component: ComponentType;
  /**
   * Determines the behavior of the reject all button
   */
  reject_all_mechanism?: RejectAllMechanism | null;
  /**
   * Privacy Notice Ids
   */
  privacy_notice_ids?: Array<string>;
  /**
   * Translations
   */
  translations?: Array<ExperienceTranslationCreate>;
  /**
   * Properties
   */
  properties?: Array<MinimalProperty>;
};
