// This file is auto-generated by @hey-api/openapi-ts

/**
 * ExperienceConfigDisabledResponse
 *
 * A minimal response for updating just whether an Experience Config is disabled
 */
export type ExperienceConfigDisabledResponse = {
  /**
   * Disabled
   */
  disabled: boolean;
  /**
   * Id
   */
  id: string;
};
