// This file is auto-generated by @hey-api/openapi-ts

import type { ExperienceTranslation } from "./ExperienceTranslation";
import { Layer1ButtonOption } from "./Layer1ButtonOption";
import type { MinimalProperty } from "./MinimalProperty";
import { PrivacyNoticeRegion } from "./PrivacyNoticeRegion";
import { RejectAllMechanism } from "./RejectAllMechanism";

/**
 * ExperienceConfigUpdate
 *
 * The schema to update an ExperienceConfig via the API.
 *
 * Note that component cannot be updated once its created.
 * Translations, regions, and privacy_notice_ids must be supplied or they will be removed.  They are
 * required in the request to hopefully make their removal intentional.
 *
 * Experience Config Updates are also re-validated with the ExperienceConfigCreate
 * schema after patch dry updates are applied.
 */
export type ExperienceConfigUpdate = {
  /**
   * Name
   */
  name?: string | null;
  /**
   * Disabled
   */
  disabled?: boolean | null;
  /**
   * Dismissable
   */
  dismissable?: boolean | null;
  /**
   * Show Layer1 Notices
   */
  show_layer1_notices?: boolean | null;
  layer1_button_options?: Layer1ButtonOption | null;
  /**
   * Allow Language Selection
   */
  allow_language_selection?: boolean | null;
  /**
   * Auto Detect Language
   */
  auto_detect_language?: boolean | null;
  /**
   * Auto Subdomain Cookie Deletion
   */
  auto_subdomain_cookie_deletion?: boolean | null;
  /**
   * Cookie Deletion Based On Host Domain
   */
  cookie_deletion_based_on_host_domain?: boolean | null;
  /**
   * Allow Vendor Asset Disclosure
   */
  allow_vendor_asset_disclosure?: boolean | null;
  /**
   * Asset Disclosure Include Types
   */
  asset_disclosure_include_types?: Array<string> | null;
  /**
   * Regions
   */
  regions: Array<PrivacyNoticeRegion>;
  /**
   * Tcf Configuration Id
   */
  tcf_configuration_id?: string | null;
  /**
   * Translations
   */
  translations: Array<ExperienceTranslation>;
  /**
   * Privacy Notice Ids
   */
  privacy_notice_ids: Array<string>;
  /**
   * Properties
   */
  properties: Array<MinimalProperty>;
  /**
   * Determines the behavior of the reject all button
   */
  reject_all_mechanism?: RejectAllMechanism | null;
};
