// This file is auto-generated by @hey-api/openapi-ts

/**
 * ExternalUserCreateRequest
 *
 * Data required to create an external respondent user
 */
export type ExternalUserCreateRequest = {
  /**
   * Username
   */
  username: string;
  /**
   * Email Address
   */
  email_address: string;
  /**
   * First Name
   */
  first_name?: string | null;
  /**
   * Last Name
   */
  last_name?: string | null;
};
