// This file is auto-generated by @hey-api/openapi-ts

/**
 * CustomPrivacyRequestField
 *
 * Schema for custom privacy request fields.
 */
export type fides__api__schemas__redis_cache__CustomPrivacyRequestField = {
  /**
   * Label
   */
  label: string;
  /**
   * Value
   */
  value: number | string | Array<number | string>;
};
