// This file is auto-generated by @hey-api/openapi-ts

import { ConsentMethod } from "./ConsentMethod";

/**
 * FidesConsentMetaCreate
 *
 * Privacy preference metadata fields defined by Fides.
 */
export type FidesConsentMetaCreate = {
  /**
   * Geography
   *
   * User geography, from the request
   */
  geography?: string | null;
  /**
   * Method of consent preference
   */
  method?: ConsentMethod | null;
  /**
   * Request Origin
   *
   * The request origin from the request headers
   */
  request_origin?: string | null;
  /**
   * Truncated Ip Address
   *
   * Truncated IP address for reporting
   */
  truncated_ip_address?: string | null;
  /**
   * Recorded Url
   *
   * The referrer from the request headers
   */
  recorded_url?: string | null;
  /**
   * User Agent
   *
   * The user agent from the request headers
   */
  user_agent?: string | null;
  /**
   * Property Id
   *
   * The Fides property ID
   */
  property_id?: string | null;
};
