// This file is auto-generated by @hey-api/openapi-ts

import { ConsentMethod } from "./ConsentMethod";
import { HistoricalOnlyReason } from "./HistoricalOnlyReason";

/**
 * FidesConsentMetaResponse
 *
 * Fides metadata for the consent request.
 */
export type FidesConsentMetaResponse = {
  /**
   * Geography
   *
   * User geography, from the request
   */
  geography?: string | null;
  /**
   * Method of consent preference
   */
  method?: ConsentMethod | null;
  /**
   * Request Origin
   *
   * The request origin from the request headers
   */
  request_origin?: string | null;
  /**
   * Truncated Ip Address
   *
   * Truncated IP address for reporting
   */
  truncated_ip_address?: string | null;
  /**
   * Recorded Url
   *
   * The referrer from the request headers
   */
  recorded_url?: string | null;
  /**
   * User Agent
   *
   * The user agent from the request headers
   */
  user_agent?: string | null;
  /**
   * Property Id
   *
   * The Fides property ID
   */
  property_id?: string | null;
  /**
   * Created At
   *
   * The timestamp when consent was created in Fides
   */
  created_at: string;
  /**
   * Updated At
   *
   * The timestamp when the record was last updated (e.g. when is_latest is flipped to False)
   */
  updated_at?: string | null;
  /**
   * If set, indicates this record was inserted as a historical record and was never the current/latest preference. The value describes the reason.
   */
  historical_only_reason?: HistoricalOnlyReason | null;
};
