// This file is auto-generated by @hey-api/openapi-ts

import type { fides__api__schemas__privacy_center_config__ConsentConfig } from "./fides__api__schemas__privacy_center_config__ConsentConfig";
import type { PolicyUnavailableMessages } from "./PolicyUnavailableMessages";
import type { PrivacyCenterLink } from "./PrivacyCenterLink";
import type { PrivacyRequestOption } from "./PrivacyRequestOption";

/**
 * PrivacyCenterConfig
 *
 * NOTE: Add to this schema with care. Any fields added to
 * this response schema will be exposed in public-facing
 * (i.e. unauthenticated) API responses. If a field has
 * sensitive information, it should NOT be added to this schema!
 */
export type fides__api__schemas__privacy_center_config__PrivacyCenterConfig = {
  /**
   * Title
   */
  title: string;
  /**
   * Description
   */
  description: string;
  /**
   * Description Subtext
   */
  description_subtext?: Array<string> | null;
  /**
   * Addendum
   */
  addendum?: Array<string> | null;
  /**
   * Server Url Development
   */
  server_url_development?: string | null;
  /**
   * Server Url Production
   */
  server_url_production?: string | null;
  /**
   * Logo Path
   */
  logo_path?: string | null;
  /**
   * Logo Url
   */
  logo_url?: string | null;
  /**
   * Favicon Path
   */
  favicon_path?: string | null;
  /**
   * Page Title
   */
  page_title?: string | null;
  /**
   * Actions
   */
  actions?: Array<PrivacyRequestOption>;
  /**
   * Includeconsent
   */
  includeConsent?: boolean | null;
  consent: fides__api__schemas__privacy_center_config__ConsentConfig;
  /**
   * Privacy Policy Url
   */
  privacy_policy_url?: string | null;
  /**
   * Privacy Policy Url Text
   */
  privacy_policy_url_text?: string | null;
  /**
   * Links
   */
  links?: Array<PrivacyCenterLink>;
  policy_unavailable_messages?: PolicyUnavailableMessages | null;
};
