// This file is auto-generated by @hey-api/openapi-ts

import type { VisibilityCondition } from "./VisibilityCondition";

/**
 * CustomPrivacyRequestField
 *
 * Regular custom privacy request field supporting text, select, and multiselect types
 */
export type fides__api__schemas__privacy_center_config__CustomPrivacyRequestField =
  {
    /**
     * Label
     */
    label: string;
    /**
     * Required
     */
    required?: boolean | null;
    /**
     * Default Value
     */
    default_value?: string | null;
    /**
     * Hidden
     */
    hidden?: boolean | null;
    /**
     * Query Param Key
     */
    query_param_key?: string | null;
    /**
     * Placeholder
     */
    placeholder?: string | null;
    /**
     * Visible When
     */
    visible_when?: Array<VisibilityCondition> | null;
    /**
     * Field Type
     */
    field_type?: "text" | "select" | "multiselect" | "radio" | null;
    /**
     * Options
     */
    options?: Array<string> | null;
  };
