// This file is auto-generated by @hey-api/openapi-ts

/**
 * PrivacyCenterConfig
 */
export type fides__api__schemas__application_config__PrivacyCenterConfig = {
  /**
   * Url
   */
  url?: string | null;
};
