/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

/**
 * An enumeration.
 */
export enum FidesDataCategory {
  USER_PAYMENT = "user.payment",
  USER_PAYMENT_FINANCIAL_ACCOUNT_NUMBER = "user.payment.financial_account_number",
  SYSTEM = "system",
  SYSTEM_AUTHENTICATION = "system.authentication",
  SYSTEM_OPERATIONS = "system.operations",
  USER = "user",
  USER_BIOMETRIC = "user.biometric",
  USER_BIOMETRIC_HEALTH = "user.biometric_health",
  USER_BROWSING_HISTORY = "user.browsing_history",
  USER_DEMOGRAPHIC = "user.demographic",
  USER_CONTACT = "user.contact",
  USER_CONTACT_ADDRESS = "user.contact.address",
  USER_DEVICE = "user.device",
  USER_DEVICE_COOKIE_ID = "user.device.cookie_id",
  USER_DEVICE_DEVICE_ID = "user.device.device_id",
  USER_DEVICE_IP_ADDRESS = "user.device.ip_address",
  USER_GENDER = "user.gender",
  USER_LOCATION = "user.location",
  USER_MEDIA_CONSUMPTION = "user.media_consumption",
  USER_NON_SPECIFIC_AGE = "user.non_specific_age",
  USER_OBSERVED = "user.observed",
  USER_PROFILING = "user.profiling",
  USER_RACE = "user.race",
  USER_RELIGIOUS_BELIEF = "user.religious_belief",
  USER_SEARCH_HISTORY = "user.search_history",
  USER_SEXUAL_ORIENTATION = "user.sexual_orientation",
  USER_SOCIAL = "user.social",
  USER_TELEMETRY = "user.telemetry",
  USER_UNIQUE_ID = "user.unique_id",
  USER_USER_SENSOR = "user.user_sensor",
  USER_ORGANIZATION = "user.organization",
  USER_WORKPLACE = "user.workplace",
  USER_SENSOR = "user.sensor",
  USER_CHILDRENS = "user.childrens",
  USER_CONTACT_ADDRESS_CITY = "user.contact.address.city",
  USER_CONTACT_ADDRESS_COUNTRY = "user.contact.address.country",
  USER_CONTACT_EMAIL = "user.contact.email",
  USER_CONTACT_PHONE_NUMBER = "user.contact.phone_number",
  USER_CONTACT_ADDRESS_POSTAL_CODE = "user.contact.address.postal_code",
  USER_CONTACT_ADDRESS_STATE = "user.contact.address.state",
  USER_CONTACT_ADDRESS_STREET = "user.contact.address.street",
  USER_CREDENTIALS = "user.credentials",
  USER_CREDENTIALS_BIOMETRIC_CREDENTIALS = "user.credentials.biometric_credentials",
  USER_CREDENTIALS_PASSWORD = "user.credentials.password",
  USER_DATE_OF_BIRTH = "user.date_of_birth",
  USER_FINANCIAL = "user.financial",
  USER_FINANCIAL_ACCOUNT_NUMBER = "user.financial.account_number",
  USER_GENETIC = "user.genetic",
  USER_GOVERNMENT_ID = "user.government_id",
  USER_GOVERNMENT_ID_DRIVERS_LICENSE_NUMBER = "user.government_id.drivers_license_number",
  USER_GOVERNMENT_ID_NATIONAL_IDENTIFICATION_NUMBER = "user.government_id.national_identification_number",
  USER_GOVERNMENT_ID_PASSPORT_NUMBER = "user.government_id.passport_number",
  USER_HEALTH_AND_MEDICAL = "user.health_and_medical",
  USER_JOB_TITLE = "user.job_title",
  USER_NAME = "user.name",
  USER_POLITICAL_OPINION = "user.political_opinion",
}
