// This file is auto-generated by @hey-api/openapi-ts

/**
 * KeyfileCreds
 *
 * Schema that holds BigQuery keyfile key/vals
 */
export type fidesplus__cls__schemas__connection_configuration__connection_secrets_bigquery__KeyfileCreds =
  {
    /**
     * Type
     */
    type?: string | null;
    /**
     * Project Id
     */
    project_id: string;
    /**
     * Private Key Id
     */
    private_key_id?: string | null;
    /**
     * Private Key
     */
    private_key?: string | null;
    /**
     * Client Email
     */
    client_email?: string | null;
    /**
     * Client Id
     */
    client_id?: string | null;
    /**
     * Auth Uri
     */
    auth_uri?: string | null;
    /**
     * Token Uri
     */
    token_uri?: string | null;
    /**
     * Auth Provider X509 Cert Url
     */
    auth_provider_x509_cert_url?: string | null;
    /**
     * Client X509 Cert Url
     */
    client_x509_cert_url?: string | null;
  };
