// This file is auto-generated by @hey-api/openapi-ts

/**
 * IdentityValue
 *
 * Represents an identity value with a label in API responses.
 *
 * The value field accepts MultiValue types which match what LabeledIdentity supports:
 * - int
 * - str
 * - List[Union[int, str]]
 *
 * This allows the schema to accept list values that were previously causing
 * validation errors.
 */
export type fides__api__schemas__privacy_request__IdentityValue = {
  /**
   * Label
   */
  label: string;
  /**
   * Value
   */
  value?: number | string | Array<number | string> | null;
};
