// This file is auto-generated by @hey-api/openapi-ts

/**
 * FidesConsentScopes
 *
 * Scopes with special purposes defined by Fides.
 */
export type FidesConsentScopes = {
  /**
   * Property Id
   *
   * The Fides property ID
   */
  property_id?: string | null;
};
