// This file is auto-generated by @hey-api/openapi-ts

import type { RangeEntry } from "./RangeEntry";
import { TCFRestrictionType } from "./TCFRestrictionType";
import { TCFVendorRestriction } from "./TCFVendorRestriction";

/**
 * TCFPublisherRestrictionResponse
 *
 * Schema for TCF Publisher Restriction responses
 */
export type fidesplus__api__schemas__tcf_publisher_restrictions__TCFPublisherRestrictionResponse =
  {
    /**
     * Purpose Id
     *
     * The ID of the purpose this restriction applies to
     */
    purpose_id: number;
    /**
     * The type of restriction
     */
    restriction_type: TCFRestrictionType;
    /**
     * The type of vendor restriction
     */
    vendor_restriction: TCFVendorRestriction;
    /**
     * Range Entries
     *
     * List of vendor ranges this restriction applies to
     */
    range_entries?: Array<RangeEntry>;
    /**
     * Id
     *
     * The unique identifier of the TCF Publisher Restriction
     */
    id: string;
    /**
     * Tcf Configuration Id
     *
     * The ID of the TCF Configuration this restriction belongs to
     */
    tcf_configuration_id: string;
  };
