// This file is auto-generated by @hey-api/openapi-ts

/**
 * ConstraintType
 *
 * Types of RBAC constraints as defined by the NIST RBAC standard (ANSI/INCITS 359-2004).
 */
export enum fides__api__models__rbac__rbac_constraint__ConstraintType {
  STATIC_SOD = "static_sod",
  DYNAMIC_SOD = "dynamic_sod",
  CARDINALITY = "cardinality",
}
