// This file is auto-generated by @hey-api/openapi-ts

/**
 * FieldMaskingStrategyOverride
 *
 * Overrides field-level masking strategies.
 */
export type FieldMaskingStrategyOverride = {
  /**
   * Strategy
   */
  strategy: string;
  /**
   * Configuration
   */
  configuration?: {
    [key: string]: unknown;
  } | null;
};
