// This file is auto-generated by @hey-api/openapi-ts

/**
 * FiltersResponse
 */
export type FiltersResponse = {
  /**
   * Consumers
   */
  consumers: Array<string>;
  /**
   * Policies
   */
  policies: Array<string>;
  /**
   * Datasets
   */
  datasets: Array<string>;
  /**
   * Data Uses
   */
  data_uses: Array<string>;
  /**
   * Controls
   */
  controls: Array<string>;
};
