// This file is auto-generated by @hey-api/openapi-ts

/**
 * GenerateTypes
 *
 * Generate Type Enum to capture the discrete possible values
 * for a valid type of resource to generate.
 */
export enum GenerateTypes {
  SYSTEMS = "systems",
  DATASETS = "datasets",
}
