// This file is auto-generated by @hey-api/openapi-ts

/**
 * GoogleCloudSQLIPType
 *
 * Enum for Google Cloud SQL IP types
 */
export enum GoogleCloudSQLIPType {
  PUBLIC = "public",
  PRIVATE = "private",
  PSC = "psc",
}
