// This file is auto-generated by @hey-api/openapi-ts

import type { fides__api__schemas__connection_configuration__connection_secrets_google_cloud_sql_mysql__KeyfileCreds } from "./fides__api__schemas__connection_configuration__connection_secrets_google_cloud_sql_mysql__KeyfileCreds";
import { GoogleCloudSQLIPType } from "./GoogleCloudSQLIPType";

/**
 * GoogleCloudSQLMySQLDocsSchema
 *
 * Google Cloud SQL MySQL Secrets Schema for API Docs
 */
export type GoogleCloudSQLMySQLDocsSchema = {
  /**
   * DB IAM user
   *
   * example: service-account@test.iam.gserviceaccount.com
   */
  db_iam_user: string;
  /**
   * Instance connection name
   *
   * example: friendly-tower-424214-n8:us-central1:test-ethyca
   */
  instance_connection_name: string;
  /**
   * Database name
   */
  dbname: string;
  /**
   * Keyfile creds
   *
   * The contents of the key file that contains authentication credentials for a service account in GCP.
   */
  keyfile_creds: fides__api__schemas__connection_configuration__connection_secrets_google_cloud_sql_mysql__KeyfileCreds;
  /**
   * IP type
   *
   * Specify the IP Address type required for your database (defaults to public). See the Google Cloud documentation for more information about connection options: https://cloud.google.com/sql/docs/postgres/connect-overview
   */
  ip_type?: GoogleCloudSQLIPType | null;
};
