// This file is auto-generated by @hey-api/openapi-ts

import { GPPUSApproach } from "./GPPUSApproach";

/**
 * GPPApplicationConfig
 */
export type GPPApplicationConfig = {
  us_approach?: GPPUSApproach | null;
  /**
   * Mspa Service Provider Mode
   */
  mspa_service_provider_mode?: boolean | null;
  /**
   * Mspa Opt Out Option Mode
   */
  mspa_opt_out_option_mode?: boolean | null;
  /**
   * Mspa Covered Transactions
   */
  mspa_covered_transactions?: boolean | null;
  /**
   * Enable Tcfeu String
   */
  enable_tcfeu_string?: boolean | null;
};
