// This file is auto-generated by @hey-api/openapi-ts

import type { GPPMechanismMapping } from "./GPPMechanismMapping";
import { PrivacyNoticeRegion } from "./PrivacyNoticeRegion";

/**
 * GPPFieldMapping
 */
export type GPPFieldMapping = {
  region: PrivacyNoticeRegion;
  /**
   * Notice
   */
  notice?: Array<string> | null;
  /**
   * Mechanism
   */
  mechanism?: Array<GPPMechanismMapping> | null;
};
