// This file is auto-generated by @hey-api/openapi-ts

/**
 * GPPMechanismMapping
 */
export type GPPMechanismMapping = {
  /**
   * Field
   */
  field: string;
  /**
   * Not Available
   */
  not_available: string;
  /**
   * Opt Out
   */
  opt_out: string;
  /**
   * Not Opt Out
   */
  not_opt_out: string;
};
