// This file is auto-generated by @hey-api/openapi-ts

/**
 * GPPMobileData
 *
 * Pre-parsed GPP data and GPP string for a CMP SDK
 */
export type GPPMobileData = {
  /**
   * Iabgpp Hdr Version
   *
   * GPP version
   */
  IABGPP_HDR_Version: string;
  /**
   * Iabgpp Hdr Sections
   *
   * List of section IDs
   */
  IABGPP_HDR_Sections: string;
  /**
   * Iabgpp Hdr Gppstring
   *
   * Full consent string in its encoded form
   */
  IABGPP_HDR_GppString: string;
  /**
   * Iabgpp Gppsid
   *
   * Section ID(s) considered to be in force. Multiple IDs are separated by underscores
   */
  IABGPP_GppSID: string;
  [key: string]: unknown | string | string;
};
