// This file is auto-generated by @hey-api/openapi-ts

import type { HTTPValidationError } from "./HTTPValidationError";

export type healthHealthGetErrors = {
  /**
   * Validation Error
   */
  422: HTTPValidationError;
  /**
   * Service Unavailable
   */
  503: unknown;
};
