// This file is auto-generated by @hey-api/openapi-ts

import type { healthHealthGetResponses } from "./healthHealthGetResponses";

export type healthHealthGetResponse =
  healthHealthGetResponses[keyof healthHealthGetResponses];
