// This file is auto-generated by @hey-api/openapi-ts

export type healthHealthGetData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Include Cache
     */
    include_cache?: boolean | null;
  };
  url: "/health";
};
