// This file is auto-generated by @hey-api/openapi-ts

import type { ValidationError } from "./ValidationError";

/**
 * HTTPValidationError
 */
export type HTTPValidationError = {
  /**
   * Detail
   */
  detail?: Array<ValidationError>;
};
