// This file is auto-generated by @hey-api/openapi-ts

/**
 * HTTPMethod
 *
 * Enum to represent HTTP Methods
 */
export enum HTTPMethod {
  GET = "GET",
  POST = "POST",
  PATCH = "PATCH",
  PUT = "PUT",
  DELETE = "DELETE",
  OPTIONS = "OPTIONS",
  HEAD = "HEAD",
}
