// This file is auto-generated by @hey-api/openapi-ts

/**
 * IdentityDefinitionType
 *
 * Enum for the type of identity
 */
export enum IdentityDefinitionType {
  EMAIL = "email",
  PHONE_NUMBER = "phone_number",
  UUID = "uuid",
  STRING = "string",
  INTEGER = "integer",
}
