// This file is auto-generated by @hey-api/openapi-ts

import type { BigQueryMonitorParams } from "./BigQueryMonitorParams";
import type { DynamoDBMonitorParams } from "./DynamoDBMonitorParams";
import { IdentityProvider } from "./IdentityProvider";
import type { MonitorClassifyParams } from "./MonitorClassifyParams";
import { MonitorFrequency } from "./MonitorFrequency";
import type { S3MonitorParams } from "./S3MonitorParams";
import type { TestMonitorParams } from "./TestMonitorParams";
import type { TestWebsiteMonitorParams } from "./TestWebsiteMonitorParams";
import type { WebsiteMonitorParams } from "./WebsiteMonitorParams";

/**
 * IdentityProviderMonitorConfig
 *
 * Configuration for Identity Provider discovery monitors.
 */
export type IdentityProviderMonitorConfig = {
  /**
   * Name
   */
  name: string;
  /**
   * Key
   */
  key?: string | null;
  /**
   * Connection Config Key
   */
  connection_config_key: string;
  /**
   * Parameters for classification of discovered resources
   */
  classify_params?: MonitorClassifyParams | null;
  /**
   * Datasource Params
   *
   * The datasource specific parameters, specified in a dictionary
   */
  datasource_params?:
    | {
        [key: string]: unknown;
      }
    | DynamoDBMonitorParams
    | S3MonitorParams
    | WebsiteMonitorParams
    | TestWebsiteMonitorParams
    | TestMonitorParams
    | BigQueryMonitorParams
    | null;
  /**
   * Databases
   *
   * The databases that the monitor is scoped to actively monitor
   */
  databases?: Array<string>;
  /**
   * Execution Start Date
   */
  execution_start_date?: string | null;
  execution_frequency?: MonitorFrequency | null;
  /**
   * Excluded Databases
   *
   * The databases that the monitor should exclude from monitoring
   */
  excluded_databases?: Array<string>;
  /**
   * Enabled
   *
   * Whether the monitor is enabled for scheduled execution
   */
  enabled?: boolean;
  /**
   * Shared Config Id
   *
   * Reference to a shared monitor configuration
   */
  shared_config_id?: string | null;
  /**
   * Stewards
   *
   * List of user IDs to set as stewards for this monitor
   */
  stewards?: Array<string>;
  /**
   * Identity Provider type (currently only 'okta' is supported)
   */
  provider?: IdentityProvider;
};
