// This file is auto-generated by @hey-api/openapi-ts

/**
 * IdentityGroupProviderResponse
 */
export type IdentityGroupProviderResponse = {
  /**
   * Id
   */
  id: string;
  /**
   * Key
   */
  key: string;
  /**
   * Name
   */
  name: string;
  /**
   * Provider Type
   */
  provider_type: string;
  /**
   * Connection Config Key
   */
  connection_config_key: string;
  /**
   * Enabled
   */
  enabled: boolean;
  /**
   * Created At
   */
  created_at: string;
  /**
   * Updated At
   */
  updated_at: string;
};
