// This file is auto-generated by @hey-api/openapi-ts

/**
 * IdentityGroupProviderCreate
 */
export type IdentityGroupProviderCreate = {
  /**
   * Key
   */
  key: string;
  /**
   * Name
   */
  name: string;
  /**
   * Provider Type
   */
  provider_type: string;
  /**
   * Connection Config Key
   */
  connection_config_key: string;
  /**
   * Enabled
   */
  enabled?: boolean;
};
