// This file is auto-generated by @hey-api/openapi-ts

import { ApplicationStatus } from "./ApplicationStatus";
import { AuthenticationProtocol } from "./AuthenticationProtocol";
import { VendorMatchConfidence } from "./VendorMatchConfidence";

/**
 * IdentityProviderApplicationMetadata
 *
 * Application metadata from Identity Providers.
 *
 * Stored in StagedResource.meta JSONB column. Matches frontend OktaAppMetadata
 * interface for display in Action Center tables.
 */
export type IdentityProviderApplicationMetadata = {
  /**
   * Authentication protocol type
   */
  app_type?: AuthenticationProtocol | null;
  /**
   * Application lifecycle status
   */
  status?: ApplicationStatus | null;
  /**
   * Created
   *
   * ISO 8601 timestamp when application was created
   */
  created?: string | null;
  /**
   * Sign On Url
   *
   * SSO login URL
   */
  sign_on_url?: string | null;
  /**
   * Confidence level of vendor match from Compass service
   */
  vendor_match_confidence?: VendorMatchConfidence | null;
  /**
   * Domain
   *
   * Extracted domain for Brandfetch logo lookup
   */
  domain?: string | null;
  /**
   * System Type
   *
   * Application template name from IDP (e.g. oidc_client, google, salesforce)
   */
  system_type?: string | null;
  /**
   * Description
   *
   * System-generated description of the application
   */
  description?: string | null;
};
