// This file is auto-generated by @hey-api/openapi-ts

/**
 * IdentityBase
 *
 * The minimum fields required to represent an identity.
 */
export type IdentityBase = {
  /**
   * Phone Number
   */
  phone_number?: string | null;
  /**
   * Email
   */
  email?: string | null;
};
