// This file is auto-generated by @hey-api/openapi-ts

/**
 * IdentityVerificationConfigResponse
 *
 * Response for identity verification config info
 */
export type IdentityVerificationConfigResponse = {
  /**
   * Identity Verification Required
   */
  identity_verification_required: boolean;
  /**
   * Disable Consent Identity Verification
   */
  disable_consent_identity_verification: boolean;
  /**
   * Valid Email Config Exists
   */
  valid_email_config_exists: boolean;
};
