// This file is auto-generated by @hey-api/openapi-ts

import { IdentityDefinitionType } from "./IdentityDefinitionType";

/**
 * IdentityDefinitionCreate
 *
 * Schema for creating an identity definition.
 */
export type IdentityDefinitionCreate = {
  /**
   * Identity Key
   */
  identity_key: string;
  /**
   * Name
   */
  name: string;
  /**
   * Description
   */
  description?: string | null;
  type: IdentityDefinitionType;
  /**
   * Case Sensitive
   */
  case_sensitive?: boolean;
};
