// This file is auto-generated by @hey-api/openapi-ts

import { DiffStatus } from "./DiffStatus";
import { IDPActionType } from "./IDPActionType";

/**
 * IDPAllowedActionsResponse
 *
 * Response for the IDP allowed actions endpoint.
 */
export type IDPAllowedActionsResponse = {
  /**
   * Allowed Actions
   *
   * List of action types that are allowed for the filtered resources
   */
  allowed_actions: Array<IDPActionType>;
  /**
   * Diff Statuses With Counts
   *
   * Map of diff_status to count of resources with that status
   */
  diff_statuses_with_counts: {
    [key in DiffStatus]?: number;
  };
  /**
   * Resource Count
   *
   * Total number of resources matching the current filters
   */
  resource_count: number;
};
