// This file is auto-generated by @hey-api/openapi-ts

import { DiffStatus } from "./DiffStatus";

/**
 * IDPMonitorResourcesFilter
 *
 * Filter schema for IDP monitor resources that includes search and dynamic filters.
 *
 * Extends IDPMonitorResourcesDynamicFilters to include the search parameter.
 * This ensures that changes to IDPMonitorResourcesDynamicFilters are automatically
 * reflected in this schema, preventing drift.
 */
export type IDPMonitorResourcesFilter = {
  /**
   * Diff Status
   */
  diff_status?: Array<DiffStatus> | null;
  /**
   * Vendor Id
   */
  vendor_id?: Array<string> | null;
  /**
   * Data Uses
   */
  data_uses?: Array<string> | null;
  /**
   * Search
   *
   * Search query to filter resources by name
   */
  search?: string | null;
};
