// This file is auto-generated by @hey-api/openapi-ts

import { DiffStatus } from "./DiffStatus";

/**
 * IDPMonitorResourcesDynamicFilters
 */
export type IDPMonitorResourcesDynamicFilters = {
  /**
   * Diff Status
   */
  diff_status?: Array<DiffStatus> | null;
  /**
   * Vendor Id
   */
  vendor_id?: Array<string> | null;
  /**
   * Data Uses
   */
  data_uses?: Array<string> | null;
};
