// This file is auto-generated by @hey-api/openapi-ts

/**
 * IngestGapEntry
 *
 * A coverage gap for a single ingested query.
 */
export type IngestGapEntry = {
  /**
   * Gap Type
   */
  gap_type: string;
  /**
   * Identifier
   */
  identifier: string;
  /**
   * Reason
   */
  reason: string;
};
