// This file is auto-generated by @hey-api/openapi-ts

/**
 * IngestTableRef
 *
 * A table reference from a query log entry.
 */
export type IngestTableRef = {
  /**
   * Project
   */
  project?: string;
  /**
   * Dataset
   */
  dataset?: string;
  /**
   * Table
   */
  table?: string;
};
