// This file is auto-generated by @hey-api/openapi-ts

import type { IngestQueryIdentity } from "./IngestQueryIdentity";
import type { IngestTableRef } from "./IngestTableRef";

/**
 * IngestQueryLogEntry
 *
 * A single query log entry for direct ingestion.
 */
export type IngestQueryLogEntry = {
  identity: IngestQueryIdentity;
  /**
   * Query Text
   */
  query_text?: string;
  /**
   * Statement Type
   */
  statement_type?: string;
  /**
   * Referenced Tables
   */
  referenced_tables?: Array<IngestTableRef>;
  /**
   * Timestamp
   */
  timestamp?: string | null;
  /**
   * External Job Id
   */
  external_job_id?: string | null;
};
