// This file is auto-generated by @hey-api/openapi-ts

/**
 * IngestTableRef
 *
 * A table reference from a query log entry.
 */
export type IngestTableRef = {
  /**
   * Catalog
   */
  catalog?: string;
  /**
   * Schema
   */
  schema?: string;
  /**
   * Table
   */
  table?: string;
};
