// This file is auto-generated by @hey-api/openapi-ts

/**
 * IngestQueryIdentity
 *
 * Who ran this query.
 */
export type IngestQueryIdentity = {
  /**
   * User
   */
  user: string;
  /**
   * Role
   */
  role?: string | null;
  /**
   * Service Account
   */
  service_account?: string | null;
};
