// This file is auto-generated by @hey-api/openapi-ts

import type { IngestGapEntry } from "./IngestGapEntry";

/**
 * IngestResultEntry
 *
 * Result for a single ingested query.
 */
export type IngestResultEntry = {
  /**
   * Query Id
   */
  query_id: string;
  /**
   * User Identity
   */
  user_identity: string;
  /**
   * Consumer Name
   */
  consumer_name?: string | null;
  /**
   * Datasets
   */
  datasets: Array<string>;
  /**
   * Is Compliant
   */
  is_compliant: boolean;
  /**
   * Violations
   */
  violations?: Array<string>;
  /**
   * Gaps
   */
  gaps?: Array<IngestGapEntry>;
};
