// This file is auto-generated by @hey-api/openapi-ts

import type { IngestQueryLogEntry } from "./IngestQueryLogEntry";

/**
 * IngestRequest
 *
 * Request body for the query log ingest endpoint.
 *
 * Accepts raw query log entries and optional purpose mappings,
 * runs them through the PBAC engine, and persists violations.
 */
export type IngestRequest = {
  /**
   * Entries
   */
  entries: Array<IngestQueryLogEntry>;
  /**
   * Dataset Purpose Map
   */
  dataset_purpose_map?: {
    [key: string]: Array<string>;
  };
};
