// This file is auto-generated by @hey-api/openapi-ts

/**
 * JiraTicketDocsSchema
 *
 * Jira Ticket Secrets Schema for API Docs
 */
export type JiraTicketDocsSchema = {
  /**
   * Access Token
   */
  access_token?: string | null;
  /**
   * Refresh Token
   */
  refresh_token?: string | null;
  /**
   * Token Expiry
   */
  token_expiry?: string | null;
  /**
   * Cloud Id
   */
  cloud_id?: string | null;
  /**
   * Site Url
   */
  site_url?: string | null;
  /**
   * Domain
   */
  domain?: string | null;
  /**
   * Username
   */
  username?: string | null;
  /**
   * Api Key
   */
  api_key?: string | null;
  [key: string]:
    | unknown
    | string
    | null
    | string
    | null
    | string
    | null
    | string
    | null
    | string
    | null
    | string
    | null
    | string
    | null
    | string
    | null
    | undefined;
};
