// This file is auto-generated by @hey-api/openapi-ts

/**
 * JiraTicketResult
 *
 * Result of creating or querying a Jira ticket.
 *
 * Returned by :class:`JiraClient` methods and used as an API response
 * schema for frontend consumption.
 */
export type JiraTicketResult = {
  /**
   * Ticket Id
   *
   * Jira issue numeric ID
   */
  ticket_id: string;
  /**
   * Ticket Key
   *
   * Jira issue key (e.g., 'PRIV-123')
   */
  ticket_key: string;
  /**
   * Ticket Url
   *
   * Full URL to the Jira issue
   */
  ticket_url: string;
  /**
   * Status
   *
   * Current Jira status name (e.g., 'To Do', 'Done')
   */
  status: string;
  /**
   * Status Category
   *
   * Jira status category key (e.g., 'new', 'done')
   */
  status_category?: string | null;
  /**
   * Created At
   *
   * Ticket creation timestamp
   */
  created_at?: string | null;
  /**
   * Updated At
   *
   * Ticket last-update timestamp
   */
  updated_at?: string | null;
};
