// This file is auto-generated by @hey-api/openapi-ts

/**
 * JiraPreviewRequest
 *
 * Request body for the Jira ticket preview endpoint.
 *
 * All fields are optional — the endpoint falls back to saved
 * configuration from the connection's secrets.
 */
export type JiraPreviewRequest = {
  /**
   * Summary Template
   *
   * Override summary template; falls back to saved
   */
  summary_template?: string | null;
  /**
   * Description Template
   *
   * Override description template; falls back to saved
   */
  description_template?: string | null;
  /**
   * Privacy Request Id
   *
   * Load real privacy request data; falls back to sample values
   */
  privacy_request_id?: string | null;
};
