// This file is auto-generated by @hey-api/openapi-ts

/**
 * JiraCredentialLinkStatus
 *
 * Status of a credential link between a jira_ticket and SaaS connection.
 */
export type JiraCredentialLinkStatus = {
  /**
   * Is Linked
   *
   * Whether a SaaS credential link exists
   */
  is_linked: boolean;
  /**
   * Linked Saas Key
   *
   * Key of the linked SaaS connection
   */
  linked_saas_key?: string | null;
  /**
   * Linked Saas Name
   *
   * Display name of the linked SaaS connection
   */
  linked_saas_name?: string | null;
  /**
   * Sync Status
   *
   * Credential sync status: 'synced', 'stale', 'source_missing', or null
   */
  sync_status?: "synced" | "stale" | "source_missing" | null;
};
