// This file is auto-generated by @hey-api/openapi-ts

/**
 * JiraLinkRequest
 *
 * Request body for linking an existing Jira ticket to a privacy request.
 */
export type JiraLinkRequest = {
  /**
   * Ticket Key
   *
   * Jira issue key to link (e.g., 'PRIV-123')
   */
  ticket_key: string;
};
