// This file is auto-generated by @hey-api/openapi-ts

/**
 * JiraIssueType
 *
 * A Jira issue type available within a project.
 *
 * Returned by :meth:`JiraClient.list_issue_types` for issue type
 * discovery during integration configuration.
 */
export type JiraIssueType = {
  /**
   * Id
   *
   * Jira issue type ID
   */
  id: string;
  /**
   * Name
   *
   * Issue type name (e.g., 'Task', 'Story')
   */
  name: string;
  /**
   * Description
   *
   * Issue type description
   */
  description?: string | null;
  /**
   * Subtask
   *
   * Whether this is a subtask type
   */
  subtask?: boolean;
};
