// This file is auto-generated by @hey-api/openapi-ts

/**
 * Layer1ButtonOption
 *
 * Layer 1 button options - not formalized in the db
 */
export enum Layer1ButtonOption {
  ACKNOWLEDGE = "acknowledge",
  OPT_IN_OPT_OUT = "opt_in_opt_out",
  OPT_IN_ONLY = "opt_in_only",
  GPC_CONDITIONAL = "gpc_conditional",
}
