// This file is auto-generated by @hey-api/openapi-ts

/**
 * LinkedSystemInfo
 *
 * Minimal system info embedded in connection config list responses.
 */
export type LinkedSystemInfo = {
  /**
   * Fides Key
   */
  fides_key: string;
  /**
   * Name
   */
  name?: string | null;
};
