// This file is auto-generated by @hey-api/openapi-ts

import type { Location } from "./Location";
import type { LocationGroup } from "./LocationGroup";
import type { LocationRegulationBase } from "./LocationRegulationBase";

/**
 * LocationRegulationResponse
 */
export type LocationRegulationResponse = {
  /**
   * Locations
   */
  locations?: Array<Location>;
  /**
   * Location Groups
   */
  location_groups?: Array<LocationGroup>;
  /**
   * Regulations
   */
  regulations?: Array<LocationRegulationBase>;
};
