// This file is auto-generated by @hey-api/openapi-ts

import type { Selection } from "./Selection";

/**
 * LocationRegulationSelections
 */
export type LocationRegulationSelections = {
  /**
   * Locations
   */
  locations?: Array<Selection>;
  /**
   * Regulations
   */
  regulations?: Array<Selection>;
};
