// This file is auto-generated by @hey-api/openapi-ts

import { Continent } from "./Continent";

/**
 * LocationRegulationBase
 *
 * Base Location Regulation Schema
 */
export type LocationRegulationBase = {
  /**
   * Id
   */
  id: string;
  /**
   * Selected
   */
  selected?: boolean;
  /**
   * Name
   */
  name: string;
  continent?: Continent | null;
  /**
   * Default Selected
   */
  default_selected?: boolean;
};
