// This file is auto-generated by @hey-api/openapi-ts

/**
 * LogEntry
 *
 * Schema representing a single log entry
 */
export type LogEntry = {
  /**
   * Timestamp
   */
  timestamp: string;
  /**
   * Level
   */
  level: string;
  /**
   * Module Info
   */
  module_info: string;
  /**
   * Message
   */
  message: string;
};
