// This file is auto-generated by @hey-api/openapi-ts

/**
 * ManualWebhookData
 */
export type ManualWebhookData = {
  /**
   * Checked
   */
  checked: boolean;
  /**
   * Fields
   */
  fields: {
    [key: string]: unknown;
  };
};
