// This file is auto-generated by @hey-api/openapi-ts

/**
 * ManualTaskFieldType
 *
 * Enum for manual task field types.
 */
export enum ManualTaskFieldType {
  TEXT = "text",
  CHECKBOX = "checkbox",
  ATTACHMENT = "attachment",
}
