// This file is auto-generated by @hey-api/openapi-ts

import { ManualFieldRequestType } from "./ManualFieldRequestType";

/**
 * ManualFieldPrivacyRequest
 *
 * Privacy request snapshot with identity fields.
 */
export type ManualFieldPrivacyRequest = {
  /**
   * Id
   */
  id: string;
  /**
   * Days Left
   *
   * Days remaining until due date
   */
  days_left?: number | null;
  request_type: ManualFieldRequestType;
  /**
   * Subject Identities
   */
  subject_identities: {
    [key: string]: unknown;
  };
  /**
   * Custom Fields
   */
  custom_fields: {
    [key: string]: unknown;
  };
  /**
   * Custom Field Labels
   *
   * Mapping of custom field keys to their display labels
   */
  custom_field_labels?: {
    [key: string]: string;
  };
};
