// This file is auto-generated by @hey-api/openapi-ts

import type { Assignee } from "./Assignee";
import type { ManualTaskCondition } from "./ManualTaskCondition";
import type { ManualTaskField } from "./ManualTaskField";

/**
 * ManualTaskNode
 */
export type ManualTaskNode = {
  /**
   * Id
   */
  id: string;
  /**
   * Name
   */
  name: string;
  /**
   * Assignees
   */
  assignees?: Array<Assignee>;
  /**
   * Fields
   */
  fields?: Array<ManualTaskField>;
  /**
   * Conditions
   */
  conditions?: Array<ManualTaskCondition>;
  /**
   * Gates
   */
  gates?: Array<string>;
};
