// This file is auto-generated by @hey-api/openapi-ts

/**
 * ManualWebhookDocsSchema
 *
 * Manual Webhooks Secrets Schema for API Docs
 */
export type ManualWebhookDocsSchema = {
  [key: string]: unknown;
};
