// This file is auto-generated by @hey-api/openapi-ts

/**
 * ManualFieldStatus
 *
 * Status of a manual field relative to a particular task instance.
 */
export enum ManualFieldStatus {
  NEW = "new",
  COMPLETED = "completed",
  SKIPPED = "skipped",
}
