// This file is auto-generated by @hey-api/openapi-ts

/**
 * ManualWebhookField
 *
 * Schema to describe the attributes on a manual webhook field
 */
export type ManualWebhookField = {
  /**
   * Pii Field
   */
  pii_field: string;
  /**
   * Types
   */
  types?: Array<"string" | "file">;
  /**
   * Dsr Package Label
   */
  dsr_package_label?: string | null;
  /**
   * Data Categories
   */
  data_categories?: Array<string> | null;
};
