// This file is auto-generated by @hey-api/openapi-ts

/**
 * ManualAction
 *
 * Surface how to retrieve or mask data in a database-agnostic way
 *
 * - 'locators' are similar to the SQL "WHERE" information.
 * - 'get' contains a list of fields that should be retrieved from the source
 * - 'update' is a dictionary of fields and the replacement value/masking strategy
 */
export type ManualAction = {
  /**
   * Locators
   */
  locators: {
    [key: string]: unknown;
  };
  /**
   * Get
   */
  get: Array<string> | null;
  /**
   * Update
   */
  update: {
    [key: string]: unknown;
  } | null;
};
