// This file is auto-generated by @hey-api/openapi-ts

/**
 * MarkAllReadResponse
 *
 * Response for bulk mark-all-as-read.
 */
export type MarkAllReadResponse = {
  /**
   * Marked Count
   *
   * Number of notifications marked as read
   */
  marked_count: number;
};
