// This file is auto-generated by @hey-api/openapi-ts

/**
 * MaskingAPIResponse
 *
 * The API Response returned upon masking completion
 */
export type MaskingAPIResponse = {
  /**
   * Plain
   */
  plain: Array<string>;
  /**
   * Masked Values
   */
  masked_values: Array<unknown>;
};
