// This file is auto-generated by @hey-api/openapi-ts

import type { PolicyMaskingSpec } from "./PolicyMaskingSpec";

/**
 * MaskingAPIRequest
 *
 * The API Request for masking operations
 */
export type MaskingAPIRequest = {
  /**
   * Values
   */
  values: Array<string>;
  /**
   * Masking Strategy
   */
  masking_strategy: PolicyMaskingSpec | Array<PolicyMaskingSpec>;
  /**
   * Masking Strategies
   */
  masking_strategies?: Array<PolicyMaskingSpec>;
};
