// This file is auto-generated by @hey-api/openapi-ts

/**
 * MatchesEnum
 *
 * The MatchesEnum resource model.
 *
 * Determines how the listed resources are matched in the evaluation logic.
 */
export enum MatchesEnum {
  ANY = "ANY",
  ALL = "ALL",
  NONE = "NONE",
  OTHER = "OTHER",
}
