// This file is auto-generated by @hey-api/openapi-ts

/**
 * MessagingServiceDetailsTwilioEmail
 *
 * The details required to represent a Twilio email configuration.
 */
export type MessagingServiceDetailsTwilioEmail = {
  /**
   * Twilio Email From
   */
  twilio_email_from: string;
};
