// This file is auto-generated by @hey-api/openapi-ts

/**
 * MessagingServiceType
 *
 * Enum for messaging service type.
 */
export enum MessagingServiceType {
  MAILGUN = "mailgun",
  TWILIO_TEXT = "twilio_text",
  TWILIO_EMAIL = "twilio_email",
  MAILCHIMP_TRANSACTIONAL = "mailchimp_transactional",
  AWS_SES = "aws_ses",
}
