// This file is auto-generated by @hey-api/openapi-ts

import type { IdentityBase } from "./IdentityBase";

/**
 * MessagingTestBodyParams
 *
 * Body params required for testing messaging service
 */
export type MessagingTestBodyParams = {
  to_identity: IdentityBase;
};
