// This file is auto-generated by @hey-api/openapi-ts

import type { MinimalProperty } from "./MinimalProperty";

/**
 * MessagingTemplateWithPropertiesDetail
 */
export type MessagingTemplateWithPropertiesDetail = {
  /**
   * Id
   */
  id: string;
  /**
   * Type
   */
  type: string;
  /**
   * Is Enabled
   */
  is_enabled: boolean;
  /**
   * Properties
   */
  properties?: Array<MinimalProperty> | null;
  /**
   * Content
   */
  content: {
    [key: string]: unknown;
  };
};
