// This file is auto-generated by @hey-api/openapi-ts

/**
 * MessagingConnectionTestStatus
 *
 * Enum for supplying statuses of validating credentials for a messaging Config
 */
export enum MessagingConnectionTestStatus {
  SUCCEEDED = "succeeded",
  FAILED = "failed",
}
