// This file is auto-generated by @hey-api/openapi-ts

/**
 * MessagingServiceDetailsMailgun
 *
 * The details required to represent a Mailgun email configuration.
 */
export type MessagingServiceDetailsMailgun = {
  /**
   * Is Eu Domain
   */
  is_eu_domain?: boolean | null;
  /**
   * Api Version
   */
  api_version?: string | null;
  /**
   * Domain
   */
  domain: string;
};
