// This file is auto-generated by @hey-api/openapi-ts

/**
 * MessagingServiceSecretsMailchimpTransactionalDocs
 *
 * The secrets required to connect Mailchimp Transactional, for documentation
 */
export type MessagingServiceSecretsMailchimpTransactionalDocs = {
  /**
   * Mailchimp Transactional Api Key
   */
  mailchimp_transactional_api_key: string;
};
