// This file is auto-generated by @hey-api/openapi-ts

/**
 * MessagingSecretsMailgunDocs
 *
 * The secrets required to connect to Mailgun, for documentation
 */
export type MessagingSecretsMailgunDocs = {
  /**
   * Mailgun Api Key
   */
  mailgun_api_key: string;
};
