// This file is auto-generated by @hey-api/openapi-ts

/**
 * MinimalPrivacyNotice
 *
 * Minimal schema to represent child privacy notices.
 */
export type MinimalPrivacyNotice = {
  /**
   * Id
   */
  id: string;
  /**
   * Name
   */
  name: string;
};
