// This file is auto-generated by @hey-api/openapi-ts

import { ConnectionType } from "./ConnectionType";
import type { ConsentAlertInfo } from "./ConsentAlertInfo";
import type { DatastoreMonitorUpdates } from "./DatastoreMonitorUpdates";
import type { InfrastructureMonitorUpdates } from "./InfrastructureMonitorUpdates";
import type { MonitorStewardUserResponse } from "./MonitorStewardUserResponse";
import type { SaaSConfigBase } from "./SaaSConfigBase";
import type { WebMonitorUpdates } from "./WebMonitorUpdates";

/**
 * MonitorConfigStagedResourcesAggregateRecord
 *
 * API response model for records of aggregated staged resources by monitor config.
 *
 * This model inherits from ConnectionConfigSecretsMixin, which handles the masking of
 * sensitive values in the connection config `secrets` attribute, and also declares a
 * `connection_type` attribute.
 */
export type MonitorConfigStagedResourcesAggregateRecord = {
  connection_type: ConnectionType;
  /**
   * Secrets
   */
  secrets?: {
    [key: string]: unknown;
  } | null;
  saas_config?: SaaSConfigBase | null;
  /**
   * Name
   */
  name: string;
  /**
   * Key
   */
  key?: string | null;
  /**
   * Last Monitored
   */
  last_monitored?: string | null;
  /**
   * Updates
   */
  updates?:
    | DatastoreMonitorUpdates
    | InfrastructureMonitorUpdates
    | WebMonitorUpdates;
  /**
   * Total Updates
   */
  total_updates?: number;
  consent_status?: ConsentAlertInfo | null;
  /**
   * Connection Name
   */
  connection_name?: string | null;
  /**
   * Has Failed Tasks
   */
  has_failed_tasks?: boolean | null;
  /**
   * Stewards
   */
  stewards?: Array<MonitorStewardUserResponse>;
};
