// This file is auto-generated by @hey-api/openapi-ts

import { MonitorExecutionStatus } from "./MonitorExecutionStatus";

/**
 * MonitorExecution
 */
export type MonitorExecution = {
  /**
   * Id
   */
  id: string;
  /**
   * Monitor Config Key
   */
  monitor_config_key: string;
  status?: MonitorExecutionStatus | null;
  /**
   * Started
   */
  started?: string | null;
  /**
   * Completed
   */
  completed?: string | null;
  /**
   * Classification Instances
   */
  classification_instances?: Array<string>;
  /**
   * Messages
   */
  messages?: Array<string>;
};
