// This file is auto-generated by @hey-api/openapi-ts

import { ClassifyLlmPromptTemplateOptions } from "./ClassifyLlmPromptTemplateOptions";

/**
 * MonitorClassifyParams
 *
 * Extension of base ClassifyParams to include some additional
 * classification parameters that can be used with Discovery monitors
 */
export type MonitorClassifyParams = {
  /**
   * Possible Targets
   */
  possible_targets?: Array<string> | null;
  /**
   * Top N
   */
  top_n?: number;
  /**
   * Remove Stop Words
   */
  remove_stop_words?: boolean;
  /**
   * Pii Threshold
   */
  pii_threshold?: number;
  /**
   * Num Samples
   */
  num_samples?: number;
  /**
   * Num Threads
   */
  num_threads?: number;
  /**
   * Context Weight
   */
  context_weight?: number;
  /**
   * Content Weight
   */
  content_weight?: number;
  /**
   * Prefer Context
   */
  prefer_context?: boolean;
  /**
   * Excluded Categories
   */
  excluded_categories?: Array<unknown>;
  /**
   * Context Classification Enabled
   */
  context_classification_enabled?: boolean;
  /**
   * Context Classifier
   */
  context_classifier?: string;
  /**
   * Custom Llm Instructions
   */
  custom_llm_instructions?: string | null;
  /**
   * Llm Model Override
   */
  llm_model_override?: string | null;
  prompt_template?: ClassifyLlmPromptTemplateOptions | null;
  /**
   * Num Workers
   */
  num_workers?: number;
  /**
   * Max Tokens
   */
  max_tokens?: number;
  /**
   * Classification Retry Count
   *
   * Number of times to retry classification if the LLM returns an invalid response (e.g., null tags, malformed XML). Set to 0 to disable retries.
   */
  classification_retry_count?: number;
  /**
   * Language
   */
  language?: string;
  /**
   * Decision Method
   */
  decision_method?: string;
  /**
   * Aggregation Method
   */
  aggregation_method?: string;
  /**
   * Infer Not Pii
   */
  infer_not_pii?: boolean;
  /**
   * Content Model
   */
  content_model?: string;
  /**
   * Content Classification Enabled
   */
  content_classification_enabled?: boolean;
  /**
   * Context Regex Pattern Mapping
   */
  context_regex_pattern_mapping?: Array<[string, string]>;
  /**
   * Ignore Classification Updates
   */
  ignore_classification_updates?: boolean;
};
