// This file is auto-generated by @hey-api/openapi-ts

/**
 * MonitorStewardUserResponse
 *
 * Response schema for a user assigned as a monitor steward.
 */
export type MonitorStewardUserResponse = {
  /**
   * Id
   */
  id: string;
  /**
   * Username
   */
  username: string;
  /**
   * Email Address
   */
  email_address?: string | null;
  /**
   * First Name
   */
  first_name?: string | null;
  /**
   * Last Name
   */
  last_name?: string | null;
};
