// This file is auto-generated by @hey-api/openapi-ts

import { SupportedLanguage } from "./SupportedLanguage";

/**
 * NoticeTranslationCreate
 *
 * Notice Translation Create Schema
 * Makes title non-optional on create
 */
export type NoticeTranslationCreate = {
  language: SupportedLanguage;
  /**
   * Title
   */
  title: string;
  /**
   * Description
   */
  description?: string | null;
};
