// This file is auto-generated by @hey-api/openapi-ts

/**
 * NotificationResponse
 *
 * Response schema for a single notification.
 */
export type NotificationResponse = {
  /**
   * Id
   *
   * The notification ID
   */
  id: string;
  /**
   * Notification Type
   *
   * The type of notification
   */
  notification_type: string;
  /**
   * Title
   *
   * Notification title
   */
  title: string;
  /**
   * Body
   *
   * Notification body text
   */
  body?: string | null;
  /**
   * Resource Type
   *
   * Type of the linked resource
   */
  resource_type?: string | null;
  /**
   * Resource Id
   *
   * ID of the linked resource
   */
  resource_id?: string | null;
  /**
   * Is Read
   *
   * Whether the notification has been read
   */
  is_read?: boolean;
  /**
   * Created At
   *
   * When the notification was created
   */
  created_at: string;
};
