// This file is auto-generated by @hey-api/openapi-ts

/**
 * NotificationType
 *
 * Types of in-app notifications.
 *
 * String constants — the DB column is a plain String (no migration
 * for new values), but the API contract enumerates valid values so
 * FE can switch on them.
 */
export enum NotificationType {
  CORRESPONDENCE_REPLY = "correspondence_reply",
  CORRESPONDENCE_BOUNCE = "correspondence_bounce",
}
