// This file is auto-generated by @hey-api/openapi-ts

/**
 * OktaConfig
 *
 * The model for the connection config for Okta using OAuth2.
 */
export type OktaConfig = {
  /**
   * Orgurl
   */
  orgUrl: string;
  /**
   * Clientid
   */
  clientId: string;
  /**
   * Privatekey
   */
  privateKey: string;
  /**
   * Scopes
   */
  scopes?: Array<string> | null;
};
