// This file is auto-generated by @hey-api/openapi-ts

/**
 * OktaDocsSchema
 *
 * Okta Secrets Schema for API Docs
 */
export type OktaDocsSchema = {
  /**
   * Organization URL
   *
   * The URL of your Okta organization (e.g. https://your-org.okta.com)
   */
  org_url: string;
  /**
   * OAuth2 Client ID
   *
   * The OAuth2 client ID from your Okta service application
   */
  client_id: string;
  /**
   * Private Key
   *
   * RSA private key in JWK (JSON) format for signing JWT assertions. Download from Okta: Applications > Your App > Sign On > Client Credentials > Edit > Generate new key.
   */
  private_key: string;
  /**
   * OAuth2 Scopes
   *
   * OAuth2 scopes to request (default: okta.apps.read)
   */
  scopes?: Array<string> | null;
};
