// This file is auto-generated by @hey-api/openapi-ts

import { ProviderEnum } from "./ProviderEnum";

/**
 * OpenIDProvider
 *
 * Complete schema, does NOT include sensitive values.
 */
export type OpenIDProvider = {
  /**
   * Identifier
   */
  identifier: string;
  /**
   * Name
   */
  name: string;
  provider: ProviderEnum;
  /**
   * Authorization Url
   */
  authorization_url?: string | null;
  /**
   * Token Url
   */
  token_url?: string | null;
  /**
   * User Info Url
   */
  user_info_url?: string | null;
  /**
   * Domain
   */
  domain?: string | null;
  /**
   * Scopes
   */
  scopes?: Array<string> | null;
  /**
   * Email Field
   */
  email_field?: string | null;
  /**
   * Verify Email
   */
  verify_email?: boolean | null;
  /**
   * Verify Email Field
   */
  verify_email_field?: string | null;
  /**
   * Id
   */
  id: string;
  /**
   * Created At
   */
  created_at: string;
  /**
   * Updated At
   */
  updated_at: string;
};
