// This file is auto-generated by @hey-api/openapi-ts

import { ProviderEnum } from "./ProviderEnum";

/**
 * OpenIDProviderCreate
 *
 * Schema for creating an OpenIDProvider, including sensitive values client ID and secret.
 */
export type OpenIDProviderCreate = {
  /**
   * Identifier
   */
  identifier: string;
  /**
   * Name
   */
  name: string;
  provider: ProviderEnum;
  /**
   * Authorization Url
   */
  authorization_url?: string | null;
  /**
   * Token Url
   */
  token_url?: string | null;
  /**
   * User Info Url
   */
  user_info_url?: string | null;
  /**
   * Domain
   */
  domain?: string | null;
  /**
   * Scopes
   */
  scopes?: Array<string> | null;
  /**
   * Email Field
   */
  email_field?: string | null;
  /**
   * Verify Email
   */
  verify_email?: boolean | null;
  /**
   * Verify Email Field
   */
  verify_email_field?: string | null;
  /**
   * Client Id
   */
  client_id: string;
  /**
   * Client Secret
   */
  client_secret: string;
};
