// This file is auto-generated by @hey-api/openapi-ts

import type { ClassifyInstanceResponseValues } from "./ClassifyInstanceResponseValues";

/**
 * Page[ClassifyInstanceResponseValues]
 */
export type Page_ClassifyInstanceResponseValues_ = {
  /**
   * Items
   */
  items: Array<ClassifyInstanceResponseValues>;
  /**
   * Total
   */
  total: number;
  /**
   * Page
   */
  page: number;
  /**
   * Size
   */
  size: number;
  /**
   * Pages
   */
  pages: number;
};
