// This file is auto-generated by @hey-api/openapi-ts

import type { SystemSummary } from "./SystemSummary";

/**
 * Page[SystemSummary]
 */
export type Page_SystemSummary_ = {
  /**
   * Items
   */
  items: Array<SystemSummary>;
  /**
   * Total
   */
  total: number;
  /**
   * Page
   */
  page: number;
  /**
   * Size
   */
  size: number;
  /**
   * Pages
   */
  pages: number;
};
