// This file is auto-generated by @hey-api/openapi-ts

import type { ExperienceConfigListViewResponse } from "./ExperienceConfigListViewResponse";

/**
 * Page[ExperienceConfigListViewResponse]
 */
export type Page_ExperienceConfigListViewResponse_ = {
  /**
   * Items
   */
  items: Array<ExperienceConfigListViewResponse>;
  /**
   * Total
   */
  total: number;
  /**
   * Page
   */
  page: number;
  /**
   * Size
   */
  size: number;
  /**
   * Pages
   */
  pages: number;
};
