// This file is auto-generated by @hey-api/openapi-ts

import type { AccessPolicyResponse } from "./AccessPolicyResponse";

/**
 * Page[AccessPolicyResponse]
 */
export type Page_AccessPolicyResponse_ = {
  /**
   * Items
   */
  items: Array<AccessPolicyResponse>;
  /**
   * Total
   */
  total: number;
  /**
   * Page
   */
  page: number;
  /**
   * Size
   */
  size: number;
  /**
   * Pages
   */
  pages: number;
};
