// This file is auto-generated by @hey-api/openapi-ts

import type { PrivacyRequestResponseExtended } from "./PrivacyRequestResponseExtended";
import type { PrivacyRequestVerboseResponseExtended } from "./PrivacyRequestVerboseResponseExtended";

/**
 * Page[Union[PrivacyRequestVerboseResponseExtended, PrivacyRequestResponseExtended]]
 */
export type Page_Union_PrivacyRequestVerboseResponseExtended__PrivacyRequestResponseExtended__ =
  {
    /**
     * Items
     */
    items: Array<
      PrivacyRequestVerboseResponseExtended | PrivacyRequestResponseExtended
    >;
    /**
     * Total
     */
    total: number;
    /**
     * Page
     */
    page: number;
    /**
     * Size
     */
    size: number;
    /**
     * Pages
     */
    pages: number;
  };
