// This file is auto-generated by @hey-api/openapi-ts

import type { ManualTaskResponse } from "./ManualTaskResponse";

/**
 * Page[ManualTaskResponse]
 */
export type Page_ManualTaskResponse_ = {
  /**
   * Items
   */
  items: Array<ManualTaskResponse>;
  /**
   * Total
   */
  total: number;
  /**
   * Page
   */
  page: number;
  /**
   * Size
   */
  size: number;
  /**
   * Pages
   */
  pages: number;
};
