// This file is auto-generated by @hey-api/openapi-ts

import type { Property } from "./Property";

/**
 * Page[Property]
 */
export type Page_Property_ = {
  /**
   * Items
   */
  items: Array<Property>;
  /**
   * Total
   */
  total: number;
  /**
   * Page
   */
  page: number;
  /**
   * Size
   */
  size: number;
  /**
   * Pages
   */
  pages: number;
};
