// This file is auto-generated by @hey-api/openapi-ts

import type { IdentityGroupProviderResponse } from "./IdentityGroupProviderResponse";

/**
 * Page[IdentityGroupProviderResponse]
 */
export type Page_IdentityGroupProviderResponse_ = {
  /**
   * Items
   */
  items: Array<IdentityGroupProviderResponse>;
  /**
   * Total
   */
  total: number;
  /**
   * Page
   */
  page: number;
  /**
   * Size
   */
  size: number;
  /**
   * Pages
   */
  pages: number;
};
