// This file is auto-generated by @hey-api/openapi-ts

import type { ClientResponse } from "./ClientResponse";

/**
 * Page[ClientResponse]
 */
export type Page_ClientResponse_ = {
  /**
   * Items
   */
  items: Array<ClientResponse>;
  /**
   * Total
   */
  total: number;
  /**
   * Page
   */
  page: number;
  /**
   * Size
   */
  size: number;
  /**
   * Pages
   */
  pages: number;
};
