// This file is auto-generated by @hey-api/openapi-ts

import type { MonitorStatusResponse } from "./MonitorStatusResponse";

/**
 * Page[MonitorStatusResponse]
 */
export type Page_MonitorStatusResponse_ = {
  /**
   * Items
   */
  items: Array<MonitorStatusResponse>;
  /**
   * Total
   */
  total: number;
  /**
   * Page
   */
  page: number;
  /**
   * Size
   */
  size: number;
  /**
   * Pages
   */
  pages: number;
};
