// This file is auto-generated by @hey-api/openapi-ts

import type { AssessmentTaskResponse } from "./AssessmentTaskResponse";

/**
 * Page[AssessmentTaskResponse]
 */
export type Page_AssessmentTaskResponse_ = {
  /**
   * Items
   */
  items: Array<AssessmentTaskResponse>;
  /**
   * Total
   */
  total: number;
  /**
   * Page
   */
  page: number;
  /**
   * Size
   */
  size: number;
  /**
   * Pages
   */
  pages: number;
};
