// This file is auto-generated by @hey-api/openapi-ts

import type { ViolationFindingResponse } from "./ViolationFindingResponse";

/**
 * Page[ViolationFindingResponse]
 */
export type Page_ViolationFindingResponse_ = {
  /**
   * Items
   */
  items: Array<ViolationFindingResponse>;
  /**
   * Total
   */
  total: number;
  /**
   * Page
   */
  page: number;
  /**
   * Size
   */
  size: number;
  /**
   * Pages
   */
  pages: number;
};
