// This file is auto-generated by @hey-api/openapi-ts

import type { TemplateResponse } from "./TemplateResponse";

/**
 * Page[TemplateResponse]
 */
export type Page_TemplateResponse_ = {
  /**
   * Items
   */
  items: Array<TemplateResponse>;
  /**
   * Total
   */
  total: number;
  /**
   * Page
   */
  page: number;
  /**
   * Size
   */
  size: number;
  /**
   * Pages
   */
  pages: number;
};
