// This file is auto-generated by @hey-api/openapi-ts

import type { PreApprovalWebhookResponse } from "./PreApprovalWebhookResponse";

/**
 * Page[PreApprovalWebhookResponse]
 */
export type Page_PreApprovalWebhookResponse_ = {
  /**
   * Items
   */
  items: Array<PreApprovalWebhookResponse>;
  /**
   * Total
   */
  total: number;
  /**
   * Page
   */
  page: number;
  /**
   * Size
   */
  size: number;
  /**
   * Pages
   */
  pages: number;
};
