// This file is auto-generated by @hey-api/openapi-ts

import type { StorageDestinationResponse } from "./StorageDestinationResponse";

/**
 * Page[StorageDestinationResponse]
 */
export type Page_StorageDestinationResponse_ = {
  /**
   * Items
   */
  items: Array<StorageDestinationResponse>;
  /**
   * Total
   */
  total: number;
  /**
   * Page
   */
  page: number;
  /**
   * Size
   */
  size: number;
  /**
   * Pages
   */
  pages: number;
};
