// This file is auto-generated by @hey-api/openapi-ts

import type { SystemWithMonitorKeys } from "./SystemWithMonitorKeys";

/**
 * Page[SystemWithMonitorKeys]
 */
export type Page_SystemWithMonitorKeys_ = {
  /**
   * Items
   */
  items: Array<SystemWithMonitorKeys>;
  /**
   * Total
   */
  total: number;
  /**
   * Page
   */
  page: number;
  /**
   * Size
   */
  size: number;
  /**
   * Pages
   */
  pages: number;
};
