// This file is auto-generated by @hey-api/openapi-ts

import type { AssessmentResponse } from "./AssessmentResponse";

/**
 * Page[AssessmentResponse]
 */
export type Page_AssessmentResponse_ = {
  /**
   * Items
   */
  items: Array<AssessmentResponse>;
  /**
   * Total
   */
  total: number;
  /**
   * Page
   */
  page: number;
  /**
   * Size
   */
  size: number;
  /**
   * Pages
   */
  pages: number;
};
