// This file is auto-generated by @hey-api/openapi-ts

import type { UserResponse } from "./UserResponse";

/**
 * Page[UserResponse]
 */
export type Page_UserResponse_ = {
  /**
   * Items
   */
  items: Array<UserResponse>;
  /**
   * Total
   */
  total: number;
  /**
   * Page
   */
  page: number;
  /**
   * Size
   */
  size: number;
  /**
   * Pages
   */
  pages: number;
};
