// This file is auto-generated by @hey-api/openapi-ts

import type { RuleTarget } from "./RuleTarget";

/**
 * Page[RuleTarget]
 */
export type Page_RuleTarget_ = {
  /**
   * Items
   */
  items: Array<RuleTarget>;
  /**
   * Total
   */
  total: number;
  /**
   * Page
   */
  page: number;
  /**
   * Size
   */
  size: number;
  /**
   * Pages
   */
  pages: number;
};
