// This file is auto-generated by @hey-api/openapi-ts

import type { fides__api__schemas__privacy_center_config__CustomPrivacyRequestField } from "./fides__api__schemas__privacy_center_config__CustomPrivacyRequestField";
import type { IdentityInputs } from "./IdentityInputs";
import type { LocationCustomPrivacyRequestField } from "./LocationCustomPrivacyRequestField";

/**
 * PartialPrivacyRequestOption
 */
export type PartialPrivacyRequestOption = {
  /**
   * Policy Key
   */
  policy_key: string;
  /**
   * Title
   */
  title: string;
  identity_inputs?: IdentityInputs | null;
  /**
   * Custom Privacy Request Fields
   */
  custom_privacy_request_fields?: {
    [key: string]:
      | LocationCustomPrivacyRequestField
      | fides__api__schemas__privacy_center_config__CustomPrivacyRequestField;
  } | null;
};
