// This file is auto-generated by @hey-api/openapi-ts

import type { PartialPrivacyRequestOption } from "./PartialPrivacyRequestOption";

/**
 * PartialPrivacyCenterConfig
 *
 * Partial schema for the Admin UI privacy request submission.
 */
export type PartialPrivacyCenterConfig = {
  /**
   * Actions
   */
  actions?: Array<PartialPrivacyRequestOption>;
};
