// This file is auto-generated by @hey-api/openapi-ts

/**
 * PolicyMaskingSpec
 *
 * Models the masking strategy definition
 */
export type PolicyMaskingSpec = {
  /**
   * Strategy
   */
  strategy: string;
  /**
   * Configuration
   */
  configuration: {
    [key: string]: unknown;
  };
};
