// This file is auto-generated by @hey-api/openapi-ts

import { ActionType } from "./ActionType";
import type { ConditionGroup } from "./ConditionGroup";
import type { ConditionLeaf } from "./ConditionLeaf";
import { DrpAction } from "./DrpAction";
import type { RuleResponse } from "./RuleResponse";

/**
 * PolicyResponse
 *
 * A holistic view of a Policy record, including all foreign keys by default.
 */
export type PolicyResponse = {
  /**
   * Name
   */
  name: string;
  /**
   * Key
   */
  key?: string | null;
  action_type?: ActionType | null;
  /**
   * Rules
   */
  rules?: Array<RuleResponse> | null;
  drp_action?: DrpAction | null;
  /**
   * Execution Timeframe
   */
  execution_timeframe?: number | null;
  /**
   * Conditions
   */
  conditions?: ConditionLeaf | ConditionGroup | null;
};
