// This file is auto-generated by @hey-api/openapi-ts

import { WebhookDirection } from "./WebhookDirection";

/**
 * PolicyWebhookCreate
 *
 * Request schema for creating/updating a Policy Webhook
 */
export type PolicyWebhookCreate = {
  direction: WebhookDirection;
  /**
   * Key
   */
  key?: string | null;
  /**
   * Name
   */
  name?: string | null;
  /**
   * Connection Config Key
   */
  connection_config_key: string;
};
