// This file is auto-generated by @hey-api/openapi-ts

import type { ConditionGroup } from "./ConditionGroup";
import type { ConditionLeaf } from "./ConditionLeaf";

/**
 * PolicyConditionResponse
 *
 * Response schema for policy conditions.
 */
export type PolicyConditionResponse = {
  /**
   * Condition
   *
   * Root condition (leaf or group) with nested structure. Null if no conditions exist.
   */
  condition?: ConditionLeaf | ConditionGroup | null;
};
