// This file is auto-generated by @hey-api/openapi-ts

import type { WebhookOrder } from "./WebhookOrder";

/**
 * PolicyWebhookDeleteResponse
 *
 * Response schema after deleting a webhook; new_order includes remaining reordered webhooks if applicable
 */
export type PolicyWebhookDeleteResponse = {
  /**
   * New Order
   */
  new_order: Array<WebhookOrder>;
};
