// This file is auto-generated by @hey-api/openapi-ts

/**
 * PolicyUnavailableMessages
 *
 * Used to capture the information to present to a user if a policy is unavailable.
 */
export type PolicyUnavailableMessages = {
  /**
   * Title
   */
  title: string;
  /**
   * Description
   */
  description: string;
  /**
   * Close Button Text
   */
  close_button_text: string;
  /**
   * Action Button Text
   */
  action_button_text: string;
  /**
   * Action Link
   */
  action_link: string;
};
