// This file is auto-generated by @hey-api/openapi-ts

/**
 * PostgreSQLDocsSchema
 *
 * Postgres Secrets Schema for API Docs
 */
export type PostgreSQLDocsSchema = {
  /**
   * Host
   *
   * The hostname or IP address of the server where the database is running.
   */
  host: string;
  /**
   * Port
   *
   * The network port number on which the server is listening for incoming connections (default: 5432).
   */
  port?: number;
  /**
   * Username
   *
   * The user account used to authenticate and access the database.
   */
  username?: string | null;
  /**
   * Password
   *
   * The password used to authenticate and access the database.
   */
  password?: string | null;
  /**
   * SSH required
   *
   * Indicates whether an SSH tunnel is required for the connection. Enable this option if your PostgreSQL server is behind a firewall and requires SSH tunneling for remote connections.
   */
  ssh_required?: boolean;
  /**
   * Database
   *
   * The name of the specific database within the database server that you want to connect to.
   */
  dbname?: string | null;
  /**
   * Schema
   *
   * The default schema to be used for the database connection (defaults to public).
   */
  db_schema?: string | null;
  /**
   * SSL Mode
   */
  ssl_mode?: string | null;
};
