// This file is auto-generated by @hey-api/openapi-ts

import type { ConnectionConfigurationResponse } from "./ConnectionConfigurationResponse";

/**
 * PreApprovalWebhookResponse
 *
 * Response schema after creating/updating/getting a PreApprovalWebhook
 */
export type PreApprovalWebhookResponse = {
  /**
   * Key
   */
  key?: string | null;
  /**
   * Name
   */
  name: string;
  connection_config?: ConnectionConfigurationResponse | null;
};
