// This file is auto-generated by @hey-api/openapi-ts

/**
 * PreApprovalWebhookUpdate
 *
 * Request schema for updating a single webhook - fields are optional
 */
export type PreApprovalWebhookUpdate = {
  /**
   * Name
   */
  name?: string | null;
  /**
   * Connection Config Key
   */
  connection_config_key?: string | null;
};
