// This file is auto-generated by @hey-api/openapi-ts

import { PreferenceType } from "./PreferenceType";
import { PropagationPolicyKey } from "./PropagationPolicyKey";
import type { SourcePreference } from "./SourcePreference";

/**
 * PreferenceFidesMeta
 *
 * Fides-defined metadata properties for a single preference value (includes backend-only fields).
 */
export type PreferenceFidesMeta = {
  /**
   * The type of the preference value.
   */
  preference_type?: PreferenceType;
  /**
   * The key of the policy that created the preference value, if any.
   */
  policy_key?: PropagationPolicyKey | null;
  /**
   * Source preference information for a preference created by a propagation policy.
   */
  source_preference?: SourcePreference | null;
  /**
   * Property Id
   *
   * The Fides property id where the preference was collected
   */
  property_id?: string | null;
  /**
   * Experience Config History Id
   *
   * Identifier for the experience config history
   */
  experience_config_history_id?: string | null;
};
