// This file is auto-generated by @hey-api/openapi-ts

/**
 * PreferenceFidesMetaCreate
 *
 * Fides-defined metadata for API input (user-provided fields only).
 */
export type PreferenceFidesMetaCreate = {
  /**
   * Property Id
   *
   * The Fides property id where the preference was collected
   */
  property_id?: string | null;
  /**
   * Experience Config History Id
   *
   * Identifier for the experience config history
   */
  experience_config_history_id?: string | null;
};
