// This file is auto-generated by @hey-api/openapi-ts

import type { ExperienceConfigResponseNoNotices } from "./ExperienceConfigResponseNoNotices";
import type { ExperienceMeta } from "./ExperienceMeta";
import type { fidesplus__schemas__tcf_experience__TCFPublisherRestrictionResponse } from "./fidesplus__schemas__tcf_experience__TCFPublisherRestrictionResponse";
import type { PrivacyExperienceGPPSettings } from "./PrivacyExperienceGPPSettings";
import { PrivacyNoticeRegion } from "./PrivacyNoticeRegion";
import type { PrivacyNoticeResponse } from "./PrivacyNoticeResponse";
import type { TCFFeatureRecord } from "./TCFFeatureRecord";
import type { TCFPurposeConsentRecord } from "./TCFPurposeConsentRecord";
import type { TCFPurposeLegitimateInterestsRecord } from "./TCFPurposeLegitimateInterestsRecord";
import type { TCFSpecialFeatureRecord } from "./TCFSpecialFeatureRecord";
import type { TCFSpecialPurposeRecord } from "./TCFSpecialPurposeRecord";
import type { TCFVendorConsentRecord } from "./TCFVendorConsentRecord";
import type { TCFVendorLegitimateInterestsRecord } from "./TCFVendorLegitimateInterestsRecord";
import type { TCFVendorRelationships } from "./TCFVendorRelationships";

/**
 * PrivacyExperienceResponse
 *
 * An API representation of a PrivacyExperience used for response payloads
 *
 * Notices are extracted from the shared Experience Config and placed at the top-level here
 * for backwards compatibility, and to reduce nesting due to notice translations.
 *
 * Additionally, the notices may be a subset of the notices attached to the ExperienceConfig
 * due to filtering
 */
export type PrivacyExperienceResponse = {
  /**
   * Id
   */
  id: string;
  /**
   * Created At
   */
  created_at: string;
  /**
   * Updated At
   */
  updated_at: string;
  region: PrivacyNoticeRegion;
  gpp_settings?: PrivacyExperienceGPPSettings | null;
  /**
   * Tcf Purpose Consents
   */
  tcf_purpose_consents?: Array<TCFPurposeConsentRecord>;
  /**
   * Tcf Purpose Legitimate Interests
   */
  tcf_purpose_legitimate_interests?: Array<TCFPurposeLegitimateInterestsRecord>;
  /**
   * Tcf Special Purposes
   */
  tcf_special_purposes?: Array<TCFSpecialPurposeRecord>;
  /**
   * Tcf Features
   */
  tcf_features?: Array<TCFFeatureRecord>;
  /**
   * Tcf Special Features
   */
  tcf_special_features?: Array<TCFSpecialFeatureRecord>;
  /**
   * Tcf Vendor Consents
   */
  tcf_vendor_consents?: Array<TCFVendorConsentRecord>;
  /**
   * Tcf Vendor Legitimate Interests
   */
  tcf_vendor_legitimate_interests?: Array<TCFVendorLegitimateInterestsRecord>;
  /**
   * Tcf Vendor Relationships
   */
  tcf_vendor_relationships?: Array<TCFVendorRelationships>;
  /**
   * Tcf System Consents
   */
  tcf_system_consents?: Array<TCFVendorConsentRecord>;
  /**
   * Tcf System Legitimate Interests
   */
  tcf_system_legitimate_interests?: Array<TCFVendorLegitimateInterestsRecord>;
  /**
   * Tcf System Relationships
   */
  tcf_system_relationships?: Array<TCFVendorRelationships>;
  /**
   * Tcf Publisher Restrictions
   */
  tcf_publisher_restrictions?: Array<fidesplus__schemas__tcf_experience__TCFPublisherRestrictionResponse>;
  /**
   * Tcf Publisher Country Code
   */
  tcf_publisher_country_code?: string | null;
  /**
   * Privacy Notices
   *
   * The Privacy Notices associated with this experience, if applicable
   */
  privacy_notices?: Array<PrivacyNoticeResponse> | null;
  /**
   * Non Applicable Privacy Notices
   *
   * The notice keys of the Privacy Notices that are enabled, but not applicable to the experience
   */
  non_applicable_privacy_notices?: Array<string> | null;
  /**
   * The Experience Config and its translations
   */
  experience_config?: ExperienceConfigResponseNoNotices | null;
  /**
   * Gvl
   */
  gvl?: {
    [key: string]: unknown;
  } | null;
  /**
   * Gvl Translations
   */
  gvl_translations?: {
    [key: string]: unknown;
  } | null;
  /**
   * Available Locales
   */
  available_locales?: Array<string> | null;
  meta?: ExperienceMeta | null;
  /**
   * Vendor Count
   *
   * The number of vendors in the TCF experience. Only populated for TCF experiences.
   */
  vendor_count?: number | null;
};
