// This file is auto-generated by @hey-api/openapi-ts

/**
 * PrivacyPreferenceStats
 */
export type PrivacyPreferenceStats = {
  /**
   * Estimated Count
   *
   * Estimated count of privacy preferencehistory table using stats collector for fast reads
   */
  estimated_count?: number;
};
