// This file is auto-generated by @hey-api/openapi-ts

/**
 * PrivacyRequestNotificationInfo
 */
export type PrivacyRequestNotificationInfo = {
  /**
   * Email Addresses
   */
  email_addresses: Array<string>;
  /**
   * Notify After Failures
   */
  notify_after_failures: number;
};
