// This file is auto-generated by @hey-api/openapi-ts

import type { CheckpointActionRequiredDetails } from "./CheckpointActionRequiredDetails";
import type { ExecutionAndAuditLogResponse } from "./ExecutionAndAuditLogResponse";
import type { fides__api__schemas__privacy_request__IdentityValue } from "./fides__api__schemas__privacy_request__IdentityValue";
import type { PolicyResponse } from "./PolicyResponse";
import { PrivacyRequestSource } from "./PrivacyRequestSource";
import { PrivacyRequestStatus } from "./PrivacyRequestStatus";
import type { PrivacyRequestUser } from "./PrivacyRequestUser";

/**
 * PrivacyRequestVerboseResponse
 *
 * The schema for the more detailed PrivacyRequest response containing both
 * detailed execution logs and audit logs.
 */
export type PrivacyRequestVerboseResponse = {
  /**
   * Id
   */
  id: string;
  /**
   * Created At
   */
  created_at?: string | null;
  /**
   * Started Processing At
   */
  started_processing_at?: string | null;
  /**
   * Reviewed At
   */
  reviewed_at?: string | null;
  /**
   * Reviewed By
   */
  reviewed_by?: string | null;
  /**
   * Submitted By
   */
  submitted_by?: string | null;
  reviewer?: PrivacyRequestUser | null;
  submitter?: PrivacyRequestUser | null;
  /**
   * Finished Processing At
   */
  finished_processing_at?: string | null;
  /**
   * Identity Verified At
   */
  identity_verified_at?: string | null;
  /**
   * Paused At
   */
  paused_at?: string | null;
  status: PrivacyRequestStatus;
  /**
   * External Id
   */
  external_id?: string | null;
  /**
   * Identity
   */
  identity?: {
    [key: string]:
      | string
      | fides__api__schemas__privacy_request__IdentityValue
      | null;
  } | null;
  /**
   * Custom Privacy Request Fields
   */
  custom_privacy_request_fields?: {
    [key: string]: unknown;
  } | null;
  policy: PolicyResponse;
  action_required_details?: CheckpointActionRequiredDetails | null;
  /**
   * Resume Endpoint
   */
  resume_endpoint?: string | null;
  /**
   * Days Left
   */
  days_left?: number | null;
  /**
   * Custom Privacy Request Fields Approved By
   */
  custom_privacy_request_fields_approved_by?: string | null;
  /**
   * Custom Privacy Request Fields Approved At
   */
  custom_privacy_request_fields_approved_at?: string | null;
  source?: PrivacyRequestSource | null;
  /**
   * Location
   */
  location?: string | null;
  /**
   * Deleted At
   */
  deleted_at?: string | null;
  /**
   * Deleted By
   */
  deleted_by?: string | null;
  /**
   * Finalized At
   */
  finalized_at?: string | null;
  /**
   * Finalized By
   */
  finalized_by?: string | null;
  /**
   * Duplicate Request Group Id
   */
  duplicate_request_group_id?: string | null;
  /**
   * Results
   */
  results: {
    [key: string]: Array<ExecutionAndAuditLogResponse>;
  };
  /**
   * Task Status By Dataset
   */
  task_status_by_dataset?: {
    [key: string]: string;
  } | null;
};
