// This file is auto-generated by @hey-api/openapi-ts

import type { PrivacyRequestFilter } from "./PrivacyRequestFilter";

/**
 * PrivacyRequestBulkSelection
 *
 * Select privacy requests for bulk actions using either explicit IDs or filters.
 *
 * If request_ids is provided, it will be used directly.
 * If filters is provided (without request_ids), filters will be used to select privacy requests,
 * with optional exclusions via exclude_ids.
 *
 * For backwards compatibility, a plain list of request IDs is also accepted and will be
 * automatically converted to {"request_ids": [...]}.
 */
export type PrivacyRequestBulkSelection = {
  /**
   * Request Ids
   *
   * List of privacy request IDs to act on. The backend will automatically batch requests if the list is large.
   */
  request_ids?: Array<string> | null;
  /**
   * Filters to select privacy requests (only used when request_ids is not provided)
   */
  filters?: PrivacyRequestFilter | null;
  /**
   * Exclude Ids
   *
   * List of privacy request IDs to exclude from the action (only used with filters)
   */
  exclude_ids?: Array<string> | null;
};
