// This file is auto-generated by @hey-api/openapi-ts

/**
 * PrivacyRequestDRPStatus
 *
 * A list of privacy request statuses specified by the Data Rights Protocol.
 */
export enum PrivacyRequestDRPStatus {
  OPEN = "open",
  IN_PROGRESS = "in_progress",
  FULFILLED = "fulfilled",
  REVOKED = "revoked",
  DENIED = "denied",
  EXPIRED = "expired",
}
