// This file is auto-generated by @hey-api/openapi-ts

/**
 * PromoteResourcesResponse
 *
 * Response model for promote operations on staged resources
 */
export type PromoteResourcesResponse = {
  /**
   * Task Id
   *
   * The task ID of the promote operation
   */
  task_id?: string | null;
};
