// This file is auto-generated by @hey-api/openapi-ts

/**
 * PromptType
 *
 * Specific prompt types.
 */
export enum PromptType {
  ASSESSMENT_ANALYSIS = "assessment_analysis",
  INTENT_CLASSIFICATION = "intent_classification",
  MESSAGE_GENERATION = "message_generation",
  QUESTION_REPHRASE = "question_rephrase",
  QUESTION_REPHRASE_BATCH = "question_rephrase_batch",
}
