// This file is auto-generated by @hey-api/openapi-ts

/**
 * PropertyNameResolutionRequest
 *
 * Request schema for resolving property names to IDs.
 */
export type PropertyNameResolutionRequest = {
  /**
   * Property Names
   */
  property_names: Array<string>;
};
