// This file is auto-generated by @hey-api/openapi-ts

/**
 * RateLimitPeriod
 *
 * Defines the periods supported by rate limit config
 */
export enum RateLimitPeriod {
  SECOND = "second",
  MINUTE = "minute",
  HOUR = "hour",
  DAY = "day",
}
