// This file is auto-generated by @hey-api/openapi-ts

/**
 * RBACRoleCreate
 *
 * Schema for creating a new role.
 */
export type RBACRoleCreate = {
  /**
   * Name
   *
   * Display name
   */
  name: string;
  /**
   * Key
   *
   * Machine-readable key
   */
  key: string;
  /**
   * Description
   *
   * Role description
   */
  description?: string | null;
  /**
   * Parent Role Id
   *
   * Parent role ID for hierarchy
   */
  parent_role_id?: string | null;
  /**
   * Priority
   *
   * Priority for conflict resolution
   */
  priority?: number;
};
