// This file is auto-generated by @hey-api/openapi-ts

/**
 * RBACEvaluateResponse
 *
 * Schema for permission evaluation response.
 */
export type RBACEvaluateResponse = {
  /**
   * Has Permission
   *
   * Whether user has the permission
   */
  has_permission: boolean;
  /**
   * Reason
   *
   * Explanation of the result
   */
  reason: string;
  /**
   * Evaluated Roles
   *
   * Roles that were checked
   */
  evaluated_roles?: Array<string>;
  /**
   * Matched Via
   *
   * How permission was granted: 'direct', 'inherited', or None
   */
  matched_via?: string | null;
};
