// This file is auto-generated by @hey-api/openapi-ts

/**
 * RBACPermissionResponse
 *
 * Schema for permission responses.
 */
export type RBACPermissionResponse = {
  /**
   * Id
   */
  id: string;
  /**
   * Code
   */
  code: string;
  /**
   * Description
   */
  description?: string | null;
  /**
   * Resource Type
   */
  resource_type?: string | null;
  /**
   * Is Active
   */
  is_active: boolean;
};
