// This file is auto-generated by @hey-api/openapi-ts

/**
 * RBACEvaluateRequest
 *
 * Schema for permission evaluation request.
 */
export type RBACEvaluateRequest = {
  /**
   * User Id
   *
   * User ID to evaluate
   */
  user_id: string;
  /**
   * Permission Code
   *
   * Permission code to check
   */
  permission_code: string;
  /**
   * Resource Type
   *
   * Resource type for scoped check
   */
  resource_type?: string | null;
  /**
   * Resource Id
   *
   * Specific resource ID for scoped check
   */
  resource_id?: string | null;
};
