// This file is auto-generated by @hey-api/openapi-ts

/**
 * RBACRolePermissionsUpdate
 *
 * Schema for updating role permissions.
 */
export type RBACRolePermissionsUpdate = {
  /**
   * Permission Codes
   *
   * List of permission codes to assign to the role
   */
  permission_codes: Array<string>;
};
