// This file is auto-generated by @hey-api/openapi-ts

/**
 * RecalculateConsentResponse
 *
 * Response model for recalculate consent operations on staged resources
 */
export type RecalculateConsentResponse = {
  /**
   * Updated
   *
   * Number of resources updated
   */
  updated: number;
};
