// This file is auto-generated by @hey-api/openapi-ts

import type { fides__api__schemas__redis_cache__Identity } from "./fides__api__schemas__redis_cache__Identity";
import { ServingComponent } from "./ServingComponent";

/**
 * RecordConsentServedRequest
 *
 * Request body to use when saving that consent was served
 */
export type RecordConsentServedRequest = {
  /**
   * Tcf Purpose Consents
   */
  tcf_purpose_consents?: Array<number>;
  /**
   * Tcf Purpose Legitimate Interests
   */
  tcf_purpose_legitimate_interests?: Array<number>;
  /**
   * Tcf Special Purposes
   */
  tcf_special_purposes?: Array<number>;
  /**
   * Tcf Vendor Consents
   */
  tcf_vendor_consents?: Array<string>;
  /**
   * Tcf Vendor Legitimate Interests
   */
  tcf_vendor_legitimate_interests?: Array<string>;
  /**
   * Tcf Features
   */
  tcf_features?: Array<number>;
  /**
   * Tcf Special Features
   */
  tcf_special_features?: Array<number>;
  /**
   * Tcf System Consents
   */
  tcf_system_consents?: Array<string>;
  /**
   * Tcf System Legitimate Interests
   */
  tcf_system_legitimate_interests?: Array<string>;
  /**
   * Privacy Notice History Ids
   */
  privacy_notice_history_ids?: Array<string>;
  browser_identity: fides__api__schemas__redis_cache__Identity;
  /**
   * Code
   */
  code?: string | null;
  /**
   * Privacy Experience Id
   */
  privacy_experience_id?: string | null;
  /**
   * Privacy Experience Config History Id
   */
  privacy_experience_config_history_id?: string | null;
  /**
   * User Geography
   */
  user_geography?: string | null;
  /**
   * Acknowledge Mode
   */
  acknowledge_mode?: boolean | null;
  /**
   * Served Notice History Id
   */
  served_notice_history_id?: string | null;
  serving_component: ServingComponent;
  /**
   * Property Id
   */
  property_id?: string | null;
};
