// This file is auto-generated by @hey-api/openapi-ts

import { RedactionType } from "./RedactionType";

/**
 * RedactionEntry
 *
 * A single redaction instruction targeting a specific field or record.
 */
export type RedactionEntry = {
  /**
   * Source
   *
   * Collection address, e.g. 'postgres_db:customers'
   */
  source: string;
  /**
   * Record Index
   *
   * Index of the record within the collection
   */
  record_index: number;
  /**
   * Field Path
   *
   * Field name within the record. Omit for remove_record.
   */
  field_path?: string | null;
  type: RedactionType;
};
