// This file is auto-generated by @hey-api/openapi-ts

import type { DataSectionConfig } from "./DataSectionConfig";
import { PromptType } from "./PromptType";

/**
 * RenderPromptRequest
 *
 * Request to render a prompt with data.
 */
export type RenderPromptRequest = {
  prompt_type: PromptType;
  data_sections?: DataSectionConfig;
  /**
   * Assessment Id
   */
  assessment_id?: string | null;
  /**
   * Declaration Id
   */
  declaration_id?: string | null;
  /**
   * Template Key
   */
  template_key?: string | null;
  /**
   * Questionnaire Variables
   */
  questionnaire_variables?: {
    [key: string]: unknown;
  } | null;
};
