// This file is auto-generated by @hey-api/openapi-ts

/**
 * ResponseWithMessage
 *
 * Generic schema for responses with a message
 */
export type ResponseWithMessage = {
  /**
   * Message
   */
  message: string;
};
