// This file is auto-generated by @hey-api/openapi-ts

import type { PaginationFilterParams } from "./PaginationFilterParams";

/**
 * ResultSetStats
 */
export type ResultSetStats = {
  /**
   * Count
   *
   * Total number of records matching the filter
   */
  count?: number;
  /**
   * The filter that this metadata describes
   */
  filter: PaginationFilterParams;
  /**
   * Timestamp
   *
   * Timestamp of the result-set metadata
   */
  timestamp?: number;
};
