// This file is auto-generated by @hey-api/openapi-ts

/**
 * RevertAnswerRequest
 *
 * Request to revert an answer to a previous version.
 */
export type RevertAnswerRequest = {
  /**
   * Version Number
   *
   * Version number to revert to
   */
  version_number: number;
};
