// This file is auto-generated by @hey-api/openapi-ts

import { ActionType } from "./ActionType";
import type { PolicyMaskingSpec } from "./PolicyMaskingSpec";

/**
 * RuleCreate
 *
 * The schema to use when creating a Rule. This schema accepts a storage_destination_key
 * over a composite object.
 */
export type RuleCreate = {
  /**
   * Name
   */
  name: string;
  /**
   * Key
   */
  key?: string | null;
  action_type: ActionType;
  /**
   * Storage Destination Key
   */
  storage_destination_key?: string | null;
  masking_strategy?: PolicyMaskingSpec | null;
};
