// This file is auto-generated by @hey-api/openapi-ts

/**
 * S3MonitorParams
 */
export type S3MonitorParams = {
  /**
   * Max Objects
   *
   * The maximum number of objects that will be detected, per bucket
   */
  max_objects?: number | null;
};
