// This file is auto-generated by @hey-api/openapi-ts

import type { ReadSaaSRequest } from "./ReadSaaSRequest";
import type { SaaSRequest } from "./SaaSRequest";

/**
 * SaaSRequestMap
 *
 * A map of actions to SaaS requests
 */
export type SaaSRequestMap = {
  /**
   * Read
   */
  read?: ReadSaaSRequest | Array<ReadSaaSRequest>;
  update?: SaaSRequest | null;
  delete?: SaaSRequest | null;
};
