// This file is auto-generated by @hey-api/openapi-ts

import { ConnectionCategory } from "./ConnectionCategory";
import { IntegrationFeature } from "./IntegrationFeature";

/**
 * SaaSDisplayInfo
 *
 * Optional display information for SAAS integrations to enhance frontend presentation.
 * When not provided, smart defaults will be inferred based on the integration type.
 */
export type SaaSDisplayInfo = {
  category?: ConnectionCategory | null;
  /**
   * Tags
   */
  tags?: Array<string> | null;
  /**
   * Enabled Features
   */
  enabled_features?: Array<IntegrationFeature> | null;
};
