// This file is auto-generated by @hey-api/openapi-ts

/**
 * SeedResponse
 *
 * Response schema after triggering environment seed.
 */
export type SeedResponse = {
  /**
   * Execution Id
   *
   * Unique execution ID for tracking
   */
  execution_id: string;
  /**
   * Message
   *
   * Status message
   */
  message: string;
};
