// This file is auto-generated by @hey-api/openapi-ts

import type { DiscoveryMonitorsConfig } from "./DiscoveryMonitorsConfig";
import type { MailgunConfig } from "./MailgunConfig";
import type { S3Config } from "./S3Config";
import type { SeedTasksConfig } from "./SeedTasksConfig";

/**
 * SeedRequest
 *
 * Request schema for triggering environment seed.
 *
 * Extra fields are ignored for backward compatibility: older clients or
 * newer payloads with additional keys (e.g. new monitor types) won't fail validation.
 */
export type SeedRequest = {
  /**
   * Which seed tasks to run
   */
  tasks?: SeedTasksConfig;
  /**
   * Mailgun credentials (required if messaging_mailgun)
   */
  mailgun?: MailgunConfig | null;
  /**
   * S3 credentials (required if storage_s3)
   */
  s3?: S3Config | null;
  /**
   * Discovery monitor configs (required if discovery_monitors)
   */
  discovery_monitors?: DiscoveryMonitorsConfig | null;
};
