// This file is auto-generated by @hey-api/openapi-ts

/**
 * SeedTasksConfig
 *
 * Configuration for which seed tasks to run.
 */
export type SeedTasksConfig = {
  /**
   * Sample Resources
   *
   * Load sample resources from demo/.fides (systems, datasets, policies)
   */
  sample_resources?: boolean;
  /**
   * Messaging Mailgun
   *
   * Configure Mailgun for messaging
   */
  messaging_mailgun?: boolean;
  /**
   * Storage S3
   *
   * Configure S3 for storage
   */
  storage_s3?: boolean;
  /**
   * Linked Connections
   *
   * Link sample connections to systems
   */
  linked_connections?: boolean;
  /**
   * Consent Notices
   *
   * Enable default consent notices
   */
  consent_notices?: boolean;
  /**
   * Consent Experiences
   *
   * Enable default consent experiences
   */
  consent_experiences?: boolean;
  /**
   * Compass Vendors
   *
   * Enable default Compass vendors
   */
  compass_vendors?: boolean;
  /**
   * Email Templates
   *
   * Update email templates with HTML versions
   */
  email_templates?: boolean;
  /**
   * Discovery Monitors
   *
   * Create discovery monitors
   */
  discovery_monitors?: boolean;
};
