// This file is auto-generated by @hey-api/openapi-ts

/**
 * Selection
 *
 * Selection schema
 */
export type Selection = {
  /**
   * Id
   */
  id: string;
  /**
   * Selected
   */
  selected?: boolean;
};
