// This file is auto-generated by @hey-api/openapi-ts

/**
 * SendQuestionnaireResponse
 *
 * Response from sending a questionnaire.
 */
export type SendQuestionnaireResponse = {
  /**
   * Sent At
   */
  sent_at: string;
  /**
   * Channel
   */
  channel: string;
  /**
   * Questions Sent
   */
  questions_sent: number;
  /**
   * Message Id
   */
  message_id?: string | null;
};
