// This file is auto-generated by @hey-api/openapi-ts

/**
 * SendMessageRequest
 *
 * Request schema for sending a chat message.
 */
export type SendMessageRequest = {
  /**
   * Channel Id
   */
  channel_id: string;
  /**
   * Message
   */
  message: string;
};
