// This file is auto-generated by @hey-api/openapi-ts

/**
 * SendMessageResponse
 *
 * Response schema for send message result.
 */
export type SendMessageResponse = {
  /**
   * Success
   */
  success: boolean;
  /**
   * Message
   */
  message: string;
};
