// This file is auto-generated by @hey-api/openapi-ts

import type { AttachmentResponse } from "./AttachmentResponse";
import type { CommentResponse } from "./CommentResponse";

/**
 * SingleFieldSubmissionResponse
 *
 * Response schema for single field submission
 */
export type SingleFieldSubmissionResponse = {
  /**
   * Privacy Request Id
   */
  privacy_request_id: string;
  /**
   * Connection Key
   */
  connection_key: string;
  /**
   * Field Key
   */
  field_key: string;
  /**
   * Field Value
   *
   * The field value (may be empty if attachments were provided)
   */
  field_value: string;
  /**
   * Submission Id
   */
  submission_id: string;
  /**
   * Instance Id
   */
  instance_id: string;
  /**
   * Instance Status
   */
  instance_status: string;
  /**
   * Is Complete
   */
  is_complete: boolean;
  /**
   * Completed At
   */
  completed_at?: string | null;
  comment?: CommentResponse | null;
  /**
   * Attachments
   *
   * List of attachments for this field submission
   */
  attachments?: Array<AttachmentResponse>;
  /**
   * Message
   */
  message: string;
  /**
   * User Id
   */
  user_id?: string | null;
  /**
   * User First Name
   */
  user_first_name?: string | null;
  /**
   * User Last Name
   */
  user_last_name?: string | null;
  /**
   * User Email Address
   */
  user_email_address?: string | null;
};
