// This file is auto-generated by @hey-api/openapi-ts

/**
 * StagedResourceUpdateRequest
 *
 * Defines the subset of StagedResource fields permissable on update request payloads
 */
export type StagedResourceUpdateRequest = {
  /**
   * Urn
   */
  urn: string;
  /**
   * User Assigned Data Categories
   */
  user_assigned_data_categories?: Array<string> | null;
  /**
   * User Assigned Data Uses
   *
   * User assigned data uses overriding auto assigned data uses
   */
  user_assigned_data_uses?: Array<string> | null;
  /**
   * User Assigned System Key
   */
  user_assigned_system_key?: string | null;
};
