// This file is auto-generated by @hey-api/openapi-ts

/**
 * StagedResourceTypeValue
 *
 * Enum of the values used for `StagedResource.resource_type`s in the DB
 */
export enum StagedResourceTypeValue {
  DATABASE = "Database",
  SCHEMA = "Schema",
  TABLE = "Table",
  FIELD = "Field",
  ENDPOINT = "Endpoint",
  COOKIE = "Cookie",
  BROWSER_REQUEST = "Browser request",
  IMAGE = "Image",
  I_FRAME = "iFrame",
  JAVASCRIPT_TAG = "Javascript tag",
  IDP_APP = "IDP App",
  CLOUD_INFRASTRUCTURE = "Cloud Infrastructure",
}
