// This file is auto-generated by @hey-api/openapi-ts

import { ResponseFormat } from "./ResponseFormat";
import type { StorageDetailsGCS } from "./StorageDetailsGCS";
import type { StorageDetailsLocal } from "./StorageDetailsLocal";
import type { StorageDetailsS3 } from "./StorageDetailsS3";
import { StorageType } from "./StorageType";

/**
 * StorageDestinationBase
 *
 * Storage Destination Schema -- used for setting defaults
 */
export type StorageDestinationBase = {
  type: StorageType;
  /**
   * Details
   */
  details: StorageDetailsS3 | StorageDetailsGCS | StorageDetailsLocal;
  format?: ResponseFormat | null;
};
