// This file is auto-generated by @hey-api/openapi-ts

import { ResponseFormat } from "./ResponseFormat";
import { StorageDetails } from "./StorageDetails";
import { StorageType } from "./StorageType";

/**
 * StorageDestinationResponse
 *
 * Storage Destination Response Schema
 */
export type StorageDestinationResponse = {
  /**
   * Name
   */
  name: string;
  type: StorageType;
  /**
   * Details
   */
  details: {
    [key in StorageDetails]?: unknown;
  };
  /**
   * Key
   */
  key: string;
  format: ResponseFormat;
  /**
   * Is Default
   */
  is_default?: boolean;
};
