// This file is auto-generated by @hey-api/openapi-ts

/**
 * StorageSecretsS3Docs
 *
 * The secrets required to connect to S3, for documentation
 */
export type StorageSecretsS3Docs = {
  /**
   * Aws Access Key Id
   */
  aws_access_key_id?: string | null;
  /**
   * Aws Secret Access Key
   */
  aws_secret_access_key?: string | null;
  /**
   * Region Name
   */
  region_name?: string | null;
  /**
   * Assume Role Arn
   */
  assume_role_arn?: string | null;
};
