// This file is auto-generated by @hey-api/openapi-ts

/**
 * StorageSecretsGCSDocs
 *
 * The secrets required to connect to Google Cloud Storage, for documentation
 */
export type StorageSecretsGCSDocs = {
  /**
   * Type
   */
  type?: string;
  /**
   * Project Id
   */
  project_id: string;
  /**
   * Private Key Id
   */
  private_key_id: string;
  /**
   * Private Key
   */
  private_key: string;
  /**
   * Client Email
   */
  client_email: string;
  /**
   * Client Id
   */
  client_id: string;
  /**
   * Auth Uri
   */
  auth_uri: string;
  /**
   * Token Uri
   */
  token_uri: string;
  /**
   * Auth Provider X509 Cert Url
   */
  auth_provider_x509_cert_url: string;
  /**
   * Client X509 Cert Url
   */
  client_x509_cert_url: string;
  /**
   * Universe Domain
   */
  universe_domain: string;
};
