// This file is auto-generated by @hey-api/openapi-ts

import { StorageTypeApiAccepted } from "./StorageTypeApiAccepted";

/**
 * StorageApplicationConfig
 */
export type StorageApplicationConfig = {
  active_default_storage_type: StorageTypeApiAccepted;
};
