// This file is auto-generated by @hey-api/openapi-ts

/**
 * StorageTypeApiAccepted
 *
 * Enum for storage destination types accepted in API updates
 */
export enum StorageTypeApiAccepted {
  S3 = "s3",
  GCS = "gcs",
  LOCAL = "local",
}
