// This file is auto-generated by @hey-api/openapi-ts

/**
 * StorageType
 *
 * Enum for storage destination types
 */
export enum StorageType {
  S3 = "s3",
  GCS = "gcs",
  TRANSCEND = "transcend",
  ETHYCA = "ethyca",
  LOCAL = "local",
}
