// This file is auto-generated by @hey-api/openapi-ts

import { ResponseFormat } from "./ResponseFormat";
import type { StorageDetailsGCS } from "./StorageDetailsGCS";
import type { StorageDetailsLocal } from "./StorageDetailsLocal";
import type { StorageDetailsS3 } from "./StorageDetailsS3";
import { StorageType } from "./StorageType";

/**
 * StorageDestination
 *
 * Storage Destination Schema
 */
export type StorageDestination = {
  type: StorageType;
  /**
   * Details
   */
  details: StorageDetailsS3 | StorageDetailsGCS | StorageDetailsLocal;
  format?: ResponseFormat | null;
  /**
   * Name
   */
  name: string;
  /**
   * Key
   */
  key?: string | null;
};
