// This file is auto-generated by @hey-api/openapi-ts

import { GCSAuthMethod } from "./GCSAuthMethod";

/**
 * StorageDetailsGCS
 *
 * The details required to represent a Google Cloud Storage bucket.
 */
export type StorageDetailsGCS = {
  /**
   * Naming
   */
  naming?: string;
  auth_method: GCSAuthMethod;
  /**
   * Bucket
   */
  bucket: string;
  /**
   * Max Retries
   */
  max_retries?: number | null;
};
