// This file is auto-generated by @hey-api/openapi-ts

/**
 * Strategy
 *
 * General shape for swappable strategies (ex: auth, processors, pagination, etc.)
 */
export type Strategy = {
  /**
   * Strategy
   */
  strategy: string;
  /**
   * Configuration
   */
  configuration?: {
    [key: string]: unknown;
  } | null;
};
