/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

export enum SupportedLanguage {
  AR = "ar",
  BG = "bg",
  BS = "bs",
  CA = "ca",
  CS = "cs",
  DA = "da",
  DE = "de",
  EL = "el",
  EN = "en",
  ES = "es",
  ES_MX = "es-MX",
  ET = "et",
  EU = "eu",
  FI = "fi",
  FR = "fr",
  FR_CA = "fr-CA",
  GL = "gl",
  HI_IN = "hi-IN",
  HR = "hr",
  HU = "hu",
  IT = "it",
  JA = "ja",
  LT = "lt",
  LV = "lv",
  MT = "mt",
  NL = "nl",
  NO = "no",
  PL = "pl",
  PT_BR = "pt-BR",
  PT_PT = "pt-PT",
  RO = "ro",
  RU = "ru",
  SK = "sk",
  SL = "sl",
  SR_CYRL = "sr-Cyrl",
  SR_LATN = "sr-Latn",
  SV = "sv",
  TR = "tr",
  UK = "uk",
  ZH = "zh",
}
