// This file is auto-generated by @hey-api/openapi-ts

import type { System } from "./System";

/**
 * SystemScanResponse
 */
export type SystemScanResponse = {
  /**
   * Systems
   */
  systems: Array<System>;
};
