// This file is auto-generated by @hey-api/openapi-ts

/**
 * SystemSummary
 *
 * A summary of a system with aggregate counts for select fields.
 */
export type SystemSummary = {
  /**
   * Id
   */
  id: string;
  /**
   * Fides Key
   */
  fides_key: string;
  /**
   * Vendor Id
   */
  vendor_id?: string | null;
  /**
   * Name
   */
  name: string;
  /**
   * Purposes
   */
  purposes: number;
  /**
   * Cookies
   */
  cookies: number;
  /**
   * Data Uses
   */
  data_uses: number;
  /**
   * Legal Bases
   */
  legal_bases: number;
  /**
   * Consent Categories
   */
  consent_categories: number;
};
