// This file is auto-generated by @hey-api/openapi-ts

import type { System } from "./System";

/**
 * SystemScanHistory
 */
export type SystemScanHistory = {
  /**
   * Id
   */
  id: number;
  /**
   * Status
   */
  status: string;
  /**
   * Result
   */
  result: Array<System>;
  /**
   * Created At
   */
  created_at: string;
  /**
   * Updated At
   */
  updated_at: string;
};
