// This file is auto-generated by @hey-api/openapi-ts

/**
 * SystemRef
 */
export type SystemRef = {
  /**
   * Fides Key
   */
  fides_key: string;
  /**
   * Name
   */
  name: string;
  /**
   * Data Uses
   */
  data_uses?: Array<string>;
};
