// This file is auto-generated by @hey-api/openapi-ts

/**
 * SystemLinkResponse
 */
export type SystemLinkResponse = {
  /**
   * System Fides Key
   */
  system_fides_key: string;
  /**
   * System Name
   */
  system_name?: string | null;
  /**
   * Created At
   */
  created_at: string;
};
