// This file is auto-generated by @hey-api/openapi-ts

/**
 * SystemMetadata
 *
 * The SystemMetadata resource model.
 *
 * Object used to hold application specific metadata for a system
 */
export type SystemMetadata = {
  /**
   * Resource Id
   *
   * The external resource id for the system being modeled.
   */
  resource_id?: string | null;
  /**
   * Endpoint Address
   *
   * The host of the external resource for the system being modeled.
   */
  endpoint_address?: string | null;
  /**
   * Endpoint Port
   *
   * The port of the external resource for the system being modeled.
   */
  endpoint_port?: string | null;
};
