// This file is auto-generated by @hey-api/openapi-ts

/**
 * SystemPurposeSummary
 *
 * A summary of privacy declaration information for a system aggregated by TCF purpose.
 */
export type SystemPurposeSummary = {
  /**
   * Fides Key
   */
  fides_key: string;
  /**
   * Name
   */
  name: string;
  /**
   * Purposes
   */
  purposes: {
    [key: string]: {
      [key: string]: Array<unknown>;
    };
  };
  /**
   * Features
   */
  features: Array<string>;
  /**
   * Data Categories
   */
  data_categories: Array<string>;
};
