// This file is auto-generated by @hey-api/openapi-ts

/**
 * TaxonomyResponse
 *
 * Response schema for taxonomy resources.
 */
export type TaxonomyResponse = {
  /**
   * Fides Key
   *
   * Taxonomy type key
   */
  fides_key: string;
  /**
   * Name
   *
   * Display name for the taxonomy
   */
  name?: string | null;
  /**
   * Description
   *
   * Taxonomy description
   */
  description?: string | null;
  /**
   * Applies To
   *
   * List of resource types this taxonomy can be applied to
   */
  applies_to?: Array<string>;
};
