// This file is auto-generated by @hey-api/openapi-ts

import { TCFRestrictionType } from "./TCFRestrictionType";

/**
 * TCFConfigurationDetail
 *
 * Schema for TCF Configuration detail responses
 */
export type TCFConfigurationDetail = {
  /**
   * Id
   *
   * The unique identifier of the TCF Configuration
   */
  id: string;
  /**
   * Name
   *
   * The unique name of the TCF Configuration
   */
  name: string;
  /**
   * Restriction Types Per Purpose
   *
   * The restriction_types defined for this configuration, grouped per purpose
   */
  restriction_types_per_purpose?: {
    [key: string]: Array<TCFRestrictionType>;
  };
};
