// This file is auto-generated by @hey-api/openapi-ts

/**
 * TCFLegalBasisEnum
 *
 * Restricts the Legal Basis to just those that are relevant for TCF
 */
export enum TCFLegalBasisEnum {
  CONSENT = "Consent",
  LEGITIMATE_INTERESTS = "Legitimate interests",
}
