// This file is auto-generated by @hey-api/openapi-ts

import type { EmbeddedVendor } from "./EmbeddedVendor";
import { UserConsentPreference } from "./UserConsentPreference";

/**
 * TCFPurposeConsentRecord
 *
 * Schema for a TCF Purpose with Consent Legal Basis returned in the TCF Overlay Experience
 */
export type TCFPurposeConsentRecord = {
  /**
   * Id
   *
   * Official GVL purpose ID. Used for linking with other records, e.g. vendors, cookies, etc.
   */
  id: number;
  /**
   * Name
   *
   * Name of the GVL purpose.
   */
  name: string;
  /**
   * Description
   *
   * Description of the GVL purpose.
   */
  description: string;
  /**
   * Illustrations
   *
   * Illustrative examples of the purpose.
   */
  illustrations: Array<string>;
  /**
   * Data Uses
   *
   * The fideslang default taxonomy data uses that are associated with the purpose.
   */
  data_uses: Array<string>;
  default_preference?: UserConsentPreference | null;
  /**
   * Vendors
   */
  vendors?: Array<EmbeddedVendor>;
  /**
   * Systems
   */
  systems?: Array<EmbeddedVendor>;
};
