// This file is auto-generated by @hey-api/openapi-ts

import type { TCFFeatureSave } from "./TCFFeatureSave";
import type { TCFPurposeSave } from "./TCFPurposeSave";
import type { TCFSpecialFeatureSave } from "./TCFSpecialFeatureSave";
import type { TCFSpecialPurposeSave } from "./TCFSpecialPurposeSave";
import type { TCFVendorSave } from "./TCFVendorSave";

/**
 * TCFPreferences
 *
 * All TCF Attributes against which consent can be saved
 */
export type TCFPreferences = {
  /**
   * Purpose Consent Preferences
   */
  purpose_consent_preferences?: Array<TCFPurposeSave>;
  /**
   * Purpose Legitimate Interests Preferences
   */
  purpose_legitimate_interests_preferences?: Array<TCFPurposeSave>;
  /**
   * Vendor Consent Preferences
   */
  vendor_consent_preferences?: Array<TCFVendorSave>;
  /**
   * Vendor Legitimate Interests Preferences
   */
  vendor_legitimate_interests_preferences?: Array<TCFVendorSave>;
  /**
   * Special Feature Preferences
   */
  special_feature_preferences?: Array<TCFSpecialFeatureSave>;
  /**
   * Special Purpose Preferences
   */
  special_purpose_preferences?: Array<TCFSpecialPurposeSave>;
  /**
   * Feature Preferences
   */
  feature_preferences?: Array<TCFFeatureSave>;
  /**
   * System Consent Preferences
   */
  system_consent_preferences?: Array<TCFVendorSave>;
  /**
   * System Legitimate Interests Preferences
   */
  system_legitimate_interests_preferences?: Array<TCFVendorSave>;
};
