// This file is auto-generated by @hey-api/openapi-ts

import { UserConsentPreference } from "./UserConsentPreference";

/**
 * TCFSpecialFeatureSave
 *
 * Schema for saving a user's preference with respect to a TCF special feature
 */
export type TCFSpecialFeatureSave = {
  /**
   * Id
   */
  id: number;
  preference: UserConsentPreference;
};
