// This file is auto-generated by @hey-api/openapi-ts

/**
 * TemplateVariable
 *
 * Describes an available template variable for the UI template editor.
 *
 * Returned by :meth:`JiraTemplateService.get_template_variables` so
 * the frontend can present a list of insertable variables.
 */
export type TemplateVariable = {
  /**
   * Name
   *
   * Variable name as used in templates (e.g., 'request_id')
   */
  name: string;
  /**
   * Description
   *
   * Human-readable description of the variable
   */
  description: string;
  /**
   * Example Value
   *
   * Example value for preview rendering
   */
  example_value?: string | null;
};
