// This file is auto-generated by @hey-api/openapi-ts

/**
 * TestWebsiteMonitorParams
 *
 * Configuration parameters for the test website monitor
 */
export type TestWebsiteMonitorParams = {
  /**
   * Locations
   *
   * The locations from which the website should be monitored
   */
  locations?: Array<string> | null;
  /**
   * Exclude Domains
   *
   * List of domains to exclude from monitoring
   */
  exclude_domains?: Array<string> | null;
  /**
   * Sitemap Url
   *
   * URL to a sitemap.xml file that will be used to discover pages to monitor
   */
  sitemap_url?: string | null;
  /**
   * Num Cookies
   *
   * Number of test cookies to generate
   */
  num_cookies?: number;
  /**
   * Num Javascript Requests
   *
   * Number of test JavaScript requests to generate
   */
  num_javascript_requests?: number;
  /**
   * Num Image Requests
   *
   * Number of test image requests to generate
   */
  num_image_requests?: number;
  /**
   * Num Iframe Requests
   *
   * Number of test iframe requests to generate
   */
  num_iframe_requests?: number;
  /**
   * Num Browser Requests
   *
   * Number of general browser requests to generate
   */
  num_browser_requests?: number;
  /**
   * Test Domains
   *
   * List of test domains to use in generated assets
   */
  test_domains?: Array<string>;
  /**
   * Test Pages
   *
   * List of test pages where assets are discovered
   */
  test_pages?: Array<string>;
  /**
   * Test Locations
   *
   * List of test locations for asset discovery
   */
  test_locations?: Array<string>;
  /**
   * Consent Granted Percentage
   *
   * Percentage of assets that should be generated with granted consent (0.0 to 1.0)
   */
  consent_granted_percentage?: number;
  /**
   * Consent Denied Percentage
   *
   * Percentage of assets that should be generated with denied consent (0.0 to 1.0)
   */
  consent_denied_percentage?: number;
  /**
   * Consent Cmp Error Percentage
   *
   * Percentage of assets that should be generated with cmp_error consent (0.0 to 1.0)
   */
  consent_cmp_error_percentage?: number;
  /**
   * Cookie Names
   *
   * Sample cookie names to use
   */
  cookie_names?: Array<string>;
  /**
   * Cookie Values
   *
   * Sample cookie values to use
   */
  cookie_values?: Array<string>;
  /**
   * Vendor Match Percentage
   *
   * Percentage of assets that should be matched to vendors (0.0 to 1.0)
   */
  vendor_match_percentage?: number;
  /**
   * Test Vendor Ids
   *
   * List of test vendor IDs to assign to matched assets
   */
  test_vendor_ids?: Array<string>;
  /**
   * Experiences Data
   *
   * Experiences data for consent notice mapping. Uses default experiences data if not provided.
   */
  experiences_data?: {
    [key: string]: {
      [key: string]: unknown;
    };
  };
};
