// This file is auto-generated by @hey-api/openapi-ts

/**
 * TestMonitorParams
 *
 * Configuration parameters for the test monitor
 */
export type TestMonitorParams = {
  /**
   * Sharded Table Pattern
   *
   * Regex pattern to identify sharded tables
   */
  sharded_table_pattern?: string | null;
  /**
   * Num Databases
   *
   * Number of databases to generate
   */
  num_databases?: number;
  /**
   * Num Schemas Per Db
   *
   * Number of schemas to generate per database
   */
  num_schemas_per_db?: number;
  /**
   * Num Tables Per Schema
   *
   * Number of tables to generate per schema
   */
  num_tables_per_schema?: number;
  /**
   * Num Fields Per Table
   *
   * Number of fields to generate per table
   */
  num_fields_per_table?: number;
  /**
   * Field Sample Data
   *
   * Sample data to return for field sampling
   */
  field_sample_data?: Array<string>;
  /**
   * Max Nesting Level
   *
   * Maximum depth of nested fields
   */
  max_nesting_level?: number;
  /**
   * Nested Field Percentage
   *
   * Percentage of fields that should be nested (0.0 to 1.0)
   */
  nested_field_percentage?: number;
  /**
   * Num Fields Per Nested
   *
   * Number of fields to generate for each nested field
   */
  num_fields_per_nested?: number;
  /**
   * Simulate Classification
   *
   * Whether to simulate classification when calling the /classify endpoint
   */
  simulate_classification?: boolean;
  /**
   * Classification Sleep Seconds
   *
   * Number of seconds to sleep during classification to simulate processing time
   */
  classification_sleep_seconds?: number;
};
