// This file is auto-generated by @hey-api/openapi-ts

/**
 * ToneResponse
 *
 * Response schema returning the active (resolved) tone prompt.
 */
export type ToneResponse = {
  /**
   * Questionnaire Tone Prompt
   */
  questionnaire_tone_prompt: string;
};
