// This file is auto-generated by @hey-api/openapi-ts

import type { IdentityRoot } from "./IdentityRoot";
import type { IntegrationNode } from "./IntegrationNode";
import type { ManualTaskNode } from "./ManualTaskNode";
import type { PreviewEdge } from "./PreviewEdge";
import type { PropertyRef } from "./PropertyRef";

/**
 * TraversalPreviewResponse
 */
export type TraversalPreviewResponse = {
  property: PropertyRef;
  /**
   * Action Type
   */
  action_type: "access" | "erasure";
  /**
   * Computed At
   */
  computed_at: string;
  /**
   * Cache Hit
   */
  cache_hit: boolean;
  identity_root: IdentityRoot;
  /**
   * Integrations
   */
  integrations: Array<IntegrationNode>;
  /**
   * Manual Tasks
   */
  manual_tasks: Array<ManualTaskNode>;
  /**
   * Edges
   */
  edges: Array<PreviewEdge>;
  /**
   * Warnings
   */
  warnings?: Array<string>;
};
