// This file is auto-generated by @hey-api/openapi-ts

import type { PropertyRef } from "./PropertyRef";

/**
 * TraversalPreviewResponse
 */
export type TraversalPreviewResponse = {
  property: PropertyRef;
  /**
   * Action Type
   */
  action_type: "access" | "erasure";
  /**
   * Computed At
   */
  computed_at: string;
  /**
   * Cache Hit
   */
  cache_hit: boolean;
  /**
   * Identity Root
   */
  identity_root: {
    [key: string]: unknown;
  };
  /**
   * Integrations
   */
  integrations: Array<{
    [key: string]: unknown;
  }>;
  /**
   * Manual Tasks
   */
  manual_tasks: Array<{
    [key: string]: unknown;
  }>;
  /**
   * Edges
   */
  edges: Array<{
    [key: string]: unknown;
  }>;
  /**
   * Warnings
   */
  warnings?: Array<string>;
};
