// This file is auto-generated by @hey-api/openapi-ts

/**
 * UnverifiedIdentity
 *
 * Exclude email and phone number from the identity
 */
export type UnverifiedIdentity = {
  /**
   * GA client ID
   */
  ga_client_id?: string | null;
  /**
   * LJT reader ID
   */
  ljt_readerID?: string | null;
  /**
   * Fides user device ID
   */
  fides_user_device_id?: string | null;
  /**
   * External ID
   */
  external_id?: string | null;
  [key: string]:
    | unknown
    | string
    | null
    | string
    | null
    | string
    | null
    | string
    | null
    | undefined;
};
