// This file is auto-generated by @hey-api/openapi-ts

/**
 * UpdateMonitorStewardsRequest
 *
 * Request schema for updating the stewards on a specific monitor.
 */
export type UpdateMonitorStewardsRequest = {
  /**
   * User Ids
   *
   * List of user IDs to set as stewards for this monitor
   */
  user_ids: Array<string>;
};
