// This file is auto-generated by @hey-api/openapi-ts

import { RoleRegistryEnum } from "./RoleRegistryEnum";
import { ScopeRegistryEnum } from "./ScopeRegistryEnum";

/**
 * UserPermissionsPlusResponse
 *
 * Response after creating, editing, or retrieving a FidesUserPermissions record.
 *
 * Overrides in Plus to use the Plus ScopeRegistryEnum so Plus scopes are returned.
 */
export type UserPermissionsPlusResponse = {
  /**
   * Roles
   */
  roles: Array<RoleRegistryEnum>;
  /**
   * Id
   */
  id: string;
  /**
   * User Id
   */
  user_id: string;
  /**
   * Total Scopes
   */
  total_scopes: Array<ScopeRegistryEnum>;
};
