// This file is auto-generated by @hey-api/openapi-ts

/**
 * UserUpdate
 *
 * Data required to update a FidesUser
 */
export type UserUpdate = {
  /**
   * Email Address
   */
  email_address?: string | null;
  /**
   * First Name
   */
  first_name?: string | null;
  /**
   * Last Name
   */
  last_name?: string | null;
};
