// This file is auto-generated by @hey-api/openapi-ts

import type { AccessToken } from "./AccessToken";
import type { UserResponse } from "./UserResponse";

/**
 * UserLoginResponse
 *
 * Similar to UserResponse except with an access token
 */
export type UserLoginResponse = {
  user_data: UserResponse;
  token_data: AccessToken;
};
