// This file is auto-generated by @hey-api/openapi-ts

import { RoleRegistryEnum } from "./RoleRegistryEnum";

/**
 * UserPermissionsCreate
 *
 * Data required to create a FidesUserPermissions record
 *
 * Users will be assigned role(s) directly which are associated with a list of scopes. Scopes
 * cannot be assigned directly to users.
 */
export type UserPermissionsCreate = {
  /**
   * Roles
   */
  roles: Array<RoleRegistryEnum>;
};
