// This file is auto-generated by @hey-api/openapi-ts

/**
 * UserResponse
 *
 * Response after requesting a User
 */
export type UserResponse = {
  /**
   * Id
   */
  id: string;
  /**
   * Username
   */
  username: string;
  /**
   * Created At
   */
  created_at: string;
  /**
   * Email Address
   */
  email_address: string | null;
  /**
   * First Name
   */
  first_name?: string | null;
  /**
   * Last Name
   */
  last_name?: string | null;
  /**
   * Disabled
   */
  disabled?: boolean | null;
  /**
   * Disabled Reason
   */
  disabled_reason?: string | null;
  /**
   * Email Verified At
   */
  email_verified_at?: string | null;
  /**
   * Has Invite
   */
  has_invite?: boolean | null;
  /**
   * Invite Expired
   */
  invite_expired?: boolean | null;
};
