// This file is auto-generated by @hey-api/openapi-ts

import { ValidationStatus } from "./ValidationStatus";

/**
 * ValidateResponse
 *
 * Validate endpoint response object
 */
export type ValidateResponse = {
  status: ValidationStatus;
  /**
   * Message
   */
  message: string;
};
