// This file is auto-generated by @hey-api/openapi-ts

import type { VendorBreakdownItem } from "./VendorBreakdownItem";

/**
 * VendorBreakdownResponse
 */
export type VendorBreakdownResponse = {
  /**
   * Vendors
   *
   * Per-vendor breakdown rows. Sorted by ``resource_count`` desc; the synthetic ``unknown`` rollup, when present, is always last.
   */
  vendors?: Array<VendorBreakdownItem>;
};
