// This file is auto-generated by @hey-api/openapi-ts

import type { VendorDataUse } from "./VendorDataUse";

/**
 * VendorBreakdownItem
 *
 * One row in the per-vendor breakdown.
 */
export type VendorBreakdownItem = {
  /**
   * Vendor Id
   *
   * Compass vendor_id or system identifier attributed to the resources, or the literal ``"unknown"`` for the synthetic unattributed rollup row.
   */
  vendor_id: string;
  /**
   * Name
   *
   * Resolved vendor display name — System name when a matching ctl_systems row exists, else Compass dictionary name. ``Unknown`` for the synthetic unattributed bucket.
   */
  name: string;
  /**
   * Resource Count
   *
   * Distinct resources attributed to this vendor.
   */
  resource_count?: number;
  /**
   * Locations
   *
   * Sorted, deduped union of ``StagedResource.meta.locations`` across the resources tied to this vendor — the actual scan locations observed for this vendor's resources, not the monitor's intended scan-region config. See response-level ``monitor_locations`` for the configured-scan union used by the cover page.
   */
  locations?: Array<string>;
  /**
   * Data Uses
   */
  data_uses?: Array<VendorDataUse>;
};
