// This file is auto-generated by @hey-api/openapi-ts

/**
 * VendorMatchStats
 *
 * Statistics about vendor matching to Compass.
 */
export type VendorMatchStats = {
  /**
   * Total With Vendor Name
   *
   * Resources where LLM identified a vendor name
   */
  total_with_vendor_name: number;
  /**
   * Matched To Compass
   *
   * Resources successfully matched to Compass vendor_id
   */
  matched_to_compass: number;
  /**
   * Match Rate
   *
   * Percentage of vendor names matched to Compass
   */
  match_rate: number;
  /**
   * Unregistered Ad Vendors
   *
   * Resources flagged as potential unregistered ad vendors
   */
  unregistered_ad_vendors: number;
  /**
   * Top Unmatched Vendors
   *
   * Most common vendor names not found in Compass
   */
  top_unmatched_vendors?: Array<string>;
};
