// This file is auto-generated by @hey-api/openapi-ts

/**
 * VerificationCode
 *
 * Request Body for the user to supply their identity verification code
 */
export type VerificationCode = {
  /**
   * Code
   */
  code: string;
};
