// This file is auto-generated by @hey-api/openapi-ts

/**
 * WebsiteSchema
 *
 * Schema to validate the secrets needed for a generic website connector
 */
export type WebsiteSchema = {
  /**
   * URL
   */
  url: string;
};
