// This file is auto-generated by @hey-api/openapi-ts

/**
 * WebsiteMonitorParams
 */
export type WebsiteMonitorParams = {
  /**
   * Locations
   *
   * The locations from which the website should be monitored
   */
  locations?: Array<string> | null;
  /**
   * Exclude Domains
   *
   * List of domains to exclude from monitoring
   */
  exclude_domains?: Array<string> | null;
  /**
   * Sitemap Url
   *
   * URL to a sitemap.xml file that will be used to discover pages to monitor
   */
  sitemap_url?: string | null;
};
