name: Check PR Size
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  check-pr-size:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR size
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;

            // Fetch all files (handles pagination automatically)
            const files = await github.paginate(github.rest.pulls.listFiles, {
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pr.number,
            });

            // Calculate total lines from ALL files (including renamed)
            const additions = files.reduce((sum, file) => sum + file.additions, 0);
            const deletions = files.reduce((sum, file) => sum + file.deletions, 0);
            const totalLinesChanged = additions + deletions;

            // Count files excluding renamed ones
            const nonRenamedFiles = files.filter(file => file.status !== 'renamed');
            const changedFiles = nonRenamedFiles.length;

            const linesLimit = 500;
            const filesLimit = 15;

            let failMessage = '';

            if (totalLinesChanged > linesLimit) {
              failMessage += `Lines changed: ${totalLinesChanged} (limit: ${linesLimit})\n`;
            }

            if (changedFiles > filesLimit) {
              failMessage += `Files changed: ${changedFiles} (limit: ${filesLimit})\n`;
            }

            if (failMessage) {
              const renamedCount = files.length - nonRenamedFiles.length;
              if (renamedCount > 0) {
                failMessage += `(${renamedCount} renamed/moved file(s) excluded from file count)\n`;
              }
              failMessage += '\nPlease consider splitting this PR into smaller, more focused changes.';

              core.setFailed(failMessage);
            } else {
              const renamedCount = files.length - nonRenamedFiles.length;
              console.log(`PR size check passed (${totalLinesChanged} lines, ${changedFiles} files${renamedCount > 0 ? `, ${renamedCount} renamed files excluded from count` : ''})`);
            }
