name: Publish the CLI on Conda

# on:
#   push:
#     tags:
#       - "*"
on:
  pull_request:
    branches:
      - main
    paths:
      - "*"
jobs:
  upload_to_conda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Anaconda
        run: |
          wget -P /tmp https://repo.anaconda.com/archive/Anaconda3-2020.02-Linux-x86_64.sh
          bash /tmp/Anaconda3-2020.02-Linux-x86_64.sh -b
      - name: Conda Upload
        run: |
          conda install conda-build
          conda build --output-folder ./conda-out/ ./fidesctl/conda/ -c plotly -c conda-forge
          anaconda -t "${{ secrets.CONDA_TOKEN }}" upload -u ethyca ./conda-out/noarch/fidesctl*.bz2
