name: Docker Build & Push Privacy Center

on:
  push:
    tags:
      - "*"

env:
  DOCKER_USER: ethycaci
  DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}

jobs:
  push-fides-privacy-center-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_USER }}
          password: ${{ env.DOCKER_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ethyca/fides-privacy-center

      - name: Build and publish
        uses: docker/build-push-action@v3
        with:
          context: ./clients/ops/privacy-center
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
