name: Docker Build & Push Privacy Center

on:
  push:
    branches:
      - main
    paths:
      - "clients/ops/privacy-center
    tags:
      - "*"

env:
  DOCKER_USER: ethycaci
  DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}

jobs:
  push-fidesops-privacy-center-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_USER }}  # Needs updating for fidesops privacy center
          password: ${{ env.DOCKER_TOKEN }}  # Needs updating for fidesops privacy center

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@4
        with:
          images: ethyca/fidesops-privacy-center

      - name: Change to privacy center directory
        run: cd clients/ops/privacy-center

      - name: Build and publish
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labes: ${{ steps.metadata.outputs.labesl }}
