name: Notify Downstream Projects of Release

on:
  release:
    types: [released]

jobs:
  fidesops-plus:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.DISPATCH_ACCESS_TOKEN }}
          repository: ethyca/fidesops-plus
          event-type: new-fidesops-release
          client-payload: '{"tag": "${{ github.event.release.tag_name }}", "url": "${{ github.event.release.html_url }}"}'

  fidesdemo:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.DISPATCH_ACCESS_TOKEN }}
          repository: ethyca/fidesdemo
          event-type: new-fidesops-release
          client-payload: '{"tag": "${{ github.event.release.tag_name }}", "url": "${{ github.event.release.html_url }}"}'
