name: Notify Downstream Projects of Release

on:
  release:
    types: [released]

jobs:
  fidesplus:
    runs-on: ubuntu-latest
    steps:
      - name: Send Repository Dispatch Event
        uses: peter-evans/repository-dispatch@v2
        with:
          client-payload: '{"tag": "${{ github.event.release.tag_name }}", "url": "${{ github.event.release.html_url }}"}'
          event-type: new-fides-release
          repository: ethyca/fidesplus
          token: ${{ secrets.DISPATCH_ACCESS_TOKEN }}

  fidesdocs:
    runs-on: ubuntu-latest
    steps:
      - name: Send Repository Dispatch Event
        uses: peter-evans/repository-dispatch@v2
        with:
          client-payload: '{"tag": "${{ github.event.release.tag_name }}", "url": "${{ github.event.release.html_url }}"}'
          event-type: new-fides-release
          repository: ethyca/fidesdocs
          token: ${{ secrets.DISPATCH_ACCESS_TOKEN }}

  fides-helm:
    runs-on: ubuntu-latest
    steps:
      - name: Send Repository Dispatch Event
        uses: peter-evans/repository-dispatch@v2
        with:
          client-payload: '{"tag": "${{ github.event.release.tag_name }}", "url": "${{ github.event.release.html_url }}"}'
          event-type: new-fides-release
          repository: ethyca/fides-helm
          token: ${{ secrets.DISPATCH_ACCESS_TOKEN }}
