name: Notify Downstream Projects of Release

on:
  release:
    types: [released]

jobs:
  fidesctl-plus:
    runs-on: ubuntu-latest
    steps:
      - name: Send Repository Dispatch Event
        uses: peter-evans/repository-dispatch@v2
        with:
          client-payload: '{"tag": "${{ github.event.release.tag_name }}", "url": "${{ github.event.release.html_url }}"}'
          event-type: new-fides-release
          repository: ethyca/fidesctl-plus
          token: ${{ secrets.DISPATCH_ACCESS_TOKEN }}

  fidesops-plus:
    runs-on: ubuntu-latest
    steps:
      - name: Send Repository Dispatch Event
        uses: peter-evans/repository-dispatch@v2
        with:
          client-payload: '{"tag": "${{ github.event.release.tag_name }}", "url": "${{ github.event.release.html_url }}"}'
          event-type: new-fides-release
          repository: ethyca/fidesops-plus
          token: ${{ secrets.DISPATCH_ACCESS_TOKEN }}
