name: CI Checks - Safe
on: [
  pull_request
]

jobs:
  Autoformat:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running CI for branch ${{ github.ref }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: make black-ci

  Check-Migrations:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running CI for branch ${{ github.ref }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: make init-db
      - run: make check-migrations

  Lint:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running CI for branch ${{ github.ref }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: make pylint

  Check-Types:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running CI for branch ${{ github.ref }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: make mypy

  Unit-Tests:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running CI for branch ${{ github.ref }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: make pytest

  Integration-Tests-Access:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running CI for branch ${{ github.ref }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: make pytest-integration-access

  Integration-Tests-Erasure:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running CI for branch ${{ github.ref }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: make pytest-integration-erasure
