name: Python Static Checks

on:
  pull_request:
    paths-ignore:
      - "**.md"
  push:
    branches:
      - "main"

env:
  IMAGE: ethyca/fides:local
  DEFAULT_PYTHON_VERSION: "3.10.7"

# Matrix this
jobs:
  Static-Checks:
    strategy:
      matrix:
        session_name: ["isort", "black", "mypy", "pylint", "xenon"]
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.DEFAULT_PYTHON_VERSION }}

      - name: Install Nox
        run: pip install nox>=2022

      - name: Run Static Check
        run: nox -s ${{ matrix.session_name }}
