name: Tests

# Only test on Pull Requests that target main
on:
  pull_request:
    branches:
      - main
    paths: # Only run tests when certain paths change
      - fidesctl/**
      - .github/workflows/test.yaml

jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build the Docker Images
        run: make compose-build

      - name: Check fidesctl installed
        run: make check-install

      - name: Fidesctl Evaluation
        run: make fidesctl

      - name: Format
        run: make black

      - name: Lint
        run: make pylint

      - name: TypeCheck
        run: make mypy

      - name: Complexity Check
        run: make xenon

      - name: Test
        run: make pytest
