name: Tests

# Only test on Pull Requests that target main
on:
  pull_request:
    branches:
      - main
    paths: # Only run tests when certain paths change
      - fidesctl/**
      - .github/workflows/test.yaml

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build the Docker Images
        run: make compose-build

      - name: Check fidesctl installed
        run: make check-install

      - name: Format
        run: make black

      - name: Lint
        run: make pylint

      - name: TypeCheck
        run: make mypy

      - name: Complexity Check
        run: make xenon

      - name: Test
        run: make pytest

  Fidesctl:
    runs-on: ubuntu-latest
    container:
      image: ethyca/fidesctl:latest

    steps:
      - uses: actions/checkout@v2

      - name: Local Evaluation
        run: fidesctl evaluate --local fidesctl/fides_resources/
        env:
          FIDESCTL_CONFIG_PATH: fidesctl/fidesctl.toml
