name: Test Fidesctl & Fides Server

# Only test on Pull Requests that target main
on:
  pull_request:
    branches:
      - main
    paths: # Only run tests when certain paths change
      - fidesctl/**
      - .github/workflows/test.yaml

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build the Docker Images
        run: make compose-build

      - name: Check fidesctl installed
        run: make check-install

      - name: Format Fidesctl
        run: make black

      - name: Lint Fidesctl
        run: make pylint

      - name: TypeCheck Fidesctl
        run: make mypy

      - name: Complexity Check
        run: make xenon

      - name: Test Fidesctl
        run: make pytest
