name: CI Checks - Unsafe
on:
  push:
    branches:
      - main
  pull_request:
    types: [labeled]

jobs:
  External-Datastores:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'run unsafe ci checks')
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Integration Tests (External)
        env:
          REDSHIFT_TEST_URI: ${{ secrets.REDSHIFT_TEST_URI }}
          REDSHIFT_TEST_DB_SCHEMA: ${{ secrets.REDSHIFT_TEST_DB_SCHEMA }}
          BIGQUERY_KEYFILE_CREDS: ${{ secrets.BIGQUERY_KEYFILE_CREDS }}
          BIGQUERY_DATASET: ${{ secrets.BIGQUERY_DATASET }}
          SNOWFLAKE_TEST_URI: ${{ secrets.SNOWFLAKE_TEST_URI }}
        run: make pytest-integration-external


  External-SaaS-Connectors:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'run unsafe ci checks')
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get Vault Token
        uses: hashicorp/vault-action@v2.4.1
        with:
          url: ${{ secrets.VAULT_ADDR }}
          namespace: ${{ secrets.VAULT_NAMESPACE }}
          method: jwt
          role: ${{ secrets.VAULT_ROLE }}
          exportToken: True

      - name: SaaS Connector Tests
        env:
          VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
          VAULT_NAMESPACE: ${{ secrets.VAULT_NAMESPACE }}
        run: make pytest-saas
